### ISSUE TITLE
Authentication with nodejs

### ISSUE THREAD

**Issue by RezaErfani67** [Aymkdn/SharepointPlus#103]
hi Aymkdn
i sign in to sharepoint successfully with below example
```javascript
const credentials = {
  username:'my_username',
  password:'mypassword',
  domain:'mydomain'
};
```

but i want login with current user of windows(domain user) without entering username and pasword.
how can i do this?

**Comment by Aymkdn** [comment]
You can't. I believe this is not possible when using Node.

**Comment by RezaErfani67** [comment]
@koltyakov what is your idea?
