### ISSUE TITLE
Issue using formfields. 

### ISSUE THREAD

**Issue by morph1904** [Aymkdn/SharepointPlus#108]
Hi, 

I am using the formfields plugin and trying a simple line of:

`$SP().formfields("Title").row().hide();`

However this does not appear to be doing anything, there are also no errors in the console. When i run the command directly in the console, I simply get an object returned. 

`{}​<prototype>: Object { jquery: "2.2.4", constructor: n(), length: 0, … } `

Please can you help?

**Comment by Aymkdn** [comment]
Hi,

If you have jQuery loaded, then typing `console.log($SP().formfields("Title").row())` should display the jQuery object that represents the `TR` for the field called `Title`. Can you try this and let me know what the console returns?

Are you into a `EditForm.aspx` or `NewForm.aspx` page ? Is it Sharepoint 2010 or Sharepoint 2013 ? Any other details ?

**Comment by morph1904** [comment]
Hi Aymkdn, 

Thanks for your assistance. I tried the command and it returned an empty JQuery object. I was using a newly created NewForm.aspx I took a copy of the SharePoint standard NewForm.aspx, renamed it and tried again. This time it worked. SharePoint must be doing something strange with a new version of the forms. 

Thanks again for your assistance.

**Comment by Aymkdn** [comment]
Yeah, `formfields` uses the default form structure, so you have to use the default ones provided by Sharepoint.

I'm glad it worked :)
