### ISSUE TITLE
Node.js version requires storing credentials?

### ISSUE THREAD

**Issue by TheHanna** [Aymkdn/SharepointPlus#109]
Correct me if I'm wrong, but the current implementation of the `node-sp-auth` library in this project requires storing the users credentials (in my case, using ADFS, so username, password, domain, ADFS url, and ADFS cookie name). Isn't this generally regarded as a bad idea from a security standpoint?

These credentials would need to be kept in memory on the server side. Wouldn't the better approach to store the _result_ of using `node-sp-auth` (the FedAuth cookie, bearer token, or headers object generated by `node-sp-auth`) rather than continually calling using the raw credentails? It reduces the potential attack surface in cases where the server is compromised and the credentials are leaked. If you use the result, they have access to SharePoint. If you use the raw credentials (username, password) they could get access to a whole host of enterprise systems.

**Comment by Aymkdn** [comment]
> Isn't this generally regarded as a bad idea from a security standpoint?

Yes...

As you said, Sharepointplus `auth()` is based on [node-sp-auth](https://github.com/s-KaiNet/node-sp-auth). So in `$SP().auth(credentialOptions)` the `credentialOptions` is passed to `getAuth()` from `node-sp-auth`.

The purpose of Sharepointplus is not to manage the authentication system with Sharepoint: it's the role of [node-sp-auth](https://github.com/s-KaiNet/node-sp-auth). So you may want to open an issue on that repository.

If you think we can already leverage `node-sp-auth` to improve the auth system of Sharepointplus, then please provide me more details and I'll be happy to investigate !

**Comment by TheHanna** [comment]
I will fork and try to cook up a pull request that allows for using the return value from the `getAuth()` function in `node-sp-auth`.

Looking through `node-sp-auth` and the various methods it provides, it appears the return value will always be an object, with 1 to 2 keys. It will always have a `headers` key, and may have an `options` key. If those headers and options can be provided to this library for use, auth will be implicit, and fully within the developers control. Wouldn't even necessarily need to use `node-sp-auth` if they couldn't/didn't want to for some reason.

**Comment by Aymkdn** [comment]
Any lead so far ?

Also, to which Sharepoint are you trying to auth with ?

**Comment by koltyakov** [comment]
@TheHanna, 

`node-sp-auth` has a mode to deal with encrypted secrets based on custom encryption master key or machineId which is used by default. We use `cpass` module to never ever store raw secrets.
Also, you're always free in providing required creds prepared and stored in memory and never dump any creds to disc. E.g. in CI/CD processes environment variables should be used.

Auth cookies/tokens have limited, sometimes very limited, time to live. `node-sp-auth` caches cookies/tokens and checks for expiration times and requests for new cookies/tokens only when it should update cached. Of course, having a token you "don't need" node-sp-auth, until it has to be refreshed, but at the same time calling getAuth method on each request is also effective, it's just reading a cached token or updating it if one is expired.

P.S. Feel free chat about these option in our Gitter channel https://gitter.im/sharepoint-node/Lobby

**Comment by Aymkdn** [comment]
With no further reply, I'm closing this issue. Feel free to keep commenting here if you want to.
