### ISSUE TITLE
addressbook method - Unable to pass 'word' parameter as a variable

### ISSUE THREAD

**Issue by greddin** [Aymkdn/SharepointPlus#110]
This way works:  

`$SP().addressbook("john", {limit:25}).then(function(people)`

But it seems I can't pass a string variable in like this:

```
var myUser = "john";
$SP().addressbook(myUser, {limit:25}).then(function(people)

```
Is this possible?

Thanks!

**Comment by Aymkdn** [comment]
It works in both way. You probably has an incorrect value in your `myUser`
