### ISSUE TITLE
Promise is undefined error in IE

### ISSUE THREAD

**Issue by greddin** [Aymkdn/SharepointPlus#111]
I getting the following error in IE browser only.  This is from the console.

SCRIPT5009: 'Promise' is undefined
sharepointplus-5.1-min.js (8,2474)

Any ideas?

**Comment by Aymkdn** [comment]
Yes, you need a [promise polyfill](https://github.com/taylorhakes/promise-polyfill), as explained on the homepage : https://aymkdn.github.io/SharepointPlus/
