### ISSUE TITLE
getUserInfo

### ISSUE THREAD

**Issue by RezaErfani67** [Aymkdn/SharepointPlus#112]
hi
thanks for v 5.1
getUserInfo not works with then()...
it works good with callback function...

this example on your site return error:
```javascript
$SP().getUserInfo("domain\\john_doe",{url:"http://my.si.te/subdir/"}).then(function(info) {
  alert("User ID = "+info.ID)
}, function(error) {
  console.log(error)
});
```
error is:
Uncaught [SharepointPlus] You tried to use `then()` however your browser doesn't support Promise, and you don't use jQuery. Please refer to the documentation.

i use  chrome and it support then() promise

**Comment by Aymkdn** [comment]
I believe you don't use the last version, do you ?

Try : `$SP().getVersion()` please
