### ISSUE TITLE
detect user on node js

### ISSUE THREAD

**Issue by RezaErfani67** [Aymkdn/SharepointPlus#113]
with nodejs,how can i detect witch user send request?

**Comment by Aymkdn** [comment]
You have to use `auth()` when using NodeJS.... So the user is the one defined with `auth()`...

**Comment by RezaErfani67** [comment]
i want use nodejs for specific date validation...
but this validation not need for some users such as site manager.
i want a way that can detect witch user send request from sharepoint to nodejs server and validate it if candidate...

**Comment by RezaErfani67** [comment]
ok.thanks :)
