### ISSUE TITLE
People Search not working with new version

### ISSUE THREAD

**Issue by kingjtiv** [Aymkdn/SharepointPlus#114]
Wanted to know if the PeopleHead plugin works for version 5.1

**Comment by Aymkdn** [comment]
I think it won't, just because of this line : https://github.com/Aymkdn/SharepointPlus/blob/master/plugins/peopleahead/sp-plugin.peopleahead.js#L96

It should be :
```javascript
$SP().addressbook($this.val(),{limit:options.limit}).then(function(data) {
```

I will change it when I'll release SharepointPlus 5.2

**Comment by kingjtiv** [comment]
That did the trick.  Much appreciated.

**Comment by kingjtiv** [comment]
This is awesome. One last question can you limit the people that are returned by passing a group or list of users.

**Comment by Aymkdn** [comment]
Nope. But you can try to change parameters https://aymkdn.github.io/SharepointPlus/people.html#addressbook
