### ISSUE TITLE
Unable to catch error in $SP().lists()

### ISSUE THREAD

**Issue by Zireael** [Aymkdn/SharepointPlus#116]
Hi,
I don't seem to be able to catch promise resolve error in:

```
  SPlistsInfo() {
       $SP()
      .lists({ url: "www.mysite.com", cache: false })
      .then(function(lists) {
        console.log(lists)
      })
      .catch(function(error) {
        console.log("Error: ", error);
      });
  }
```
Getting uncaught error:

> Uncaught (in promise) {statusCode: 500, responseText: [...]

I am able to catch the same error with user query:
```
whoamiSP() {
      $SP()
      .whoami({ url: "www.mysite.com" })
      .then(function(people) {
        console.log(people)
      })
      .catch(function(error) {
        console.log("Error: ", error);
      });
  }
```
Getting caught error:
> {statusCode: 500, responseText: [...]

This one catches properly as well, for example:

```
$SP()
      .list("someList", "www.mywebsite.com")
      .update(payload.data)
      .then(function(items) {})
      .catch(function(error) {
        console.log("Error: ", error);
      });

```
I'm calling both functions from a block of code where they sit next to each other, so the problem is only from .lists() not letting me catch. I'm testing error handling by trying to query a Sharepoint site from which I'm logged out (thus getting error 500). Both blocks of code function when I'm logged in to the site.

I'd appreciate your advice. Thanks in advance.

**Comment by Aymkdn** [comment]
Hi,

I've just published SharepointPlus v5.2 and I've included a fix for this issue.

Thanks.
