### ISSUE TITLE
taxonomy fields / managed metadata

### ISSUE THREAD

**Issue by latonita** [Aymkdn/SharepointPlus#119]
Hello
I just got stuck with MS Graph API which cannot handle listItem field updates in case it is taxonomy fields or multi-selection fields.

Can this library help me update fields which are not just simple string or integer but look something like this object:
```
Account: {
     Label:"Account name",
      TermGuid:"f5be41bf-0f3d-4d18-b156-5258ac7959f4",
      WssId:36
}
```

thanks a lot

**Comment by Aymkdn** [comment]
Did you check https://github.com/Aymkdn/SharepointPlus/wiki/Add-or-Update-a-Term-aka-Taxonomy-aka-Managed-Metadata ?

**Comment by Aymkdn** [comment]
No reply so I'm closing it. If you have more questions, please feel free to post here.

**Comment by latonita** [comment]
@Aymkdn thanks, was off, this can be closed.
However I got into another issue. 
I'm goring through the document library. I read 3 taxonomy fields from top-most folders and then traverse down and setting those attributes to all files and folders under.
Folders being updated properly, but as for files - i notice that for 30% of files some attributes not updated. I mean it can happen that for first file taxonomy fields 1 and 2 updated, and 3rd - not. For next file - only 1 and 3 updated, and field 2 not updated... This is weird.

**Comment by Aymkdn** [comment]
I have no idea, sorry.
