### ISSUE TITLE
Slowing Down a Bit?

### ISSUE THREAD

**Issue by djpeterso23662** [Aymkdn/SharepointPlus#122]
Ciao Aymeric!  Thank you so much for $SP, it is a life-saver!  

I am trying to add 690 rows to lists, and SharePoint 2016 is failing somewhere in the work.  Can you recommend a good way to slow up the program enough that SharePoint will keep up?  Thanks! 

Ciao Aymeric! Merci beaucoup pour $ SP, c'est une bouée de sauvetage!

J'essaie d'ajouter 690 lignes aux listes et SharePoint 2016 échoue quelque part dans le travail. Pouvez-vous recommander un bon moyen de ralentir le programme suffisamment pour que SharePoint puisse suivre? Merci!

**Comment by Aymkdn** [comment]
Slowing it down? This is a weird question...

You could add a timeout between each request?!

**Comment by Aymkdn** [comment]
No reply... So I'm closing this issue!

**Comment by djpeterso23662** [comment]
I apologize for being slow responding.  It took me a couple days to restructure and test my code to submit requests at 3 second intervals.  I believe my SharePoint 2016 farm starts to ignore requests after around 120, with a 3 second interval between each request.  So, it not a SharePointPlus issue at this point.  Thank you very much for sharing SharePointPlus!  It is excellent!
