### ISSUE TITLE
Create File when using sp-rest-proxy

### ISSUE THREAD

**Issue by theparthy** [Aymkdn/SharepointPlus#124]
Hi, 
im trying to use sp-rest-proxy to access a on Promise SharePoint.
Everything works fine. 
Only creating files with additional fields is failing, as the Library tries to get the field infos from the non proxied Sharepoint and fails with a 403.  

```js     
const created = await $SP()
      .list(list, _SHAREPOINT_URL)
      .createFile({
        content: bufferFile,
        filename: `${filename}`,
        // fields: transformedData,
        progress: onProgress
      });
```
I've boiled it down to this Line https://github.com/Aymkdn/SharepointPlus/blob/9c7b198691c120c3cc7645ecb8d302d5730b342d/sharepointplus-5.2.js#L2290

Not sure if this is a $SP or a sp-rest-proxy issue, though!

Any Pointers how to circumvent the behaviour would be appreciated.

**Comment by koltyakov** [comment]
Hey @theparthy! It's more likely on sp-rest-proxy side, we got to transform some responses with endpoints replacement for the clients to work in localhost workbenches as SharePoint often sends absolute paths in props. Please post a linked issue with raw REST requests to reproduce (or, which is better, a minimal project to clone, restore and run) I'll take a look later on.

**Comment by Aymkdn** [comment]
If it's related to sp-rest-proxy, then I'll close this issue. Feel free to repost here or submit a new issue if it happens to be related to SharepointPlus :-)

Thanks @koltyakov !
