### ISSUE TITLE
Using SharepointPlus with client side framework (React)

### ISSUE THREAD

**Issue by hanadkubat** [Aymkdn/SharepointPlus#125]
Hello, can someone please write a clear guide how to use SP in a react project which is not directly deployed to Sharepoint, also it would bi nice to include a sample of $SP().auth() usage in this guide. This could also be helpful for other frameworks and libraries.

Thank you

**Comment by koltyakov** [comment]
Shameless plug =), use [generator-sppp](https://github.com/koltyakov/generator-sppp) and `npm run start` command. The generator contains configured [sp-rest-proxy](https://github.com/koltyakov/sp-rest-proxy) and Webpack dev server, as well as React presets and publishing tasks.

**Comment by Aymkdn** [comment]
The homepage https://aymkdn.github.io/SharepointPlus/ describes how to use it with Node/Webpack. Is it not enough? It's what I use for my Vue projects. What else do you need?

Regarding `auth` there is an example in the documentation https://aymkdn.github.io/SharepointPlus/node.html#Auth ? What else do you need to know here?

**Comment by Aymkdn** [comment]
BTW, `auth` should be used for Node server scripts, and not for Webpack projects.

**Comment by hanadkubat** [comment]
> The homepage https://aymkdn.github.io/SharepointPlus/ describes how to use it with Node/Webpack. Is it not enough? It's what I use for my Vue projects. What else do you need?
> 
> Regarding `auth` there is an example in the documentation https://aymkdn.github.io/SharepointPlus/node.html#Auth ? What else do you need to know here?

First of all thank you for making this great library, but if you could add a snippet of importing and using SP dependency with these front end libraries it would be great, since you are already using it with vue. The already existing explanation is not clear enough for all users.

**Comment by Aymkdn** [comment]
I guess I could share some stuff, but it won't be before several days as I won't have the time before that...

**Comment by Aymkdn** [comment]
Sorry for the delay.

I explain [here](https://github.com/Aymkdn/SharepointPlus/wiki/SharepointPlus-and-Webpack) how my environment is setup... The way I do it might be unconventional... Please, note that I'm working alone (I don't have any dev co-workers), and my environment is a Sharepoint 2013 On-Promise where I'm a Site Collection admin (without Farm permissions).
