### ISSUE TITLE
list "add" method pushes the xml data to the input object after submission 

### ISSUE THREAD

**Issue by YakQin** [Aymkdn/SharepointPlus#126]
hello, 
This is a great lib and I have been using it for years. Thanks a lot. Today I happen to notice below.
I have an object data to be submitted to sharepoint, it is like
`var listData={
a:1,
b:2
}`
after the submission is done successfully, I saw the "raw" (the xml from the callback) was added to my listData

![Capture](https://user-images.githubusercontent.com/17231180/69412363-acbc0b80-0d49-11ea-96d6-b0166b396a35.JPG)

I checked the code, I found 

`items[i].raw = rows[0];`
here "items" is in my case the listData
so the method is manipulating my input data. I am not an expert in JS and I could not figure out. Actually after the data is submitted I dont need the listData at all, just a little curious and want to know why.

Thanks

**Comment by Aymkdn** [comment]
It will return more columns in this `raw`, in case you need to access to some other columns that weren't part of your initial parameters but that are returned by the server anyway.

If you don't want to change your original input, you could do something like:
```javascript
var listData={ a:1, b:2 };
$SP().list("MyList").add(JSON.parse(JSON.stringify(listData)))
```

**Comment by YakQin** [comment]
Thanks a lot. it makes a lot of sense.
