### ISSUE TITLE
Nintex workflows

### ISSUE THREAD

**Issue by raymar** [Aymkdn/SharepointPlus#128]
I will also start with a big thank you for the work you have done. Its amazing and I also use SharepointPlus a lot! Nevertheless I would suggest to add also Nintex workflows manipulation to the library. They are used quite often and it would be a great imporvement. Here is a link to their web service documentation.

https://help.nintex.com/en-US/sdks/sdk2013/#Reference/SOAP/NW_REF_SOAP_NAV.htm%3FTocPath%3DNintex%2520Software%2520Development%2520Kit%7CNintex%2520Workflow%25202013%2520Software%2520Development%2520Kit%7CNintex%2520Workflow%25202013%2520SDK%2520Reference%7CWeb%2520Service%2520Reference%7C_____0

Thank you!

**Comment by Aymkdn** [comment]
Hi.

I don't use Nintex so I couldn't test it.... However, you could try https://aymkdn.github.io/SharepointPlus/core.html#webService to trigger their workflows.

I'll close this issue as I won't implement it. Feel free to comment if you have more questions.
