### ISSUE TITLE
SP6 forms plugin

### ISSUE THREAD

**Issue by Germain-Italic** [Aymkdn/SharepointPlus#131]
Hello, as stated in the changelog:

> sharepointplus used to have a few plugins. One of them was dedicated to deal with forms' fields. However I'm not using them anymore, and I'm not even sure anyone was using them.

Yes sir

> I decided to remove them altogether.

Well that's a bad news :(

**Comment by Germain-Italic** [comment]
@Aymkdn in my memories there was a documentation page for the forms plugin. Where did it go?

**Comment by Aymkdn** [comment]
At the bottom of the homepage you have a link to the old documentation: https://sharepointplus5.netlify.com/docs/

**Comment by Germain-Italic** [comment]
Sorry for missing the link, thank you!
