### ISSUE TITLE
$SP().webService - soapURL not reflected in the soapEnvelope

### ISSUE THREAD

**Issue by raymar** [Aymkdn/SharepointPlus#132]
Hi,

I am trying the $SP().webService to call Nintex web service. Even though I specify the soapURL options. It still keeps the http://schemas.microsoft.com/sharepoint/soap/ in the body.

This is how I call it:

$SP().webService({ // http://sympmarc.github.io/SPServices/core/web-services/Lists/UpdateList.html
  service:"NintexWorkflow/Workflow",
  operation:"GetRunningWorkflowTasksForListItem",
  soapURL:'http://nintex.com/',
  webURL:webURL,
  properties:{
    itemId: 1,
    listName:"ListName",
  }

But this is the SOAP envelope which is going out in fact
```xml
<soap:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
<soap:Body>
<GetRunningWorkflowTasksForListItem xmlns="http://schemas.microsoft.com/sharepoint/soap/">
<itemId>1</itemId>
<listName>ListName</listName>
</GetRunningWorkflowTasksForListItem>
</soap:Body>
</soap:Envelope>
```
instead of xmlns="**http://schemas.microsoft.com/sharepoint/soap/**" there should be xmlns="**http://nintex.com**"

Thanks.

Regards,
Bronislav

**Comment by Aymkdn** [comment]
Thanks for letting me know. I'll investigate as soon as I have the time (not before next week).

**Comment by Aymkdn** [comment]
I've just tested the last version (v6.0.4) and it works as expected:
```javascript
$SP().webService({
  service:"NintexWorkflow/Workflow",
  operation:"GetRunningWorkflowTasksForListItem",
  soapURL:'http://nintex.com/',
  properties:{
    itemId: 1,
    listName:"ListName",
  }
})
```
will send the below request:
```xml
<soap:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
  <soap:Body>
    <GetRunningWorkflowTasksForListItem xmlns="http://nintex.com/">
      <itemId>1</itemId>
      <listName>ListName</listName>
    </GetRunningWorkflowTasksForListItem>
  </soap:Body>
</soap:Envelope>
```

**Comment by raymar** [comment]
You are right...I still had v5.2. In 6.0.4 it works well. But strangely if I send the request via $SP().webService, i get error code 500.
```xml
<?xml version="1.0" encoding="utf-8"?><soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema"><soap:Body><soap:Fault><faultcode>soap:Server</faultcode><faultstring>Server was unable to process request. ---&gt; Cannot find list.
Parameter name: listName</faultstring><detail /></soap:Fault></soap:Body></soap:Envelope>
```

 But if I send the request manually...it passes through.

This is the one generated via $SP().webService:

Request URL: rootURL/_vti_bin/NintexWorkflow/Workflow.asmx
Request Method: POST
Status Code: 500 Internal Server Error
Remote Address: 10.3.56.104:443
Referrer Policy: no-referrer-when-downgrade
Cache-Control: private
Content-Length: 431
Content-Type: text/xml; charset=utf-8
Date: Mon, 02 Mar 2020 15:11:08 GMT
MicrosoftSharePointTeamServices: 15.0.0.5131
SPIisLatency: 0
SPRequestDuration: 37
SPRequestGuid: 9ddf3a9f-b781-301a-15d3-6f682051b1b9
X-Content-Type-Options: nosniff
X-FRAME-OPTIONS: SAMEORIGIN
X-MS-InvokeApp: 1; RequireReadOnly
Accept: */*
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9,cs;q=0.8,de;q=0.7
Connection: keep-alive
Content-Length: 359
Content-Type: text/xml; charset=UTF-8
Host: rootURL
Origin: rootURL
Referer: rootURL/Lists/gcrmStock/MainView.aspx
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-origin
SOAPAction: http://nintex.com/GetRunningWorkflowTasksForListItem
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36
X-Requested-With: XMLHttpRequest
```xml
<soap:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"><soap:Body><GetRunningWorkflowTasksForListItem xmlns="http://nintex.com/"><itemId>85</itemId><listName>GapAnalysis</listName></GetRunningWorkflowTasksForListItem></soap:Body></soap:Envelope>
```

And this is the one generated manually:

Request URL: rootURL/_vti_bin/NintexWorkflow/Workflow.asmx
Request Method: POST
Status Code: 200 OK
Remote Address: 10.3.56.104:443
Referrer Policy: no-referrer-when-downgrade
Cache-Control: private, max-age=0
Content-Encoding: gzip
Content-Length: 684
Content-Type: text/xml; charset=utf-8
Date: Mon, 02 Mar 2020 15:14:53 GMT
MicrosoftSharePointTeamServices: 15.0.0.5131
request-id: d4df3a9f-f774-301a-15d3-6fdef6bede9b
SPIisLatency: 1
SPRequestDuration: 361
SPRequestGuid: d4df3a9f-f774-301a-15d3-6fdef6bede9b
Vary: Accept-Encoding
X-Content-Type-Options: nosniff
X-FRAME-OPTIONS: SAMEORIGIN
X-MS-InvokeApp: 1; RequireReadOnly
X-SharePointHealthScore: 0
Accept: application/xml, text/xml, */*; q=0.01
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9,cs;q=0.8,de;q=0.7
Connection: keep-alive
Content-Length: 403
Content-Type: text/xml; charset="UTF-8"
Host: rootURL
Origin: rootURL
Referer: rootURL/Lists/gcrmStock/MainView.aspx
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-origin
SOAPAction: http://nintex.com/GetRunningWorkflowTasksForListItem
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36
X-Requested-With: XMLHttpRequest
```xml
<soap:Envelope xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance' xmlns:xsd='http://www.w3.org/2001/XMLSchema' xmlns:soap='http://schemas.xmlsoap.org/soap/envelope/'> 		  <soap:Body> 		    <GetRunningWorkflowTasksForListItem xmlns='http://nintex.com'> 		      <itemId>85</itemId> 		      <listName>GapAnalysis</listName> 		    </GetRunningWorkflowTasksForListItem> 		  </soap:Body> 		</soap:Envelope>
```

The only difference I noticed is in accept headers. Do you have an idea where is the problem?

**Comment by Aymkdn** [comment]
The error says: _Cannot find list. Parameter name: listName_

So… Maybe you have a typo somewhere? You didn't paste the XML that is sent, but only the response. I think the problem is in the XML that it sent.

**Comment by raymar** [comment]
I did paste it. Those are the one liners...
A) via SharepointPlus
```xml
<soap:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"><soap:Body><GetRunningWorkflowTasksForListItem xmlns="http://nintex.com/"><itemId>85</itemId><listName>GapAnalysis</listName></GetRunningWorkflowTasksForListItem></soap:Body></soap:Envelope>
```

B) Manually:

```xml
<soap:Envelope xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance' xmlns:xsd='http://www.w3.org/2001/XMLSchema' xmlns:soap='http://schemas.xmlsoap.org/soap/envelope/'> 		  <soap:Body> 		    <GetRunningWorkflowTasksForListItem xmlns='http://nintex.com'> 		      <itemId>85</itemId> 		      <listName>GapAnalysis</listName> 		    </GetRunningWorkflowTasksForListItem> 		  </soap:Body> 		</soap:Envelope>
```

**Comment by Aymkdn** [comment]
Try to remove the last '/' in :
> soapURL:'http://nintex.com/'

Your call will become:
```javascript
$SP().webService({
  service:"NintexWorkflow/Workflow",
  operation:"GetRunningWorkflowTasksForListItem",
  soapURL:'http://nintex.com', // remove the last '/'
  properties:{
    itemId: 1,
    listName:"ListName",
  }
})
```

I had issues in the past with Sharepoint webservices due to an url like that…

**Comment by raymar** [comment]
It says it cannot recognize the SOAPAction. Could be the Accept headers? In case of SharepointPlus it is &ast;/&ast; in case of manually generated request I set the Accept headers to application/xml, text/xml, &ast;/&ast;;
```xml
<?xml version="1.0" encoding="utf-8"?><soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema"><soap:Body><soap:Fault><faultcode>soap:Client</faultcode><faultstring>Server did not recognize the value of HTTP Header SOAPAction: http://nintex.comGetRunningWorkflowTasksForListItem.</faultstring><detail /></soap:Fault></soap:Body></soap:Envelope>
```

**Comment by Aymkdn** [comment]
1. I don't think it's the Accept header. You can try to do a manual request with the same Header defined by SharepointPlus to test.

2. Also test a manual request with adding '/' at the end of the url in the xmlns:
> &lt;GetRunningWorkflowTasksForListItem xmlns='http://nintex.com/'>

3. Finally, try the below:
```javascript
$SP().webService({
  service:"NintexWorkflow/Workflow",
  operation:"GetRunningWorkflowTasksForListItem",
  soapURL:'http://nintex.com/',
  soapAction:false,
  properties:{
    itemId: 1,
    listName:"ListName",
  }
})
```

**Comment by raymar** [comment]
Can you replace double quotes in the request with single quotes? This is the issue...it does not recognize the listName as string since it is inserted as with the same quotes

**Comment by raymar** [comment]
> 1. I don't think it's the Accept header. You can try to do a manual request with the same Header defined by SharepointPlus to test.
> 2. Also test a manual request with adding '/' at the end of the url in the xmlns:
> 
> > <GetRunningWorkflowTasksForListItem xmlns='[http://nintex.com/'>](http://nintex.com/'%3E)
> 
> 1. Finally, try the below:
> 
> ```js
> $SP().webService({
>   service:"NintexWorkflow/Workflow",
>   operation:"GetRunningWorkflowTasksForListItem",
>   soapURL:'http://nintex.com/',
>   soapAction:false,
>   properties:{
>     itemId: 1,
>     listName:"ListName",
>   }
> })
> ```

This works...thx a lot for your help!

**Comment by Aymkdn** [comment]
The last one worked? With adding `SOAPAction:false`?

**Comment by raymar** [comment]
> The last one worked? With adding `SOAPAction:false`?

Yes, this way it worked.

I have noticed that if I inserted the XML generated by $SP().webService() to my manual request it also did not work. And the difference is that in my XML I encapsulated the parameters to single quotes ' and not double quotes ". Could this also play a role? Because this is in fact the only difference...
