### ISSUE TITLE
SharePoint lists JOIN

### ISSUE THREAD

**Issue by milanVG** [Aymkdn/SharepointPlus#134]
Hello, I have been searching for help how to join two or more SharePoint lists in SQL way and I found your SP library. It looks really great but I am not able to make my code working.

I am putting the code inside Script Editor and after the page refresh I cannot see any log in the console.

Please, can you help me?

```
<script type="text/javascript">

$SP().list("desksConfig","http://teamshare.***.lan/de/0052/IX-IT/_layouts/15/start.aspx#/Lists/").get({
    fields:"nitq",
    where:"nitq = 'Sarah'",
    join:{
list:"deskReservations",
fields:"z6gx,t8fe,mlhr",
on:"'deskReservations'.mlhr = 'desksConfig'.cmbf",
    }
  }).then(function(data) {
    for (var i=0; i<data.length; i++) {
console.log(data[i].getAttribute("deskReservations.z6gx")+" | "+data[i].getAttribute("deskReservations.t8fe")+" | "+data[i].getAttribute("deskReservations.mlhr"));
    }
  });

</script>
```

**Comment by Aymkdn** [comment]
Hi,

First, be aware that my JOIN solution is not a true SQL Join solution: I actually query both lists and then I do a join using the code.

That said, your code looks OK, expect for the URL part. It should look like that:
```javascript
// The URL must be the root URL of the website, or not URL at all if the webpage
// that has this code is already located in http://teamshare.***.lan/de/0052/IX-IT/
// if it's the case you can just write: $SP().list("desksConfig")
$SP().list("desksConfig","http://teamshare.***.lan/de/0052/IX-IT/")
.get({
    fields:"nitq",
    where:"nitq = 'Sarah'",
    join:{
       list:"deskReservations",
       fields:"z6gx,t8fe,mlhr",
       on:"'deskReservations'.mlhr = 'desksConfig'.cmbf"
    }
  })
.then(function(data) {
    for (var i=0; i<data.length; i++) {
       console.log(data[i].getAttribute("deskReservations.z6gx")+" | "+data[i].getAttribute("deskReservations.t8fe")+" | "+data[i].getAttribute("deskReservations.mlhr"));
    }
});
```

Also, you can check the Network tab of the web developer toolbar, to see what is the response from the server.

Questions:
1. Which version of SharepointPlus are you using?
2. What type of columns are `mlhr` and `cmbf`?

**Comment by milanVG** [comment]
I am using just the link.
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/sharepointplus/browser/sharepointplus.js"></script>

Column type is Single line of text.

I changed and removed the URL but nothing happens either.

![image](https://user-images.githubusercontent.com/50572932/79428465-7916a200-7fc6-11ea-819c-97588d098e15.png)

**Comment by Aymkdn** [comment]
It seems your code is not executed at all.

You may want to put an `alert` or `console` before using the `$SP()` code, just to validate that this script part is executed!

**Comment by milanVG** [comment]
I put console before $SP and it actually was executed, also code after $SP function is executed.
It seems like it cannot read $SP.

**Comment by Aymkdn** [comment]
Odd… You should at least see a request generated by SharepointPlus… Did you check the "Initiator" column from the Network tab? There is nothing coming from "sharepointplus.js"?

Try a `console.log($SP().getVersion()));` that should display `6.1.0` and it will confirm SharepointPlus is loaded.

And you don't have any error message in the console?!
Which version of Sharepoint do you use?

And if you just copy/paste the code in the console, what happens? No request is done?

**Comment by milanVG** [comment]
SharePointPlus is loaded, I can see the version 6.1.0.

I found this error in the console checking Initiator. 
![image](https://user-images.githubusercontent.com/50572932/79431448-c268f080-7fca-11ea-9b55-e119272a3b59.png)

When I copy/paste the code in the console ->
![image](https://user-images.githubusercontent.com/50572932/79431258-7a49ce00-7fca-11ea-8010-606672c6766d.png)

I use SharePoint 2013.

**Comment by Aymkdn** [comment]
It looks like this release has an issue with IE browser: let me check it now why it doesn't work in IE – but in the meantime try your code in Chrome or Firefox

**Comment by Aymkdn** [comment]
OK, so actually the build is correct; however it will only work with IE11 engine: meaning either you're not using IE11, or your website doesn't have `<meta http-equiv="X-UA-Compatible" content="IE=Edge" />` in the `<head>` to force IE11 to use IE11 engine, and not IE7.

I'll release a new version that will support IE7. Give me a few minutes.

**Comment by milanVG** [comment]
I tried it also in Firefox with the same result.

**Comment by Aymkdn** [comment]
> I tried it also in Firefox with the same result.

No… It does work with a modern browser like Firefox.

**Comment by Aymkdn** [comment]
So… I did some tests using IE11:
  - with Sharepoint 2010, that doesn't have `<meta http-equiv="X-UA-Compatible" content="IE=Edge" />` in the `<head>`, it's IE7 engine that is used, which is too old to be polyfilled with current version of SharepointPlus (I'm going to update the documentation);
  - with Sharepoint 2013, that doesn't have `<meta http-equiv="X-UA-Compatible" content="IE=Edge" />` in the `<head>`, it's IE10 engine that is used, and the current build works with this version

**I assume you're using SP2010, right?** In that case you need to use an older version (v3.14): https://github.com/Aymkdn/SharepointPlus/releases/tag/v3.14

In that case, you'll have to store `nanoajax.min.js` and `sharepointplus-3.14.min.js` on your Sharepoint and call this way:
```html
<script type="text/javascript" src="nanoajax.min.js"></script>
<script type="text/javascript" src="sharepointplus-3.14.min.js"></script>
```

Then the code is a bit different because it's not using Promise, but Callbacks:
```javascript
$SP().list("desksConfig")
.get({
    fields:"nitq",
    where:"nitq = 'Sarah'",
    join:{
       list:"deskReservations",
       fields:"z6gx,t8fe,mlhr",
       on:"'deskReservations'.mlhr = 'desksConfig'.cmbf"
    }
  }, function(data) {
    for (var i=0; i<data.length; i++) {
       console.log(data[i].getAttribute("deskReservations.z6gx")+" | "+data[i].getAttribute("deskReservations.t8fe")+" | "+data[i].getAttribute("deskReservations.mlhr"));
    }
});
```

If you download [all the sources](https://github.com/Aymkdn/SharepointPlus/archive/v3.14.zip), you can find the documentation in the `docs` folder.

**Comment by milanVG** [comment]
I tried your suggestion but without success. Thank you for your time and effort, I will do it in another way.
Good luck.
