### ISSUE TITLE
Build size increases by 1156KB from 6.0.4-6.1.0

### ISSUE THREAD

**Issue by Async0x42** [Aymkdn/SharepointPlus#135]
I'm using vue-cli / webpack to bundle my web application, after updating SharepointPlus from 6.0.4 the build size increases by 1156KB. Reverting to 6.0.4 gives me the small size again.

I'm using sharepointplus-loader and treeshaking, after checking the report it looks likes there's a lot of new dependencies being included like: psl, ajv, sshpk, bluebird, elliptic

Is there a migration step that should be performed when going from 6.0.4 to 6.1.0?

**Comment by Aymkdn** [comment]
Thanks for the heads-up!

I've just found the issue, and I'll now work on a fix…

**Comment by Aymkdn** [comment]
Please, try to install v6.1.1 and let me know if it resolves the issue!

**Comment by Async0x42** [comment]
Wonderful, it's working great now. Thanks!
