### ISSUE TITLE
How i can create folder in /Lists/Listname/Attachments/

### ISSUE THREAD

**Issue by Strannik10** [Aymkdn/SharepointPlus#138]
Hello.
I would like to create folder in Sharepoint (/Lists/Listname/Attachments/)

$SP().list("ListName").createFolder("/Attachments/123").then(function(folder) { alert("Folder created!"); })

i see alert "Folder created!", but in folder not create.
Help me please create folder in /Lists/Listname/Attachments/

Thank you in advance!

**Comment by Aymkdn** [comment]
It doesn't work this way. This feature is to create a folder inside a Document Library.

**Comment by Strannik10** [comment]
Thank you.
May be i can use another SharepointPlus utility to create folder in  /Lists/Listname/Attachments/ ?

**Comment by Aymkdn** [comment]
Nope… And I'm not aware of any API in Sharepoint that permits to manipulate the file system.

But, why do you need to create this kind of thing? If you [attach a file to a list's item](https://aymkdn.github.io/SharepointPlus/lists.html#addAttachment), it will create the Attachments folder and so on…

What are your trying to achieve here?

**Comment by Strannik10** [comment]
Yes.
I try use $SP().list("My List").addAttachment
but i cannot attach several files (only one) , and i cannot overwrite attachemt (if file name same)
I try use _uploadFile() function 
https://aymkdn.github.io/SharepointPlus/files.html#createFile
if folder exist i can successfully upload several files, but i cannot create folder if folder not created.

**Comment by Aymkdn** [comment]
`addAttachment` can only add files one by one. Save thing for `createFile`.

However, you can attach **several files** to one item using the `addAttachment` function. For the overwrite, I never tried, but you could first check if the [attachment filename exist](https://aymkdn.github.io/SharepointPlus/lists.html#getAttachment), and if it's the case you can delete it before uploading a new one.

To delete an attachment:
```javascript
$SP().list(listName)
.webService({
  service:"Lists",
  operation:"DeleteAttachment",
  properties:{
    listName:listName,
    listItemID:itemID,
    url:urlToTheFile
  }
})
```

**Comment by Strannik10** [comment]
Thank you.
How can i attach several files to one item using the addAttachment function?
Can you help me?

**Comment by Aymkdn** [comment]
As simple as calling the function for each file…

```javascript
$SP().list("My List").addAttachment({
  ID:1,
  filename:"file_1.txt",
  attachment:"*ArrayBuffer*"
});

$SP().list("My List").addAttachment({
  ID:1,
  filename:"file_2.txt",
  attachment:"*ArrayBuffer*"
})
```

**Comment by Strannik10** [comment]
Thanks a lot.
I will try it.
