### ISSUE TITLE
How can i create ArrayBuffer from string variable?

### ISSUE THREAD

**Issue by Strannik10** [Aymkdn/SharepointPlus#139]
Hello.
I have string variable, for example 
var string1 = '123'
How can i put string1 in ArrayBuffer and then use AddAttachment?
My core is
$SP().list("My List").addAttachment({
ID:Myid,
filename:"file.txt",
attachment:"123"
});
but it cannot work...

Help me please.
Thank you in advance.

**Comment by Aymkdn** [comment]
https://www.google.com/search?q=How+can+i+create+ArrayBuffer+from+string+variable%3F
