### ISSUE TITLE
Can i use Dot as field name?

### ISSUE THREAD

**Issue by Strannik10** [Aymkdn/SharepointPlus#140]
Hello.
I have several fields, one of them has name . (dot)
I write code: 
$SP().list("Name").update([{ID:Myid, .:MyBlockWorkflow,  Status:MyStatus, Urgency:MyUrgency, Responsible:MyResponsible, Security:MySecurity}]);

but code does not work.
Can i use . (dot) field name in $SP().list("Name").update  ?
Thank you in advance.

**Comment by Aymkdn** [comment]
It's a JSON string. So, yes you can… You just have to use "":
```javascript
$SP().list("Name").update({
  "ID":Myid,
  ".":MyBlockWorkflow,
  "Status":MyStatus,
   "Urgency":MyUrgency,
    "Responsible":MyResponsible,
    "Security":MySecurity
});
```
