### ISSUE TITLE
Can i use multi-people field in UPDATE

### ISSUE THREAD

**Issue by Strannik10** [Aymkdn/SharepointPlus#141]
Hello.
I use people picker field. If field contain only one name, everything work good, but if i type two or more names in people picker field my code does not work. Help me please to find out error in my code.
Thank you in advance.

My code is

function Mysave() { 

var Myid =$("input[title='ID']").val();

var MyKomuSoobshit =$('div#ctl00_ctl26_g_265b926b_907d_40d9_8a85_2ff5beb6b9c7_ctl00_ctl05_ctl04_ctl00_ctl00_ctl05_ctl00_ctl00_UserField_upLevelDiv').text();

var MyKomuSoobshit ='-1;#'+MyKomuSoobshit;

$SP().list("MyList").update([{ID:Myid, Mymembers:MyMemberUsers}]);

 }

**Comment by Aymkdn** [comment]
The format required by Sharepoint is explained in the `add` function : https://aymkdn.github.io/SharepointPlus/lists.html#add

> A multiple selection of People/Users must be provided as "userID1;#email1;#userID2;#email2;#userID3;#email3", with "userID" that could be "-1" if you don't know it, and "email" that could also be an NT Login; if you know the correct userID then nothing else is required (e.g. "158;#;#27655;#" will add the users with ID 158 and 27655)

**Comment by Strannik10** [comment]
Thank you very much.
