### ISSUE TITLE
Long queries 404 error

### ISSUE THREAD

**Issue by Marouanebouzoubaa** [Aymkdn/SharepointPlus#142]
Hello Dear,

Now that SP allows me doing queries easily (Thx to your excellent project), I started doing complex ones with long where clause. But at certain point, the server returns 404.

I found out that when the whole POST url query exeeds 1545 characters, the 404 error starts happening.

Is there a config in SP, SharePoint web.config, or IIS to allow longer queries.

I would appreciate your help on this subject.

Best regards,

Marouane

**Comment by Aymkdn** [comment]
Hi,

I have no idea… You better ask on https://sharepoint.stackexchange.com/ where you may find an answer!

What do you have in your where clause ? Maybe SharepointPlus can help… For exampe, if you use an array, it will do a request for each element of the WHERE array.
