### ISSUE TITLE
addAttachment Issue

### ISSUE THREAD

**Issue by seekhead** [Aymkdn/SharepointPlus#143]
Hello, great framework but im having some issues mainly because i dont know how to interact with some of the functions
so im getting this code

> Uncaught (in promise) {statusCode: 500, responseText: "<?xml version="1.0" encoding="utf-8"?><soap:Envelo…/detail></soap:Fault></soap:Body></soap:Envelope>", request: XMLHttpRequest}

any suggestion?

**Comment by Aymkdn** [comment]
Can you also provide your code??

**Comment by seekhead** [comment]
sure
<input type='file'  onchange='openFile(event)'>
<script>
var openFile = function(event) {
    var input = event.target;
	let file = input.files[0];
    var reader = new FileReader();
    
    
    reader.onload = function(){
      var dataURL = reader.result;
    };
    reader.readAsDataURL(input.files[0]);
    
     reader.onload = function() { 
     	    var data = this.result,                       
            n=data.indexOf(";base64,") + 8;
            data= data.substring(n);

    $SP().list("MyList").addAttachment({
    ID:5,
    filename:file.name,
    attachment:data,
  }).then(function(fileURL) {
    console.log(fileURL);
  });
   
  };
 }
</script>

**Comment by Aymkdn** [comment]
Here is an example (that I cannot test at this time):
```html
<input id="attach_file" type="file" onchange="addAttachment(event)">
```
```javascript
// use fileReader
function addAttachment(event) {
   let files = event.target.files;
  let fileReader = new FileReader();
  fileReader.onloadend = function(e) {
    let content = e.target.result;
    $SP().list("MyList").addAttachment({
      ID:itemID,
      filename:fileName,
      attachment:content
    })
    .then(function(url) {
      console.log({url})
    })
    .catch(function(err) {
      console.log(err)
    }) 
  }
  fileReader.onerror = function(e) {
    alert('Unexpected error: '+e.target.error);
  }
  fileReader.readAsArrayBuffer(files[0]);
}
```

I think your problem is that you don't pass an arraybuffer to the function.

**Comment by seekhead** [comment]
you are correct. i dont know what an arraybuffer is or where does it comes, neither how to parse it
cant figure it out mb

**Comment by Aymkdn** [comment]
Everything is self-explanatory in my example. It's easy to get. You can also Google it.
