### ISSUE TITLE
How to update PeoplePicker field

### ISSUE THREAD

**Issue by Strannik10** [Aymkdn/SharepointPlus#145]
Hello!
I install Sharepoint 2013 Foundation. I use SharepointPlus Update function ( $SP().list("TestList").update )
First case:
If PeoplePicker field looks like (Sharepoint 2010)
![image](https://user-images.githubusercontent.com/66675789/87859706-ddd3f680-c93f-11ea-9316-ae0f07d088c7.png)
Update function works successfully
$SP().list("TestList").update([{ID:Myid, Responsible:MyKomuSoobshit}]);

Second case:
But if PeoplePicker field looks like (Sharepoint 2013)
![image](https://user-images.githubusercontent.com/66675789/87859683-a6654a00-c93f-11ea-800a-86d9f6ee0c84.png)

Update function does not work.

Can i use SharepointPlus Update function for PeoplePicker field in second case?

Thank you in advance!

**Comment by Aymkdn** [comment]
The important is the format you pass. Check the documentation : https://aymkdn.github.io/SharepointPlus/lists.html#add

> A person must be provided as "-1;#email" (e.g. "-1;#foo@bar.com") OR NT login with double \ (eg "-1;#europe\\foo_bar") OR the user ID as a number

**Comment by Strannik10** [comment]
Thank you. It works! (if i set variable manual, for example 
var UserName  ='-1;#testafa@arlafoods.ru'
$SP().list("TestSP1").update([{ID:1, User:UserName}]);
)
But i cannot get value from field PeoplePicker (second case)
Can i get value from PeoplePicker use SharepointPlus ?

**Comment by Aymkdn** [comment]
I don't know how to get a value from this people picker. Try to get the value and see how this value looks like...

**Comment by Strannik10** [comment]
Thanks a lot! Close my question please.
