### ISSUE TITLE
Peoplepicker in angluar using proxy

### ISSUE THREAD

**Issue by SemonnomeS** [Aymkdn/SharepointPlus#146]
I am trying to make people picker in angluar app with method addressbook. Currently i am using proxy for local development on sharepoint. I made a setup for proxy, and every method works except addressbook.

$SP().addressbook("john", {limit:25}).then(function(people) {
    for (var i=0; i < people.length; i++) {
      for (var j=0; j < people[i].length; j++) console.log(people[i][j]+" = "+people[i][people[i][j]]);
    }
  });

**Comment by Aymkdn** [comment]
This is not a SharepointPlus issue as it will just call `/_vti_bin/People.asmx` like all the other calls are done… If the other requests work, then this one should work too.

I'd recommend to check your Network tab of the developer console to see what is the error. Maybe your People service doesn't work properly or doesn't accept connection from a proxy.

**Comment by SemonnomeS** [comment]
Actually methods that allow url (passing as paramter) like GET method works with proxy, some of other methods dont allow that, for example ADD method does not allow passing url, and than function doesnt work when using proxy.

  $SP().list("ListName","http://proxyUrl").get({
  }).then(function(data) {
  });

**Comment by SemonnomeS** [comment]
Is it possible to pass the url (of proxy) to the method addressbook, as the other methods allow that ?

**Comment by koltyakov** [comment]
@SemonnomeS, are you mentioning sp-rest-proxy?

Just checked and the method works for me in the local workbench.

![image](https://user-images.githubusercontent.com/7816483/88700471-6b1e0480-d111-11ea-9510-ba31683aa629.png)

When initializing the page make sure that you loading the context. Proxy has [a helper for this](https://github.com/koltyakov/sp-rest-proxy#load-page-context-helper).

**Comment by SemonnomeS** [comment]
Thank you for your help, and fast response.

**Comment by Aymkdn** [comment]
> Is it possible to pass the url (of proxy) to the method addressbook, as the other methods allow that ?

You can use the [`url` parameter](https://aymkdn.github.io/SharepointPlus/people.html#addressbook):
```js
$SP().addressbook("john", {limit:25, url:"https://whatever/"})
```

It will then append `/_vti_bin/People.asmx` to the URL you provided.

Because you liked @koltyakov reply, then I'll guess his answer fixed your issue 👍

**Comment by SemonnomeS** [comment]
Actually passing the proxy url solved my probem.
I was trying passing url parameter like on the other methods, and it didnt work:
`$SP()
      .addressbook('alex', environment.baseUrl)
      .then(function (people) {
        for (var i = 0; i < people.length; i++) {
          for (var j = 0; j < people[i].length; j++)
            console.log(people[i][j] + ' = ' + people[i][people[i][j]]);
        }
      });`
Now your answer solved problem, it was just minor bug. Thank you so much.
