### ISSUE TITLE
Authentication issue with Sharepoint 365

### ISSUE THREAD

**Issue by anabwan** [Aymkdn/SharepointPlus#148]
Hello,
I'm trying to use Share Point 365 as the main url by usning sharepointplus (version latest: 6.1.2)
I got a problem, see below:

error: 
```
{ error: Error: <S:Fault>
  <S:Code>
    <S:Value>S:Sender</S:Value>
    <S:Subcode>
      <S:Value>wst:FailedAuthentication</S:Value>
    </S:Subcode>
  </S:Code>
  <S:Reason>
    <S:Text xml:lang="en-US">Authentication Failure</S:Text>
  </S:Reason>
  <S:Detail>
    <psf:error xmlns:psf="http://schemas.microsoft.com/Passport/SoapServices/SOAPFault">
      <psf:value>0x80048823</psf:value>
      <psf:internalerror>
        <psf:code>0x80048823</psf:code>
        <psf:text>AADSTS53003: Access has been blocked by Conditional Access policies. The access policy does not allow token issuance.</psf:text>
      </psf:internalerror>
    </psf:error>
  </S:Detail>
</S:Fault>
    at OnlineUserCredentials.postToken (C:\Github\ProjectX\node_modules\sharepointplus\node_modules\node-sp-auth\lib\src\auth\resolvers\OnlineUserCredentials.js:156:19)
    at getSecurityToken.then.xmlResponse (C:\Github\ProjectX\node_modules\sharepointplus\node_modules\node-sp-auth\lib\src\auth\resolvers\OnlineUserCredentials.js:48:25)
    at tryCatcher (C:\Github\ProjectX\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Github\ProjectX\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (C:\Github\ProjectX\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (C:\Github\ProjectX\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (C:\Github\ProjectX\node_modules\bluebird\js\release\promise.js:729:18)
    at _drainQueueStep (C:\Github\ProjectX\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (C:\Github\ProjectX\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (C:\Github\ProjectX\node_modules\bluebird\js\release\async.js:102:5)
    at Immediate.Async.drainQueues (C:\Github\ProjectX\node_modules\bluebird\js\release\async.js:15:14)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5),
  statusCode: undefined,
  response: undefined,
  responseText: '' }
```

this is the code 
```
      let data = await sp.list(WORKING_LIBRARY, SITE_URL).get(
        {
          fields: "FileRef",
          folderOptions:{
            show: method,
            path: workingDirectory
        }});
```

**Comment by Aymkdn** [comment]
It looks like an authentication issue. Are you using it with Node? Which method do you use with [`$SP().auth()`](https://aymkdn.github.io/SharepointPlus/node.html#auth)?

**Comment by Aymkdn** [comment]
Yeah actually the error is there:
> Access has been blocked by Conditional Access policies. The access policy does not allow token issuance.

So you cannot access to your Sharepoint 365 using Token because it's not allowed by your IT policy.

SharepointPlus is not dealing with the auth part, as you can see here:
> at OnlineUserCredentials.postToken (C:\Github\ProjectX\node_modules\sharepointplus\node_modules\node-sp-auth\lib\src\auth\resolvers\OnlineUserCredentials.js:156:19)

The authentication methods are based on https://github.com/s-KaiNet/node-sp-auth

**Comment by anabwan** [comment]
thank you for the fast reply..
yes I'm using the auth like this:


```
const $SP = require('sharepointplus/dist');

const CREDENTIALS = {
    username: process.env.PLC_AUTH_USER,
    password: process.env.PLC_AUTH_PASS,
    domain: process.env.PLC_AUTH_DOMAIN
  };

const sp =  $SP().auth(CREDENTIALS);
```
I don't any error on this part of code.. only when I use the sp.list()
btw, I've used the old sharepoint url with older version of sharepointpluse (ver. 5.1.0) and they have worked perfectly..
after upgrading sharepointpluse 6.1.2 the old sharepoint worked.. just after I changed the url to sp365 I got these errors..
do I need to upgrade any thing else except the sharrpointplus ?

**Comment by Aymkdn** [comment]
`sp.list()` will do a call to the server using the auth method provided, when `$SP().auth(CREDENTIALS)` will just store the credentials to being used later. So it's normal to only get an error on `sp.list()`.

> I've used the old sharepoint url with older version of sharepointpluse (ver. 5.1.0) and they have worked perfectly..

When you say "old Sharepoint URL", you mean a Sharepoint OnPremise? Because the authentication between an OnPrem and Sharepoint 365 is different. If yes, then it's normal that it's not working with Sharepoint 365.

You'll have to try the different authentication options described on https://github.com/s-KaiNet/node-sp-auth#getauthurl-credentialoptions like the [Addin only permissions](https://github.com/s-KaiNet/node-sp-auth/wiki/SharePoint%20Online%20addin%20only%20authentication) or the [SAML based with user credentials](https://github.com/s-KaiNet/node-sp-auth/wiki/SharePoint%20Online%20user%20credentials%20authentication), or maybe another one…

**Comment by anabwan** [comment]
old SharePoint it means SharePoint 2010

**Comment by Aymkdn** [comment]
Yes. The authentication method changed between the old version of Sharepoint (usually on premise) versus Sharepoint 365. You have to look at the link I sent to find the correct authentication method for your organization.
