### ISSUE TITLE
How can i get last item ID ?

### ISSUE THREAD

**Issue by Strannik10** [Aymkdn/SharepointPlus#149]
Hello!
I have sharepoint list. This list include few hundred items.
I would like to get last item ID.
Can i do it with SharepointPlus?
Thank you in advance!

**Comment by Aymkdn** [comment]
Something like:
```js
$SP().list("list name").get({
  rowlimit:1,
  orderby:"ID DESC" 
})
```

**Comment by Strannik10** [comment]
Sorry, i try , but my code does not work.

var lastID = $SP().list("TestSP1").get({
    rowlimit:1,
    orderby:"ID DESC" 
    })
alert (lastID)

but it does not work. Where i make mistake?

**Comment by Aymkdn** [comment]
Please, read the documentation... There are plenty of examples....

```js
$SP().list("TestSP1").get({
  rowlimit:1,
  orderby:"ID DESC", 
  json:true
})
.then(function(data) {
  alert(data[0].ID)
})
```
