### ISSUE TITLE
What is the minimum version of node.js needed for SharepointPlus ?

### ISSUE THREAD

**Issue by anabwan** [Aymkdn/SharepointPlus#153]
What is the minimum version of node.js needed for SharepointPlus ?

**Comment by Aymkdn** [comment]
I'm not sure… At least I think it works with v9… 

Why?

**Comment by anabwan** [comment]
because we are working with older version v7
I just need to be sure before upgrading the nodejs version

**Comment by Aymkdn** [comment]
So you're saying that you currently use Node v7 with SharepointPlus, and it works?

If yes, then no issue with upgrading Node. I don't see any reason why SP won't work with a newer version…

**Comment by anabwan** [comment]
No.. what is meant is that currently I'm using "sharepointplus": "^5.1.0" for sharepoint 2010 URL with nodejs..
and now I want to upgrade my sharepoint to 365.. and in order to do that I need to upgrade sharepointplus..
in bottom line, I need to work with sharepoint365 with latest sharepointplus... my question is do I need to upgrade nodejs ?

**Comment by anabwan** [comment]
> I think you can use SP 5.1.0 with SP365. It was not officially supported, but it should work the same.

I tried but it never worked for me, the authentication method is different between 2010 to 365 (365 is using client id and secret id)



> But again, I don't understand the problem with Node. Use the version you want. If you want to upgrade Node, feel free to do it…

the problem with Node, is that the npm packages (dependences) that sharepointplus is using not supported for old version of Node...

**Comment by Aymkdn** [comment]
> I tried but it never worked for me, the authentication method is different between 2010 to 365 (365 is using client id and secret id)

The authentication is not managed by SharepointPlus but passed to [node-sp-auth](https://github.com/s-KaiNet/node-sp-auth/) that will deal with this process.

> the problem with Node, is that the npm packages (dependences) that sharepointplus is using not supported for old version of Node...

npm packages not supported by Node?! It must be a super old version of Node then…
