### ISSUE TITLE
Left join on multiple tables

### ISSUE THREAD

**Issue by agobeljic1** [Aymkdn/SharepointPlus#155]
I have a problem on joining multiple lists with left join with SharepointPlus.
If I have for example three tables Table1 (with columns ID, Table2_ID, Name), Table2(with columns ID, Table3_ID, Surname), and Table3(with columns ID, Date),
I need to join these tables like table1 leftjoin on table2 leftjoin on table3 but I don't see left or right join in sharepoint plus documentation, only join and outerjoin are mentioned

**Comment by Aymkdn** [comment]
A `join` simulates an `INNER JOIN`, and an `outerjoin` simulates a `LEFT JOIN`. Everything is done by the code, and not on the server side. Basically I'm getting the data from the tables and then I merge them.

The simplest way to link tables is the _one to many relationship_, like the below: 
- **Table1** with ID and Name
- **Table2** with Table1_ID and Surname – so Table1 can have 0 or several children in Table2
- **Table3** with Table2_ID and Date – so Table2 can have 0 or several children in Table3

In that case, the below would work:
```js
$SP().list("Table1").get({
  fields:["ID", "Name"],
  outerjoin:{
    list:"Table2",
    fields:["ID", "Surname"],
    onLookup:"Table1_ID",
    outerjoin:{
       list:"Table3",
       fields:["ID", "Date"],
       onLookup:"Table2_ID"
    }
  }
})
```

But the way you organized your data is different and more tricky.

You could try the below:
```js
$SP().list("Table1").get({
  fields:["ID", "Table2_ID", "Name"],
  outerjoin:{
    list:"Table2",
    fields:["ID", "Table3_ID", "Surname"],
    on:"'Table2'.ID = 'Table1'.Table1_ID",
    outerjoin:{
       list:"Table3",
       fields:["ID", "Date"],
       on:"'Table3'.ID = 'Table2'.Table3_ID",
    }
  }
})
```

I'm not sure of the result.

**Comment by agobeljic1** [comment]
Thank you, problem resolved

**Comment by Aymkdn** [comment]
Can you share what you did, please?

**Comment by agobeljic1** [comment]
I did this and it worked just fine

$SP()
        .list('Table1')
        .get({
          json: true,
          outerjoin: {
            list: 'Table2',
            on:
              "'Table1'.Table2_ID = 'Table2'.ID",
            outerjoin: {
              list: 'Table3',
              on:
                "'Table2'.Table3_ID = 'Table3'.ID",
            },
          },
        })

**Comment by Aymkdn** [comment]
I'd glad that what I said worked!
