### ISSUE TITLE
cannot compile with nestjs / typescript

### ISSUE THREAD

**Issue by jmls** [Aymkdn/SharepointPlus#156]
I'm trying to integrate shaarepoint plus with my existing nestjs app 

however, when I start, I get the error

```
/workspaces/my_project/node_modules/sharepointplus/es5/index.js:1
import $SP from './main.js';
^^^^^^

SyntaxError: Cannot use import statement outside a module
```

using `import $SP from 'sharepointplus';`

**Comment by Aymkdn** [comment]
Do you support `import` in your project? Otherwise use `require`:
```js
const $SP = require("sharepointplus/dist");
```
