### ISSUE TITLE
Joining tables

### ISSUE THREAD

**Issue by SemonnomeS** [Aymkdn/SharepointPlus#157]
What i have to make is:  FROM MainTable
LEFT OUTER JOIN SecondTable ON MainTable.SecondTableID = SecondTable.ID
LEFT OUTER JOIN ThirdTable ON MainTable.ThirdTableID = ThirdTable.ID
LEFT OUTER JOIN FourthTable ON ThirdTable.FourthTableID = FourthTable.ID

In documentation i saw it is possible to do nesting of joins and on join of each table i can join another one which is connected to previous. But in this situation i have to connect Second and Third table to the Main table. 

 **Is it possible to make two outer joins from Main table, like bellow ?** 

```js
$SP()
      .list('MainTable', this.baseUrl)
      .get({
        json: true,
        orderby: 'ID ASC',
        outerjoin: {
          list: 'SecondTable',
          on: "'MainTable'.SecondTable = 'SecondTable'.ID",
        }, 
        outerjoin: {
            list: 'ThirdTable',
            on:
              "'MainTable'.ThirtTableID = 'ThirdTable'.ID",

            outerjoin: {
              list: 'FourthTable',
              on:
                "'ThirdTable'.FourthTableID = 'FouthTable'.ID",
            },
          },
      })
      .then((data) => {
        console.log(data);
      }); 
```

**I tried this solution bellow but  the result is only the informations from first two tables.**

```js $SP()
       .list('MainTable', this.baseUrl)
      .get({
        json: true,
        orderby: 'ID ASC',
        outerjoin: {
          list: 'SecondTable',
          on: "'MainTable'.SecondTable = 'SecondTable'.ID",

          outerjoin: {
            list: 'ThirdTable',
            on:
              "'MainTable'.ThirtTableID = 'ThirdTable'.ID",

            outerjoin: {
              list: 'FourthTable',
              on:
                "'ThirdTable'.FourthTableID = 'FouthTable'.ID",
            },
          },
        },
      })
      .then((data) => {
        console.log(data);
      });
```

**Comment by Aymkdn** [comment]
You cannot do it… But maybe with the option `merge` we can have the expected result?

Try something like the below:
```js
$SP().list('MainTable').get({
  json: true,
  orderby: 'ID ASC',
  outerjoin: {
    list: 'SecondTable',
    onLookup: "SecondTableID",
    merge:[
      {
        list:'MainTable',
        json: true,
        orderby: 'ID ASC',
        outerjoin: {
            list: 'ThirdTable',
            onLookup:"ThirtTableID",
            outerjoin: {
              list: 'FourthTable',
              onLookup:"FourthTableID"
            }
        }
      }
    ]
})
.then((data) => {
  console.log(data);
}); 
```

NOTE:
- no need to provide the URL if you execute your script in the same website as your list is stored
- you can use `onLookup` instead of `on` when the field will be tied to the `ID` column of the parent
- you may want to pass some `fields` for each table

**Comment by SemonnomeS** [comment]
I tried this solution, it nearly works but i dont get any data fields from second table.. 

`$SP().list('MainTable').get({
  json: true,
  orderby: 'ID ASC',
  outerjoin: {
    list: 'SecondTable',
    on: "'MainTable'.SecondTableID = 'SecondTable'.ID",
    merge:[
      {
        list:'MainTable',
        json: true,
        orderby: 'ID ASC',
        outerjoin: {
            list: 'ThirdTable',
             on:
              "'MainTable'.ThirdTableID = 'Third'.ID",
            outerjoin: {
              list: 'FourthTable',
              on:
                "'ThirdTable'.FourthTableID = 'FourthTable'.ID",
            }
        }
      }
    ]
},
})
.then((data) => {
 console.log(data)
}); `

When i try only outer join to the second table i get the data.

**Comment by Aymkdn** [comment]
Oh, I think the `merge` was not at the right place:
```js
$SP().list('MainTable').get({
  json: true,
  orderby: 'ID ASC',
  outerjoin: {
    list: 'SecondTable',
    onLookup: "SecondTableID",
  },
  merge:[
      {
        list:'MainTable',
        json: true,
        orderby: 'ID ASC',
        outerjoin: {
            list: 'ThirdTable',
            onLookup:"ThirtTableID",
            outerjoin: {
              list: 'FourthTable',
              onLookup:"FourthTableID"
            }
        }
      }
    ]
})
.then((data) => {
  console.log(data);
}); 
```

**Comment by SemonnomeS** [comment]
By this solution i only got informations from the MainTable and from SecondTable.

**Comment by Aymkdn** [comment]
Then, do it with 2 requests:
```js
Promise.all([
  $SP().list('MainTable').get({
    json: true,
    orderby: 'ID ASC',
    outerjoin: {
      list: 'SecondTable',
      onLookup: "SecondTableID",
    }
  }),
  $SP().list('MainTable').get({
      json: true,
      orderby: 'ID ASC',
      outerjoin: {
        list: 'ThirdTable',
        onLookup:"ThirtTableID",
        outerjoin: {
          list: 'FourthTable',
          onLookup:"FourthTableID"
        }
     }
   }
])
.then(res => {
  // res[0] contains First and Second tables
  // res[1] contains First, Third and Fourth
  // and you can concat both list in one array if needed:
  // let data = res[0].concat(res[1])
}); 
̀```

**Comment by SemonnomeS** [comment]
Thank you, i will use this solution.
