### ISSUE TITLE
Got UnhandledPromiseRejectionWarning - Can't pull data

### ISSUE THREAD

**Issue by anabwan** [Aymkdn/SharepointPlus#159]
Hi @Aymkdn,

I'm trying to use latest sharepointplus of pulling data from my sharepoint online
I'm using the following code for example:

```
const $SP = require('sharepointplus/dist');
const sprequest = require('sp-request');

const SITE_URL = "https://XX.sharepoint.com/sites/XXX/";
const WORKING_LIBRARY = "Shared%20Documents";

const CREDENTIALS = {
  clientId: "<BLA>",
  clientSecret: "<BLABLA>",
  realm: "<BLABLABLA>"
};

const sp = $SP().auth(CREDENTIALS);
let spr = sprequest.create(CREDENTIALS)

async function foo() {
  let data = await sp.list(WORKING_LIBRARY, SITE_URL).get({
    fields: "FileLeafRef"
  }).then(function (data) {
    for (var i = 0; i <= data.length; i++)
      console.log("FileName:" + data[i].getAttribute("FileLeafRef"));
  });
  console.log("data ", JSON.stringify(data));
}
foo();
```
here is what I got on the console:

```
> (node:29684) UnhandledPromiseRejectionWarning: #<Object>
> (node:29684) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 5)
> (node:29684) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Please note that I've teste my code using **node-sp-auth** directly, accessing the sharepoint API and it works well, it means I don't have problem with accessing my sharepoint..

Thanks

**Comment by Aymkdn** [comment]
Could you add a `catch()` block to display the error?

```js
async function foo() {
  try {
    let data = await sp.list(WORKING_LIBRARY, SITE_URL).get({
      fields: "FileLeafRef"
    });
    for (let i = 0; i <= data.length; i++) {
      console.log("FileName:" + data[i].getAttribute("FileLeafRef"));
    }
  } catch (err) {
    console.log(err)
  }
}

**Comment by anabwan** [comment]
I got big error, in bottom line it's 401 UNAUTHORIZED error

{ error:
   { StatusCodeError: 401 - "401 UNAUTHORIZED"
       at new StatusCodeError (C:\Github\XXXX\node_modules\request-promise-core\lib\errors.js:32:15)
       at Request.plumbing.callback (C:\Github\XXXX\node_modules\request-promise-core\lib\plumbing.js:104:33)
       at Request.RP$callback [as _callback] (C:\Github\XXXX\node_modules\request-promise-core\lib\plumbing.js:46:31)
       at Request.self.callback (C:\Github\XXXX\node_modules\request\request.js:185:22)
       at Request.emit (events.js:198:13)
       at Request.EventEmitter.emit (domain.js:448:20)
       at Request.<anonymous> (C:\Github\XXXX\node_modules\request\request.js:1154:10)
       at Request.emit (events.js:198:13)
       at Request.EventEmitter.emit (domain.js:448:20)
       at IncomingMessage.<anonymous> (C:\Github\XXXX\node_modules\request\request.js:1076:12)
       at Object.onceWrapper (events.js:286:20)
       at IncomingMessage.emit (events.js:203:15)
       at IncomingMessage.EventEmitter.emit (domain.js:448:20)
       at endReadableNT (_stream_readable.js:1145:12)
       at process._tickCallback (internal/process/next_tick.js:63:19)
     name: 'StatusCodeError',
     statusCode: 401,
     message: '401 - "401 UNAUTHORIZED"',
     error: '401 UNAUTHORIZED',
options:
      { json: false,
        method: 'POST',
        strictSSL: false,
        headers: [Object],
        jar: true,
        resolveWithFullResponse: true,
        body:
         '<soap:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"><soap:Body><GetListItems xmlns="http://schemas.microsoft.com/sharepoint/soap/"><listName>Shared%20Documents/</listName><viewName></viewName><query><Query></Query></query><viewFields><ViewFields Properties=\'True\'><FieldRef Name="FileLeafRef" /></ViewFields></viewFields><rowLimit>0</rowLimit><queryOptions><QueryOptions><DateInUtc>False</DateInUtc><Paging ListItemCollectionPositionNext=""></Paging><IncludeAttachmentUrls>True</IncludeAttachmentUrls><IncludeMandatoryColumns>False</IncludeMandatoryColumns><ExpandUserField>False</ExpandUserField><ViewAttributes Scope="Recursive"></ViewAttributes></QueryOptions></queryOptions></GetListItems></soap:Body></soap:Envelope>',
        url:
         'https://XX.sharepoint.com/sites/XXXX/_vti_bin/Lists.asmx',
        simple: true,
        agent: [Agent],
        callback: [Function: RP$callback],
        transform: undefined,
        transform2xxOnly: false },
     response:
      IncomingMessage {
        _readableState: [ReadableState],
        readable: false,
        domain: null,
        _events: [Object],
        _eventsCount: 4,
        _maxListeners: undefined,
        socket: [TLSSocket],
        connection: [TLSSocket],
        httpVersionMajor: 1,
        httpVersionMinor: 1,
        httpVersion: '1.1',
        complete: true,
        headers: [Object],
        rawHeaders: [Array],
        trailers: {},
        rawTrailers: [],
        aborted: false,
        upgrade: false,
        url: '',
        method: null,
        statusCode: 401,
        statusMessage: 'Unauthorized',
        client: [TLSSocket],
        _consuming: false,
        _dumped: false,
        req: [ClientRequest],
        request: [Request],
        toJSON: [Function: responseToJSON],
        caseless: [Caseless],
        body: '401 UNAUTHORIZED' } },
  statusCode: 401,
  response:
   IncomingMessage {
     _readableState:
      ReadableState {
        objectMode: false,
        highWaterMark: 16384,
        buffer: BufferList { head: null, tail: null, length: 0 },
        length: 0,
        pipes: null,
        pipesCount: 0,
        flowing: true,
        ended: true,
        endEmitted: true,
        reading: false,
        sync: true,
        needReadable: false,
        emittedReadable: false,
        readableListening: false,
        resumeScheduled: false,
        paused: false,
        emitClose: true,
        autoDestroy: false,
        destroyed: false,
        defaultEncoding: 'utf8',
        awaitDrain: 0,
        readingMore: true,
        decoder: null,
        encoding: null },
     readable: false,
     domain: null,
     _events:
      [Object: null prototype] {
        end: [Array],
        close: [Array],
        data: [Function],
        error: [Function] },
     _eventsCount: 4,
     _maxListeners: undefined,
     socket:
      TLSSocket {
        _tlsOptions: [Object],
        _secureEstablished: true,
        _securePending: false,
        _newSessionPending: false,
        _controlReleased: true,
        _SNICallback: null,
        servername: 'XX.sharepoint.com',
        alpnProtocol: false,
        authorized: true,
        authorizationError: null,
        encrypted: true,
        _events: [Object],
        _eventsCount: 8,
        connecting: false,
        _hadError: false,
        _handle: [TLSWrap],
        _parent: null,
        _host: 'XX.sharepoint.com',
        _readableState: [ReadableState],
        readable: true,
        domain: null,
        _maxListeners: undefined,
        _writableState: [WritableState],
        writable: true,
        allowHalfOpen: false,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: undefined,
        _server: null,
        ssl: [TLSWrap],
        _requestCert: true,
        _rejectUnauthorized: false,
        parser: null,
        _httpMessage: null,
        [Symbol(res)]: [TLSWrap],
        [Symbol(asyncId)]: -1,
        [Symbol(lastWriteQueueSize)]: 0,
        [Symbol(timeout)]: null,
        [Symbol(kBytesRead)]: 0,
        [Symbol(kBytesWritten)]: 0,
        [Symbol(connect-options)]: [Object] },
     connection:
      TLSSocket {
        _tlsOptions: [Object],
        _secureEstablished: true,
        _securePending: false,
        _newSessionPending: false,
        _controlReleased: true,
        _SNICallback: null,
        servername: 'XX.sharepoint.com',
        alpnProtocol: false,
        authorized: true,
        authorizationError: null,
        encrypted: true,
        _events: [Object],
        _eventsCount: 8,
        connecting: false,
        _hadError: false,
        _handle: [TLSWrap],
        _parent: null,
        _host: 'XX.sharepoint.com',
        _readableState: [ReadableState],
        readable: true,
        domain: null,
        _maxListeners: undefined,
        _writableState: [WritableState],
        writable: true,
        allowHalfOpen: false,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: undefined,
        _server: null,
        ssl: [TLSWrap],
        _requestCert: true,
        _rejectUnauthorized: false,
        parser: null,
        _httpMessage: null,
        [Symbol(res)]: [TLSWrap],
        [Symbol(asyncId)]: -1,
        [Symbol(lastWriteQueueSize)]: 0,
        [Symbol(timeout)]: null,
        [Symbol(kBytesRead)]: 0,
        [Symbol(kBytesWritten)]: 0,
        [Symbol(connect-options)]: [Object] },
     httpVersionMajor: 1,
     httpVersionMinor: 1,
     httpVersion: '1.1',
     complete: true,
     headers:
      { 'cache-control': 'private, max-age=0',
        'content-length': '16',
        'content-type': 'text/plain; charset=utf-8',
        location:
         '/_forms/default.aspx?ReturnUrl=%2fsites%2fXXXX%2f_vti_bin%2fLists.asmx',
        p3p:
         'CP="ALL IND DSP COR ADM CONo CUR CUSo IVAo IVDo PSA PSD TAI TELo OUR SAMo CNT COM INT NAV ONL PHY PRE PUR UNI"',
        'www-authenticate':
         'Bearer realm="XXXXX",client_id="00000003-0000-0ff1-ce00-000000000000",trusted_issuers="00000001-0000-0000-c000-000000000000@*,XXXXXXXX@*,https://sts.windows.net/*/,00000003-0000-0ff1-ce00-000000000000@SSSSSSSSSSS",authorization_uri="https://login.windows.net/common/oauth2/authorize"',
        'x-sharepointhealthscore': '2',
        sprequestguid: 'bf469e9f-80a5-0000-72cf-7c587d394051',
        'request-id': 'bf469e9f-80a5-0000-72cf-7c587d394051',
        'ms-cv': 'n55Gv6WAAAByz3xYfTlAUQ.0',
        'strict-transport-security': 'max-age=31536000',
        'x-aspnet-version': '4.0.30319',
        sprequestduration: '24',
        spiislatency: '0',
        'x-ms-suspended-features': 'features=""',
        'x-powered-by': 'ASP.NET',
        microsoftsharepointteamservices: '16.0.0.20802',
        'x-content-type-options': 'nosniff',
        'x-ms-invokeapp': '1; RequireReadOnly',
        'x-msedge-ref':
         'Ref A: 26D0029A9EDDXXXXXD8CC148 Ref B: TLV30EDGE0121 Ref C: 2021-01-05T11:12:01Z',
        date: 'Tue, 05 Jan 2021 11:12:01 GMT' },
     rawHeaders:
      [ 'Cache-Control',
        'private, max-age=0',
        'Content-Length',
        '16',
        'Content-Type',
        'text/plain; charset=utf-8',
        'Location',
        '/_forms/default.aspx?ReturnUrl=%2fsites%2fXXXX%2f_vti_bin%2fLists.asmx',
        'P3P',
        'CP="ALL IND DSP COR ADM CONo CUR CUSo IVAo IVDo PSA PSD TAI TELo OUR SAMo CNT COM INT NAV ONL PHY PRE PUR UNI"',
        'WWW-Authenticate',
        'Bearer realm="XXXXXXXXX",client_id="00000003-0000-0ff1-ce00-000000000000",trusted_issuers="00000001-0000-0000-c000-000000000000@*,XXXXXX@*,https://sts.windows.net/*/,00000003-0000-0ff1-ce00-000000000000@SSSSSSSSSS",authorization_uri="https://login.windows.net/common/oauth2/authorize"',
        'X-SharePointHealthScore',
        '2',
        'SPRequestGuid',
        'SSSSSSS-72cf-7c587d394051',
        'request-id',
        'SSSSSSS0000-72cf-7c587d394051',
        'MS-CV',
        'n55Gv6WAAAByz3xYfTlAUQ.0',
        'Strict-Transport-Security',
        'max-age=31536000',
        'X-AspNet-Version',
        '4.0.30319',
        'SPRequestDuration',
        '24',
        'SPIisLatency',
        '0',
        'x-ms-suspended-features',
        'features=""',
        'X-Powered-By',
        'ASP.NET',
        'MicrosoftSharePointTeamServices',
        '16.0.0.20802',
        'X-Content-Type-Options',
        'nosniff',
        'X-MS-InvokeApp',
        '1; RequireReadOnly',
        'X-MSEdge-Ref',
        'Ref A: SSSSSSS Ref B: TLV30EDGE0121 Ref C: 2021-01-05T11:12:01Z',
        'Date',
        'Tue, 05 Jan 2021 11:12:01 GMT' ],
     trailers: {},
     rawTrailers: [],
     aborted: false,
     upgrade: false,
     url: '',
     method: null,
     statusCode: 401,
     statusMessage: 'Unauthorized',
     client:
      TLSSocket {
        _tlsOptions: [Object],
        _secureEstablished: true,
        _securePending: false,
        _newSessionPending: false,
        _controlReleased: true,
        _SNICallback: null,
        servername: 'XX.sharepoint.com',
        alpnProtocol: false,
        authorized: true,
        authorizationError: null,
        encrypted: true,
        _events: [Object],
        _eventsCount: 8,
        connecting: false,
        _hadError: false,
        _handle: [TLSWrap],
        _parent: null,
        _host: 'XX.sharepoint.com',
        _readableState: [ReadableState],
        readable: true,
        domain: null,
        _maxListeners: undefined,
        _writableState: [WritableState],
        writable: true,
        allowHalfOpen: false,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: undefined,
        _server: null,
        ssl: [TLSWrap],
        _requestCert: true,
        _rejectUnauthorized: false,
        parser: null,
        _httpMessage: null,
        [Symbol(res)]: [TLSWrap],
        [Symbol(asyncId)]: -1,
        [Symbol(lastWriteQueueSize)]: 0,
        [Symbol(timeout)]: null,
        [Symbol(kBytesRead)]: 0,
        [Symbol(kBytesWritten)]: 0,
        [Symbol(connect-options)]: [Object] },
     _consuming: false,
     _dumped: false,
     req:
      ClientRequest {
        domain: null,
        _events: [Object],
        _eventsCount: 5,
        _maxListeners: undefined,
        output: [],
        outputEncodings: [],
        outputCallbacks: [],
        outputSize: 0,
        writable: true,
        _last: false,
        chunkedEncoding: false,
        shouldKeepAlive: true,
        useChunkedEncodingByDefault: true,
        sendDate: false,
        _removedConnection: false,
        _removedContLen: false,
        _removedTE: false,
        _contentLength: null,
        _hasBody: true,
        _trailer: '',
        finished: true,
        _headerSent: true,
        socket: [TLSSocket],
        connection: [TLSSocket],
        _header:
         'POST /sites/XXXX/_vti_bin/Lists.asmx HTTP/1.1\r\nContent-Type: text/xml; charset=utf-8\r\nAccept: application/xml, text/xml, */*; q=0.01\r\nUser-Agent: SharepointPlus\r\nAuthorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciXXXXXXXXXXXXXXXXXXXXXXXXXXXXTehJeD8GDffolFOjK7EAXGzew6d_y06YQAs88NMcO4L0EwfIxlt78qGLajMdsdsdsdsdsvNuIdV4_v1xLoBBX5MhYTmT4WQh5-KYbMqqyh97SFXTJYh43T_8k9wOXiPMuwwBqb-Ywcmu65A\r\nhost: XX.sharepoint.com\r\ncontent-length: 838\r\nConnection: keep-alive\r\n\r\n',
        _onPendingData: [Function: noopPendingOutput],
        agent: [Agent],
        socketPath: undefined,
        timeout: undefined,
        method: 'POST',
        insecureHTTPParser: undefined,
        path: '/sites/XXXX/_vti_bin/Lists.asmx',
        _ended: true,
        res: [Circular],
        aborted: undefined,
        timeoutCb: null,
        upgradeOrConnect: false,
        parser: null,
        maxHeadersCount: null,
        [Symbol(isCorked)]: false,
        [Symbol(outHeadersKey)]: [Object] },
     request:
      Request {
        domain: null,
        _events: [Object],
        _eventsCount: 5,
        _maxListeners: undefined,
        method: 'POST',
        strictSSL: false,
        headers: [Object],
        resolveWithFullResponse: true,
        body:
         '<soap:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"><soap:Body><GetListItems xmlns="http://schemas.microsoft.com/sharepoint/soap/"><listName>Shared%20Documents/</listName><viewName></viewName><query><Query></Query></query><viewFields><ViewFields Properties=\'True\'><FieldRef Name="FileLeafRef" /></ViewFields></viewFields><rowLimit>0</rowLimit><queryOptions><QueryOptions><DateInUtc>False</DateInUtc><Paging ListItemCollectionPositionNext=""></Paging><IncludeAttachmentUrls>True</IncludeAttachmentUrls><IncludeMandatoryColumns>False</IncludeMandatoryColumns><ExpandUserField>False</ExpandUserField><ViewAttributes Scope="Recursive"></ViewAttributes></QueryOptions></queryOptions></GetListItems></soap:Body></soap:Envelope>',
        simple: true,
        agent: [Agent],
        readable: true,
        writable: true,
        explicitMethod: true,
        _qs: [Querystring],
        _auth: [Auth],
        _oauth: [OAuth],
        _multipart: [Multipart],
        _redirect: [Redirect],
        _tunnel: [Tunnel],
        _rp_resolve: [Function],
        _rp_reject: [Function],
        _rp_promise: [Promise],
        _rp_callbackOrig: undefined,
        callback: [Function],
        _rp_options: [Object],
        setHeader: [Function],
        hasHeader: [Function],
        getHeader: [Function],
        removeHeader: [Function],
        localAddress: undefined,
        pool: {},
        dests: [],
        __isRequestRequest: true,
        _callback: [Function: RP$callback],
        uri: [Url],
        rejectUnauthorized: false,
        proxy: null,
        tunnel: true,
        setHost: true,
        originalCookieHeader: undefined,
        _jar: true,
        port: 443,
        host: 'X.sharepoint.com',
        path: '/sites/XXXX/_vti_bin/Lists.asmx',
        httpModule: [Object],
        _started: true,
        href:
         'https://XX.sharepoint.com/sites/XXXX/_vti_bin/Lists.asmx',
        req: [ClientRequest],
        ntick: true,
        response: [Circular],
        originalHost: 'XX.sharepoint.com',
        originalHostHeaderName: 'host',
        responseContent: [Circular],
        _destdata: true,
        _ended: true,
        _callbackCalled: true },
     toJSON: [Function: responseToJSON],
     caseless: Caseless { dict: [Object] },
     body: '401 UNAUTHORIZED' },
  responseText: '401 UNAUTHORIZED' }

**Comment by Aymkdn** [comment]
Based on the error message it seems an authentication error. Are you sure the credentials are correct?
SharepointPlus is using the WebServices and not the REST API, so it might also be related to it? Because you said you tried the authentication with `node-sp-auth` and it worked, but you try it with the REST API under _https://XX.sharepoint.com/sites/XXXX/_ or with an app?

Also (I don't think it's related, but just to make sure), instead of "Shared%20Documents" it should be "Shared Documents", or even "Documents": it's the display name that you must use. So if your document library is called "Documents" but the URL is "Shared%20Documents" then you msut pass "Documents".

**Comment by anabwan** [comment]
see below node-sp-auth code exmple:
    
 ```
const spauth = require('node-sp-auth');
const request = require('request-promise');

 let result = {};
      spauth
        .getAuth(SITE_URL, {
            clientId: "<BLA>",
            clientSecret: "<BLABLA>",
            realm: "<BLABLABLA>"
        })
        .then(data => {
          //console.log("&&&&&&&&&&&&&&&&&&&&&&&& ", data);
          var headers = data.headers;
          headers['Accept'] = 'application/json;odata=verbose';
          request.get({
            url: SITE_URL + "_api/web/getFolderByServerRelativeUrl('Shared%20Documents')/files",
            headers: headers,
            json: true
          }).then(data => {

           console.log("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa,", JSON.stringify(data));
}
```

on the last console I received the data...

**Comment by Aymkdn** [comment]
I guess the AddIn method only works when using the REST API (system permissions), while the WebServices are based on the user permissions.

You could use the fedauth method described here: https://github.com/Aymkdn/SharepointPlus/wiki/Using-the-FedAuth-Cookie#javascript-code – but it requires a login/password.

**Comment by anabwan** [comment]
I see, thanks 👍
