### ISSUE TITLE
Creating a file with some fields throws an error 

### ISSUE THREAD

**Issue by SemonnomeS** [Aymkdn/SharepointPlus#160]
In case when i create a new file without fields, everything works nice. But when i provide some fileds ( even when i pass empty fileds object ) request throws an error.  I will provide image bellow. 

![image](https://user-images.githubusercontent.com/25118872/104007064-a2f0a400-51a7-11eb-9cd2-ce9ff3c16960.png)

My code, which is identical to yours on https://aymkdn.github.io/SharepointPlus/files.html#createFile

![image](https://user-images.githubusercontent.com/25118872/104007304-07abfe80-51a8-11eb-9edd-4668fb7b1bff.png)

**Comment by Aymkdn** [comment]
Can you check the Network tab of your web console? To see what the server returns to the request.

**Comment by Aymkdn** [comment]
The way it works:

1. It will first create the file (without info because we cannot do it in one request);
2. It will check the `uri` returned by the server once the file has been created;
3. It will use it to figure out the item ID;
4. It will do a `$SP().list().update()` using the item ID and the provided fields.

**Comment by SemonnomeS** [comment]
It gives an error 409 (conflict) in network tab and than 401 (unauthorized). But without fields i can save file and also i can update manually ( i have full permissions ).

**Comment by Aymkdn** [comment]
Do you see the request that is done using the `uri` returned by the server after the file's creation? It might be where the 401 error is returned?

Is there a conflict because the file is checked out? Or something similar?

**Comment by SemonnomeS** [comment]
In the case that it makes two requests first creation of file than update. It should save that file without fileds i think. But nothing is saved. Currently i am saving three files in a row.
 
![image](https://user-images.githubusercontent.com/25118872/104009099-c49f5a80-51aa-11eb-878c-e714413f7559.png)

**Comment by SemonnomeS** [comment]
Sometimes it is 500, sometimes it is error 409 
![image](https://user-images.githubusercontent.com/25118872/104009386-4099a280-51ab-11eb-819d-2d3d7aca05a2.png)

**Comment by Aymkdn** [comment]
It's hard to say what's going on... You should try with one file at a time to see if it works, and clear the network tab before processing, then click on each request that is sent to verify the content of the request and the response from the server.

**Comment by SemonnomeS** [comment]
Thank you for the support. I will try to make an update on my own for each file once files are saved without fileds. Can you please tell me, where/how can i pass overwrite=false for the files creation ?

**Comment by Aymkdn** [comment]
> where/how can i pass overwrite=false for the files creation

It's actually a good question. It's hardcoded and not a parameter as of today... It's something I could add in the next release. I can try to release a new version later today if it helps...

**Comment by SemonnomeS** [comment]
Yes it would help a lot. Thank you for your fast response and good help.

**Comment by Aymkdn** [comment]
FYI I've just tried on my side (Sharepoint 2013 OnPrem) and three requests are sent:
![image](https://user-images.githubusercontent.com/946315/104025651-3edcd880-51c5-11eb-8294-439371deeda2.png)

I'm working on the new release right now.

**Comment by SemonnomeS** [comment]
Currently my sharepoint is running locally using proxy, and i think maybe that is why the request (updating) which comes after saving file doesnt work because base url is not provided for the second request.

**Comment by Aymkdn** [comment]
The new version (v6.1.3) has just been published: [changelog](https://github.com/Aymkdn/SharepointPlus/blob/master/changelog.md)

There is now an option `overwrite` (https://aymkdn.github.io/SharepointPlus/files.html#createFile) – if the file already exists it will thrown an error.
