### ISSUE TITLE
getWorkflowID does not work in NodeJS

### ISSUE THREAD

**Issue by saunlani** [Aymkdn/SharepointPlus#161]
Hello!

I'm attempting to use the workflow functions in a NodeJS API I've written because our business has a requirement for programmatically terminating an existing workflow (and triggering a new one) when a list item is updated by a user.

```
sp.list("MyListName","https://portal.corp.company.com/").getWorkflowID({ID:6737, workflowName:"WorkflowName"}).then(function(params) {
  console.log("Workflow ID:"+params.workflowID+" and the FileRef is: "+params.fileRef);
});
```

`(node:37412) UnhandledPromiseRejectionWarning: [SharepointPlus 'getWorkflowID'] This function must be executed from a Sharepoint page (JSOM support is required).`

Is there any possibility to use these functions outside of a SharePoint page? Or do you have any other suggestions?

Thanks very much!

**Comment by Aymkdn** [comment]
I think the WorkflowID only changes when a workflow is republished. So maybe you could find the workflowID in the webpage environment, and then store this ID and FileRef somewhere?

**Comment by Aymkdn** [comment]
Are you using the credentials of a Site Collection admin? Because the error "This function must be executed from a Sharepoint page" is triggered if the script has not been able to get the information due to lack of permissions, then it will try to do it with JSOM (at least for a SP2013 environment, and I'm not sure for a SP Online)

**Comment by saunlani** [comment]
wow, first and foremost just want to say thank you for your incredibly timely response.
secondly, thanks for the excellent solution and making this very useful package!

**Comment by Aymkdn** [comment]
My pleasure 🙏

I'll close this issue now. You can reply here if you have more difficulties related to it.

**Comment by saunlani** [comment]
so i can find the workflow without issue, but when i attempt to stop it i get this error:

**Comment by Aymkdn** [comment]
There is no API to stop a workflow. So as a workaround the script opens an iframe to the Workflow Instance page where there is the "stop workflow" opton. And then the form is posted to cancel the workflow.

In a Node environment, I'm not sure right now. I'll have to do some research to see how it's possible to have the same kind of behavior.
