### ISSUE TITLE
$SP().getUserInfo POST Status 500 error

### ISSUE THREAD

**Issue by itsn78** [Aymkdn/SharepointPlus#163]
statusCode: 500, responseText: "<?xml version="1.0" encoding="utf-8"?><soap:Envelo…/detail></soap:Fault></soap:Body></soap:Envelope>", request: XMLHttpRequest}

most of the people related functions have the same error any idea why ?

**Comment by Aymkdn** [comment]
You need to pass a correct username. Depending on your Sharepoint it could be something like "i:0#.w|domain\\username", or something else…

**Comment by itsn78** [comment]
it worked like a charm, thank you so much !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
