### ISSUE TITLE
.get() paging and rowlimit not working for SPO document library

### ISSUE THREAD

**Issue by landrysn** [Aymkdn/SharepointPlus#164]
`$SP()
    .list("Attachments")
    .get({
      rowlimit: 5000,
      paging: true,
      json: true,
      fields: "FileRef,FileLeafRef,DocumentIDs,Title,AttachmentType,ID"
    })`

That's the structure of the call... I can't find a known issue implementing paging on a document library so I appreciate any and all help. I love the library btw :-)

**Comment by landrysn** [comment]
To add context on the response, "The attempted operation is prohibited because it exceeds the list view threshold." Library is at 5,045 documents.

**Comment by Aymkdn** [comment]
Document Libraries are a bit different from regular lists, and you have to use `folderOptions`:.

```js
$SP() .list("Attachments") .get({
  paging: true, // the rowlimit is 5000 by default
  json: true,
  fields: "FileRef,FileLeafRef,DocumentIDs,Title,AttachmentType,ID",
  folderOptions:{
    show:"FilesAndFolders_Recursive"
  }
})
```

**Comment by landrysn** [comment]
Thank you very much for the response! Still receiving the error although we are probably onto something... the library is completely flat (no folders currently).

**Comment by Aymkdn** [comment]
I only have the same kind of libraries on a Sharepoint 2013 and it works (I have 6k+ files). It's also a flat library without any folder. It would probably work the same for SPO...

**Comment by Aymkdn** [comment]
Try with some other `fields`. In my test I used `fields:"BaseName,FileRef,FSObjType"`. Just to make sure it's not a column that causes some issues.

Other than that, I don't think I can do anything more!

**Comment by landrysn** [comment]
Thank you Sir but no luck... Not sure what it could. Ended up doing a recursive method based on last ID for the batching and was able to get it up and running. I'll keep playing with it... this will bother me until I figure out why the SPO environment is fighting me on this.
