### ISSUE TITLE
need an example for add.options.packetsize

### ISSUE THREAD

**Issue by itsn78** [Aymkdn/SharepointPlus#165]
will be thankful if you can share an example of adding multiple items using packetsize option
#question

**Comment by Aymkdn** [comment]
`packetsize ` is not for that. If you want to add several items, just pass an array of objects instead of one object as first argument.

**Comment by itsn78** [comment]
THANK YOU !!!

**Comment by itsn78** [comment]
I tried creating an array of objects (consisting of 65 items) but it did upload only 60. any idea why only 60 ?

this is my code
var x = document.getElementById("txtTitle").value;
var y = document.getElementById("txtText1").value;
var obj = [{Title:x,Text1:y},{Title:x,Text1:y}...{Title:x,Text1:y}] //the last object in the array is the 65th item
$SP().list("TestList1").add(obj,`packetsize`);

**Comment by itsn78** [comment]
I realized the add method needs some time to upload all the items and i was refreshing the page too quickly i.e. location.reload() 2000 :D

**Comment by Aymkdn** [comment]
It's a promise function so you can do:
```js
$SP().list("TestList1").add(obj).then(function() {
  alert("done!") 
}) 
```

**Comment by itsn78** [comment]
you are just amazing @Aymkdn
