### ISSUE TITLE
setReadOnly:Error

### ISSUE THREAD

**Issue by GermanBob** [Aymkdn/SharepointPlus#166]
Hi,
I try to set the Author field on an Item but I get everytime an error "Uncaught [SharepointPlus 'setReadOnly']: the list ID/Name is required"

I try this at the end:
 $SP().list("Listname").setReadOnly("Author", false)
            .then(function () {
                $SP().list("Listname").update({ ID: 1, Author: 1478 })
            });
I tried the same with add but I get the same error.

Thanks in advance

**Comment by Aymkdn** [comment]
There is a bug, indeed.

Let me a few hours and I'll publish a new version that fixes it!

**Comment by Aymkdn** [comment]
I've just published v6.1.5 that should fix it. Please, try and if you still have issues, feel free to post here again.

**Comment by GermanBob** [comment]
Thanks,
 now it works perfect
