### ISSUE TITLE
Observables with Sharepoint+

### ISSUE THREAD

**Issue by agobeljic1** [Aymkdn/SharepointPlus#167]
I am currently researching about whether it is possible to use observables from RxJs(package commonly used in Angular, but also available as standalone) for requests made with Sharepoint+. Observables have many operators by themselves and they are slightly faster than regular promises and because of that I am investigating about the potential transition. 
The thing is one can always call "of(myPromise)" and turn it to observable but that causes poorer performance since Javascript needs to convert a promise to observable. I am wondering if there is an option or will it be maybe in the future, so that sharepoint+ can natively return observables

**Comment by Aymkdn** [comment]
Sorry, but there is no plan to natively support Observables!
