### ISSUE TITLE
Getting the count of rows from a list

### ISSUE THREAD

**Issue by agobeljic1** [Aymkdn/SharepointPlus#168]
Is it possible to get a count of data from a list in such a way it is optimized and doesn't send me the data, only the number of how many rows are there in a list
I know I can get a count of data by getting the length from the array I received, but I want a faster way which only gets me the count, and it is much faster than getting all the data

**Comment by Aymkdn** [comment]
Not with SharepointPlus. I'm using the REST API when I need to do it : https://sharepoint.stackexchange.com/a/231872

**Comment by Aymkdn** [comment]
You can call it with $SP().ajax()
