### ISSUE TITLE
Error from server-side node

### ISSUE THREAD

**Issue by eniro** [Aymkdn/SharepointPlus#169]
Hello,

I'm trying to use SharepointPlus for the first time, with SharePoint Online.
I tried to use it client-side but I am getting CORS error (the requirement is to upload certain data from a custom outlook add-in to sharepoint).
So, now I'm trying to use it from server-side node like this:

```
        const $SP = require('sharepointplus');    
        const credentials = {
        "username":"test@test.com",
        "password":"testest",
        "domain":"https://mycompany.sharepoint.com"
      }


      const sp = $SP().auth(credentials);
      sp().list("Files","https://mycompany.sharepoint.com/sites/dev").get({
        fields:"Title",
      }).then(function(data) {
        for (var i=0; i<data.length; i++) console.log(data[i].getAttribute("Title"));
      });

```

but I keep getting this error:

![image](https://user-images.githubusercontent.com/32244352/117696617-2cea6100-b1ca-11eb-97b2-75e8ae1df62a.png)

Any help would be greatly appreciated!

**Comment by eniro** [comment]
Thank you very much for the quick response!

I changed it and now I'm getting this error:

![image](https://user-images.githubusercontent.com/32244352/117700364-94a2ab00-b1ce-11eb-92fb-c8fac4075730.png)

Is there anything else I could be missing?

**Comment by Aymkdn** [comment]
Because it's not `sp()` but `sp`:
```js
const $SP = require('sharepointplus/dist');    
const credentials = {
  "username":"test@test.com",
  "password":"testest",
  "domain":"https://mycompany.sharepoint.com"
}

const sp = $SP().auth(credentials);
sp.list("Files","https://mycompany.sharepoint.com/sites/dev").get({
  fields:"Title",
}).then(function(data) {
  for (var i=0; i<data.length; i++) console.log(data[i].getAttribute("Title"));
});
```
