### ISSUE TITLE
addAttachment contextinfo 404 error

### ISSUE THREAD

**Issue by Cumbalin** [Aymkdn/SharepointPlus#170]
I'm trying to use the addAttachment with a materialize.css input type="file", but I am getting a POST https://...../_api/contextinfo 404 (NOT FOUND) error message.

Any ideas?

**Comment by Aymkdn** [comment]
Please, share your code… It could be dozen of different reasons :-)

**Comment by Cumbalin** [comment]
Thanks for the quick reply.

HTML
`<input id="inp_filepath" type="file">`
`<button id="btn_filsave" spid="" edit="new" class="btn btn-primary btn-sm" style="width:85px;">Save</button>`

JS
```
$(document).on('click', '#btn_filsave', function(e) {
	e.preventDefault()
	var spid = $('#tx_spid').html()
	var filed = $('#inp_filedisplay').val()
	var filep = $('#inp_filepath').val()

	var data = []
	var fileArray = []
	$('#inp_filepath').each(function() {
		if ($(this)[0].files[0]) {
			fileArray.push({"Attachment": $(this)[0].files[0]})
		}
	});

	$SP().list(list_esc).addAttachment({
		ID:spid,
		filename:filed,
		attachment:fileArray,
	}).then(function(fileURL) {
		checkAttachments()
		console.log(fileURL)
	});

});
```

**Comment by Aymkdn** [comment]
You need to read the file content and pass it…

Example:
```js
// with something like: <input type="file" onchange="addAttachment(event)">
function addAttachment(event) {
  let files = event.target.files;
  let fileReader = new FileReader();
  fileReader.onloadend = function(e) {
    let content = e.target.result;
    $SP().list("MyList").addAttachment({
      ID:itemID,
      filename:files[0].name,
      attachment:content
    })
    .then(function(url) {
      console.log({url})
    })
    .catch(function(err) {
      console.log(err)
    })
  }
  fileReader.onerror = function(e) {
    alert('Unexpected error: '+e.target.error);
  }
  fileReader.readAsArrayBuffer(files[0]);
}
```

**Comment by Cumbalin** [comment]
I tried it that way:
`<input id="inp_filepath" onchange="addAttachment(event)" type="file">`
```
function addAttachment(event) {

var spid = $('#tx_spid').html()

  let files = event.target.files;
  let fileReader = new FileReader();
  fileReader.onloadend = function(e) {
    let content = e.target.result;
    $SP().list(list_esc).addAttachment({
      ID:spid,
      filename:files[0].name,
      attachment:content
    })
    .then(function(url) {
      console.log({url})
    })
    .catch(function(err) {
      console.log(err)
    })
  }
  fileReader.onerror = function(e) {
    alert('Unexpected error: '+e.target.error);
  }
  fileReader.readAsArrayBuffer(files[0]);
}

```

but now I'm getting a different error message.
`POST https://site../_vti_bin/Lists.asmx 500 (Internal Server Error)`
followed by the error array.

**Comment by Aymkdn** [comment]
Check the network tab of the developer console to find the response from the server.

Your Sharepoint didn't like something in what you sent.

**Comment by Cumbalin** [comment]
Great, the error said that the name is already in use. The file was in the folder, but for some reason it was not showing up in the item. Must of been corrupted somehow. I deleted that specific file, and now it seems to be uploading new files correctly onto the item, but I'm still getting that original `POST ../_api/contextinfo 404 (NOT FOUND)` error in my console. But then right after the error I'm getting the correct URL for the item.

Any other suggestions for this contextinfo 404?

**Comment by Aymkdn** [comment]
Which version of Sharepoint are you using? Because it tries to get a Digest Token from Sharepoint 2013 and newer, from the `contextinfo`, in order to upload the file using REST API.

In your case it cannot find it, so it's supposed to use the alternate solution that is the SOAP Services.

**Comment by Cumbalin** [comment]
Oh that could be it, this specific site I'm using a 2010 farm.
It looks like it's still uploading the file correctly.
How do I ignore/remove that error?

**Comment by Aymkdn** [comment]
Check what you have in `window._SP_CACHE_HASREST` after attaching a file to check how the `url` param looks like.

Then in your code, at the beginning of your script, you can add:
```js
window._SP_CACHE_HASREST["URL_OF_YOUR_SITE"] = false;
```

In theory, it should directly know that your site doesn't support REST API so it should not check it.

**Comment by Cumbalin** [comment]
It didn't work unfortunately.

**Comment by Aymkdn** [comment]
I guess you're using the last version of SharepointPlus?

Are you sure you correctly replicate `window._SP_CACHE_HASREST` after attaching a file to check? Because the `url` parameter needs to be exactly the same.

**Comment by Cumbalin** [comment]
Maybe not, can you help me?
I put it at the begging of the addAttachment funciton.

```
function addAttachment(event) {
	window._SP_CACHE_HASREST[url_esc] = false;

	var spid = $('#tx_spid').html()

  let files = event.target.files;
  let fileReader = new FileReader();
  fileReader.onloadend = function(e) {
    let content = e.target.result;
    
   	$SP().list(list_esc).addAttachment({
		ID:spid,
		filename:filed,
		attachment:content,
	}).then(function(fileURL) {
		clog(fileURL)
		checkAttachments()		
	});


  }
  fileReader.onerror = function(e) {
    alert('Unexpected error: '+e.target.error);
  }
  fileReader.readAsArrayBuffer(files[0]);
}
```

**Comment by Aymkdn** [comment]
Do these steps:

1. Attach a file
2. In the developer console, type: `console.log(JSON.stringify(window._SP_CACHE_HASREST))`   
    It should return something like `{"http://intranet/sites/Whatever":false}`
3. At the top of your code (before `function addAttachment(event)`) enter: `window._SP_CACHE_HASREST={"http://intranet/sites/Whatever":false}`
4. Reload the page
5. In the developer console, type: `console.log(JSON.stringify(window._SP_CACHE_HASREST))`   
    It should return `{"http://intranet/sites/Whatever":false}`
6. Try to attach a file: the script should not try to check the REST API availability anymore

**Comment by Cumbalin** [comment]
On step 5. It is returning `{site:false}` (but our protocol is HTTP**S** does that matter)?

I followed the steps exactly and put the `window._SP_CACHE_HASREST={"http://intranet/sites/Whatever":false}` before the function, and still getting the 404.

I want to say, I really appreciate your tenacity with helping me on this.

**Comment by Aymkdn** [comment]
Again, the "site" to enter is shown at step 3. So if at step 3 there is https, then it's what you must use. At step 3, it could also just show `/sites/whatever`. 

I forgot step 0: remove any `window._SP_CACHE_HASREST={"http://intranet/sites/Whatever":false}` from your code before following the different steps.

**Comment by Cumbalin** [comment]
Yes I removed it from inside function and moved it to before, and I'm using exactly what the console.log showed.
Does this affect anything? Can I just leave it as is? It's still uploading the file.

FYI - the removeAttachment is sending back an error too, the XML says: "Parameter Url is missing or invalid", should I open a different Issue for this?

**Comment by Aymkdn** [comment]
> Does this affect anything?

No, it doesn't impact or affect anything.

> FYI - the removeAttachment is sending back an error too, the XML says: "Parameter Url is missing or invalid", should I open a different Issue for this?

Make sure you correctly read the documentation.

**Comment by Cumbalin** [comment]
Thank you very much!
This is an amazing plugin by the way!
Much better and easier than anything else I've ever found.

**Comment by Aymkdn** [comment]
Thanks 🙏

I'm closing this issue. Feel free to post here for further questions on this topic, or to open a new one.
