### ISSUE TITLE
Translate SharePoint column names

### ISSUE THREAD

**Issue by greaturchin** [Aymkdn/SharepointPlus#172]
I would like to see a feature added where the display name of a column is available in the call the .list().get(). Or if the _x0020_ type URL encoding could be translated back to plain text. Is this possible now?

**Comment by Aymkdn** [comment]
It's not possible now, but you can get the column's display name using https://aymkdn.github.io/SharepointPlus/lists.html#info as well as the internal name.

I wouldn't recommend to use the display name because if a column is renamed, then you have to change your code...

**Comment by Aymkdn** [comment]
You may also want to look at https://aymkdn.github.io/SharepointPlus/utils.html#toXSLString however be aware this function will only work if the column has never been renamed.
