### ISSUE TITLE
Unable to getContentTypeInfo 

### ISSUE THREAD

**Issue by Cumbalin** [Aymkdn/SharepointPlus#174]
I'm trying to use getContentTypeInfo on a SharePoint 2019 on-premise farm.
The pull is working great for me, but a colleague of mine is getting this error:
`Uncaught (in promise) [SharepointPlus 'getContentTypeInfo'] not able to find Content Type called 'Item' at xxxsiteurlxxx`

I checked the list settings and with the content type Item, and he has full control permission on the site and list.
Is there something I can check/try please?

**Comment by Aymkdn** [comment]
Is this colleague not English? Because SharePoint translates the content types... I'd recommend to change the site settings to disable the languages and to only keep English.

**Comment by Aymkdn** [comment]
In Language Settings of the website 
![Screenshot_20211116-222110.jpg](https://user-images.githubusercontent.com/946315/142067658-30529211-8ff4-4f3b-9599-4f6213f66ac2.jpg)

**Comment by Cumbalin** [comment]
Excellent. French was turned on.
Turning alternative languages worked like a charm.
Thank you!
