### ISSUE TITLE
The site URL passed in the setup object is always ignored in the isMember(...) function

### ISSUE THREAD

**Issue by alexis-allemann** [Aymkdn/SharepointPlus#175]
Each time I use the `isMember(...)` function, the url that I passed as a parameter via the setup object is ignored and thus replaced by the url of the current site.
By analyzing the code, I realized that the `isMember(...)` function calls the `usergroups(...)` function. When calling this one, the site url parameter was forgotten and this method therefore uses the current site.

**Comment by alexis-allemann** [comment]
I have identified the issue. I'll add a new pull request.

**Comment by Aymkdn** [comment]
Thanks. I'll do the necessary changes in the next release.

**Comment by Aymkdn** [comment]
No need for a pull request, I already identified the issue and I fixed it on my side :-) But I won't release the new code right now.

I can show you what to change (it's pretty straight forward), or in the meantime you can directly use `usergroups` or another internal function.

**Comment by alexis-allemann** [comment]
Okay great thank you, any idea when the next release will be published?

**Comment by Aymkdn** [comment]
> any idea when the next release will be published?

Nope… Sorry. 

But as I said, you could directly use `usergroups` in your case.

**Comment by Aymkdn** [comment]
This has been fixed in v6.2.0
