### ISSUE TITLE
joins

### ISSUE THREAD

**Issue by rmartingithub** [Aymkdn/SharepointPlus#181]
Hello and thak you very much for sharepointplus!

i have some problems to join lists:

in:
```js
  $SP().list("List_A",".....").get({
    fields:"List_A_ID,List_A_Title",
    where:"List_A_ID=3",
	join:{
      list:"List_B",
      fields:"List_B_col1,List_B_col2",
	  where:"List_B_col1 <> Null",
      on:" 'List_A'.List_A_ID= 'List_B'.List_B_col1",
	},
  
  }).then(function(data) {
    for (var i=0; i<data.length; i++) { 
        console.log(data[i].getAttribute("List_A.ID")+" | "+data[i].getAttribute("List_A.Title")+"| "+data[i].getAttribute("List_B.List_B_col1")+" | "+data[i].getAttribute("List_B.List_B_col2"));
    }
  });
```

no result. maybe i use the join in a wrong way.
it should compare two integer values

List_A                 List_B
List_A_ID Title    List_B_col1  List_B_col3
1 title1               2                 title12
2 title2               3                 title234
3 title3               5                 title 87687
should be

3 title3    3 title 234
i also tried add all 4 columns in the fieldlists
thanks

**Comment by Aymkdn** [comment]
When you do each request individually, do they return a result?

**Comment by rmartingithub** [comment]
Hello Aymkd,

yes, everything else is working wonderfull at the moment, just the join..
The network response are the two Lists

**Comment by Aymkdn** [comment]
You closed by error? Or you found the solution?

**Comment by rmartingithub** [comment]
Dear Aymkdn, ..... so sorry it is working..
The sharepoint column of table B was set to Number with automatic decimals.. So the value wasnt 3, it was 3.00000.
Not the fault auf sharepointplus.
Is it possible to include a kind of parseInt('Table_B'.ID) to the ON condition?
or something like = cast('Table_B'.ID as integer)
closing, was a mistake, but maybe i should open a new one, because of my fault handling sharepoint

**Comment by Aymkdn** [comment]
No you cannot change the type.

Also it's better to link using a Lookup column.

**Comment by rmartingithub** [comment]
Thank you very much! And thanks for this nice work
