### ISSUE TITLE
$SP.List() Update method with multiple fields

### ISSUE THREAD

**Issue by beruken** [Aymkdn/SharepointPlus#21]
I am trying to update multiple fields in an individual record with a where clause. two fields are look-ups. It seems to work intermittently updating each field individually. If I re-run the code I can get the next one to update (sometimes). i am passing in the correct look-up format ID;#Stringvalue. they are single value look-ups.

 If I try to wrap the fields in an array .update( [{field: value},{field: value}], {where: value}) and make a single call it does not work at all. 

I assume unlike the update() with ID method the update() with where can only handle individual columns one at a time, is this correct? If not, how do I do a multiple field update with look-up columns?

**Comment by Aymkdn** [comment]
Hi,

Yes you can update several items as you can see it into the [documentation examples](http://aymkdn.github.io/SharepointPlus/symbols/%24SP%28%29.list.html#.update) :
```
$SP().list("My List","http://sharepoint.org/mydir/").update([{ID:5, Title:"Ok"}, {ID: 15, Title:"Good"}]);
```

So you have to pass an array of objets. The ID must be provided in each objet. When you use the WHERE clause you mustn't provide several objets.

But I think you didn't explain correctly what you want. The objet must contain all the fields you want to update. So let's say you want to update the fields "Lookup1" and "Lookup2", then you'll do:
```
$SP().list("My List","http://sharepoint.org/mydir/").update({
  "Lookup1": "ID;#String",
  "Lookup2": "ID;#String"
},{
  "where:":"your where clause"
});
```

**Comment by beruken** [comment]
Your answer shows the field names wrapped in quotes which are not present in the documentation. Without quoted field names worked for me. I did not think of just taking the array brackets [] out.

Thanks for your response and a great tool.

**Comment by Aymkdn** [comment]
The quotes are not mandatory. It's a JavaScript object so you can use or not use them :-)

I'm glad you solved your issue.
