### ISSUE TITLE
Can not read property 'length' of indefined when use setup.page 

### ISSUE THREAD

**Issue by enbeznos** [Aymkdn/SharepointPlus#24]
Example:
$SP().list("My List").get({fields:"ID",orderby:"ID DESC",rowlimit:1,paging:true,page:1}, function(data) {   console.log("last ID : "+data[0].getAttribute("ID")); })

When you specify a page number 1, then all is well.
other numbers of pages writes an error
sharepointplus-3.0.10.js: 1134 Uncaught TypeError: Can not read property 'length' of indefined
please tell me what is wrong?

error:
![image](https://cloud.githubusercontent.com/assets/8845945/8873150/64734b12-320c-11e5-80f7-53fb9eb93767.png)

ok:

![image](https://cloud.githubusercontent.com/assets/8845945/8873188/bfc570c6-320c-11e5-8c32-481f245f88fb.png)

**Comment by Aymkdn** [comment]
I'm just tried and it's working correctly. Check the request and the response from the AJAX Call: probably the problem is coming from something else.
