### ISSUE TITLE
Get users in group using groupMembers function (logged with read-only user permission).

### ISSUE THREAD

**Issue by DevGlogicM** [Aymkdn/SharepointPlus#27]
**Background**

In SharePoint Online, I'm using `SharePointPlus` for get info across lists and users. 
I'm currently developing a functionality for query certain info from users _(i.e PreferredName, AccountName, Picture, Birthday, etc)_ from users assigned in a group.

**Current situation**

After test with a admin user credentials all works perfectly. However, since **the functionality must be available for any user of the site**, I had to make another tests with a user who has **read-only** permissions:

I'm using `groupMembers` function for this purpose. When I execute the following code:

```javascript
// Calidad is the name of the group.
$SP().groupMembers("Calidad", function(members) {
  for (var i=0; i < members.length; i++) console.log(members[i]);
});
```

The response is:

`POST https://<site>/<subsite>/_vti_bin/usergroup.asmx 500 (Internal Server Error)`
`Uncaught TypeError: Cannot read property 'firstChild' of undefined`

In the "Source" tab, the error occurs in the "sharepointplus.js" file at line 2933

Here is the [screenshot](http://i.imgur.com/7BrROz4.png?1) and here is the specific line _if there're problems with the screenshot:_

```javascript
// any error ?
var error=req.responseXML.getElementsByTagName("errorstring");
if (typeof console === "object") console.error("Error 'groupMembers':"+error[0].firstChild.nodeValue);
```

When I print "using the console.log command" the `error` variable, it shows a empty object = `[]` when the if condition is true. _i.e here:_ `error[0].firstChild.nodeValue`

This situation doesn't happen with `whoami` function.

I'm wondering if anyone had seen a similar situation.

**Comment by Aymkdn** [comment]
Hi,

Check the Group Settings and make sure that `Who can view the membership of the group?` is **Everyone** and not **Group Members**.

Please let me know.

**Comment by DevGlogicM** [comment]
Hi.

The selected option is: **Group members**

That would explain a part I missed during redacting my question:

When the error _that I mentioned in my question_ appears, the `responseXML` attribute says:

`<?xml version="1.0" encoding="utf-8"?><soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema"><soap:Body><soap:Fault><faultcode>soap:Client</faultcode><faultstring>No se pudo efectuar la operación ---&gt; Access denied. only an administrator can retrieve a count of all users.</faultstring><detail><ErrorCode xmlns="http://microsoft.com/webservices/SharePointPortalServer/UserProfileService">UnauthorizedAccess</ErrorCode><ErrorMessage xmlns="http://microsoft.com/webservices/SharePointPortalServer/UserProfileService">Access denied. only an administrator can retrieve a count of all users.</ErrorMessage></detail></soap:Fault></soap:Body></soap:Envelope>`

Since I'm not the admin of the side "its from one of our clients", I must ask with the person who knows better the SharePoint Online site if would be acceptable make the change about `Who can view the membership of the group` _(I'm more a C# - javascript developer than a SharePoint developer)_.

I'm wondering why in `whoami` this situation is not happening, I can use any credential and the data is retrieved with the read-only user.

Thanks for all your help.

**Comment by Aymkdn** [comment]
The `whoami` is for the current user, so it's normal to get the info for the current user. However the `groupMembers` checks a group, so it's normal to have the appropriate rights to get info from the group...
