### ISSUE TITLE
Left Join

### ISSUE THREAD

**Issue by javanfekr** [Aymkdn/SharepointPlus#28]
Hi
can i have Left Join or Right Join on 2 list?

**Comment by Aymkdn** [comment]
Check the [examples](http://aymkdn.github.io/SharepointPlus/symbols/%24SP%28%29.list.html#.get) : you can have a left join (`join`) or right join (`outerjoin`) from list A to list B and from list B to list C, but you cannot have a join from list A to list B and from list A to list C in the same call.

Actually the `join` is just a multiple call of `$SP().list().get()` that combines the results together. I know a `<Join>` attribute exists (see the [MSDN documentation](https://msdn.microsoft.com/en-us/library/ee535061%28v=office.14%29.aspx)) but I never used it...
