### ISSUE TITLE
Issue with createFile Method

### ISSUE THREAD

**Issue by Lauura** [Aymkdn/SharepointPlus#33]
Hello,

I have a problem with the createFile method. It seems that it doesn't do anything : code after is running perfectly but I don't have any result on my Sharepoint site and it doesn't run the function put in the after attribut either. 
I am using Sharepoint Foundation 2010 for my SharePoint site : do you think it could cause the problem ? 

Thank you for your help,

**Comment by Aymkdn** [comment]
It should work on Sharepoint Foundation 2010 without issue.

Try to install Firebug addon with Firefox and to look at the console. You'll see the request and the answer from the server. It will give you the answer for sure.

Also you might want to share your code to let me see if you did it correctly.

**Comment by Lauura** [comment]
Ok so it seems that the first request can not be done. Here's what the browser tells me :
  Request URL : http://mysite/_vti_bin/copy.asmx
  Status Code : 401 Unauthorized
Do you have an idea what can cause that ?

Here is my code, maybe it can help you to understand my problem 
`<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
<script src="https://cdn.jsdelivr.net/sharepointplus/3.12.0/sharepointplus.min.js"></script>
<script>
	function exportationSharePoint(table, filename)
	{
	var dest = "https://mysite/Team%20Documents/"+filename;
	$SP().createFile({content:table, destination:dest,url:"https://mysite", after:function(){alert("File created !");}});
	
	}
</script>`

Thank you for your help.

**Comment by Aymkdn** [comment]
You should use [Firebug addon](http://getfirebug.com/) with Firefox, and then open it to watch the request that is sent. Then you'll get the real answer from the server (because 401 error code doesn't help at all).
Example: 
![capture](https://cloud.githubusercontent.com/assets/946315/17885824/397aa748-691f-11e6-8344-1bc0048fe125.PNG)

Also, in the coming days, I'll try to release a new version of SharepointPlus. This new release has new options for `$SP().createFile()` and one of them is `error` that permits to catch an error and print it.

**Comment by Aymkdn** [comment]
I've just released the new version of SharepointPlus with the new [createFile](http://aymkdn.github.io/SharepointPlus/symbols/%24SP%28%29.html#.createFile).

**Comment by Lauura** [comment]
Ok I will check it out. Thank you for letting me know :)

**Comment by Aymkdn** [comment]
Please keep me update about your issue :-)

**Comment by Lauura** [comment]
It works really well know ! 

Thank you for your help :)

**Comment by Aymkdn** [comment]
Sorry for the late answer, I didn't receive an email notification....

Yes you can checkin : http://aymkdn.github.io/SharepointPlus/symbols/%24SP%28%29.html#.checkin

I'm now closing this issue :-)
