### ISSUE TITLE
Issue with checkin method 

### ISSUE THREAD

**Issue by Lauura** [Aymkdn/SharepointPlus#35]
Hi, 

I tried to use the checkin method after the creation of an excel file but it gives me a error :
in 3.13/sharepointplus.js line 20 col 4127
_spPageContextInfo is undefined

here is my code : 
```
var dest = "http://monsite.com/file.xls";
$SP().createFile({content:table,destination:dest,url:"https://mysite.com",after:function(){alert("File created");}});
$SP().checkin({destination:dest});

```
Do you have any idea what can cause that ? 

Thank you for your help

**Comment by Aymkdn** [comment]
The `checkin` must be moved into the `after`, because it's asynchronous. Also if you use SharepointPlus 3.13 the options for `createFile` are different:
```javascript
$SP().createFile({
  content:table,
  filename:"file.xls",
  library:"Shared Documents",
  after:function(fileURL){
     alert("File created at "+fileURL);
     $SP().checkin({
       destination:fileURL,
       after:function() { alert("File checked in!") }
     });
  }
});
```

**Comment by Lauura** [comment]
Thank you for your quick answer !
It's working now so I'm closing the issue :)
