### ISSUE TITLE
Object doesn't support property or method 'addAttachment' error on list

### ISSUE THREAD

**Issue by martin0852** [Aymkdn/SharepointPlus#36]
Hi, 

Great library by the way! 

My issue is with the addAttachment method on a sharepoint list .

I am using the off-the-shelf example provided on the site which is as follows:
```
$SP().list("List_Name","http://collaboration.company.com/projects/office_site/sub_page/").addAttachment({
        ID:1,
        filename:"helloworld.txt",
        attachment:"U2hhcmVwb2ludFBsdXMgUm9ja3Mh",
        after:function(fileURL) {
          alert(fileURL)
        }
      });
```
Only change is I have added the url to the list as I am using the library to upload files from a clientside  webapp and so am 'outside' the destination site.
However when I debug (using IE11 - unfortunately a necessity) without even getting into the setup object within the addAttachment() method I get the error in subject line.

I've setup the list to allow attachments however think the issue lies in my setup as the server doesn't appear to be ever queried here.

Adding, updating and removing list items works fine apart from this.

I am using the following cdn:
[https://cdn.jsdelivr.net/sharepointplus/3.13/sharepointplus.min.js](url)

Any help here would be appreciated.

**Comment by Aymkdn** [comment]
Mmmhhh it looks like the CDN file is not the correct version of SharepointPlus-3.13 ... and this is my fault. Sorry about that. I'll see if I can have the actual file on CDN to be updated.

In the meantime you can use https://github.com/Aymkdn/SharepointPlus/blob/master/sharepointplus-3.13.min.js as a local resource!

**Comment by martin0852** [comment]
Hey,

Thanks for fast response - I am using the local file for now and it works well with the example above.

Thanks for the help!

**Comment by Aymkdn** [comment]
The cdn.jsdelivr.net should now reflect the correct file!
