### ISSUE TITLE
Remove attachments from list item

### ISSUE THREAD

**Issue by martin0852** [Aymkdn/SharepointPlus#37]
Hi Not sure if this is an issue but a feature request.

I've tried to remove attachments from List items with no luck.

I have tried the 
`// example for deleting a file
$SP().list("My List","urltolist"}).remove({ID:4,FileRef:"my/directory/My Shared Documents/something.xls"});` example which deleted the item. 

I've also tried setting the Attachments field to nothing:
```
$SP().list("My List","urltolist").update(
  			{ID:2,Attachments:""},{success:function(items){
      		items.map(function(i){
            console.log("Success");
      		})
    	},error:function(items) {
        items.map(function(i){
          console.log(i.errorMessage);
        })
    	}});
```

But this appears to do nothing.
Is there a way to remove the attachments from a List item?

**Comment by Aymkdn** [comment]
Hi. I don't know how to remove an attachment... At least I don't think it's possible with SharepointPlus... Maybe there is a web service to do it. I'm currently on vacation so I cannot really search for it....

**Comment by martin0852** [comment]
Hi Aymkdn,

Thanks for reply.

Found the answer I was looking for [here](http://sharepoint.stackexchange.com/questions/137752/how-to-delete-list-attachments-using-javascript)

```
$().SPServices({
    webURL : "http://path to site"
    operation: "DeleteAttachment",
    listName: "List Name",
    listItemID: itemId, //list item id
    url: filePath, //url of attachment that needs to be deleted
    completefunc: function (xData, Status) {
        console.log('Deleted');
    }
});
```

**Comment by Aymkdn** [comment]
OK cool!
