### ISSUE TITLE
Strange behavior in IE11 Version 11.0.9600.18449

### ISSUE THREAD

**Issue by marcorensch** [Aymkdn/SharepointPlus#39]
Hi
i have created on one of our sharepoint sites a simple call to a sharepointlist. This one is to create a little HowTo. Because i have already created a fully functional dashboard with sharepointlist datas on another site. But this one is strange.

when i try to do a simple View command i receive in IE 11 an error:
"XML5619: Fehlerhafte Syntax in einem Dokument. Zeile: 1, Spalte 1" and the call stops.
When i check the console under network i see an Error 404:
Respone from Webs.asmx:
`<?xml version="1.0" encoding="utf-8"?><soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema"><soap:Body><WebUrlFromPageUrlResponse xmlns="http://schemas.microsoft.com/sharepoint/soap/"><WebUrlFromPageUrlResult>https://xy.ch/projects/advanced-sharepoint-things/charts</WebUrlFromPageUrlResult></WebUrlFromPageUrlResponse></soap:Body></soap:Envelope>`

Webs Demand in IE:
`<soap:Envelope xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance' xmlns:xsd='http://www.w3.org/2001/XMLSchema' xmlns:soap='http://schemas.xmlsoap.org/soap/envelope/'><soap:Body><WebUrlFromPageUrl xmlns='http://schemas.microsoft.com/sharepoint/soap/' ><pageUrl>https://xy.ch/projects/advanced-sharepoint-things/charts/SitePages/test_6.html</pageUrl></WebUrlFromPageUrl></soap:Body></soap:Envelope>`

_i have removed our domainname_

Views Demand in IE is:
`<?xml version="1.0" encoding="utf-8"?><soap:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">  <soap:Body>    <GetViewCollection xmlns="http://schemas.microsoft.com/sharepoint/soap/">      <listName>Demoliste</listName>    </GetViewCollection>  </soap:Body></soap:Envelope>`

Repsonse from Views.asmx:
`404 FILE NOT FOUND`

and here is the path to the listfile:
https://xy.ch/projects/advanced-sharepoint-things/charts/Lists/Demoliste/AllItems.aspx
_i have removed our domainname_
Listname is: "Demoliste"
the View is: "Alle Elemente" or "dataview"

this is how i'd like to get the columns:
` $(document).ready(function(){
                $SP().list("Demoliste").view('Alle Elemente',function(data) {
                    var array = [];
                    for(var i=0; i<data.fields.length;i++){
                        array.push(data.fields[i]);
                    }
                        console.log(array);
                });
            });`

the same Page shows me in FF the Array with the column titles, so no error - but with IE it did not take this list. Whats wrong here?

I've tried it out with SP Plus Version 3.12 & 3.13 (because my working dashboard runs with 3.12)
The list is saved on a subweb (same level as the html file which calls it).

thanks for this great script / framework - its very nice :-)
but have you any clue why that did not work?

**Comment by Aymkdn** [comment]
This is odd...

What happens if you try the same command but with another list in IE ?

What happens if you try to open https://xy.ch/projects/advanced-sharepoint-things/charts/_vti_bin/Views.asmx in IE ? 

Are you in Strict Mode or Quirks Mode ?

Which version of jQuery do you use ?

On [StackOverflow](http://stackoverflow.com/questions/15360918/xml5619-incorrect-document-syntax-error-in-ie10-only) they suggest it could be a problem of content-type...

**Comment by marcorensch** [comment]
Hi Aymkdn
Same Site another list = same issue (i have created a new list)
If i open the Views.asmx i see the following list:

- AddView 
- DeleteView 
- GetView 
- GetViewCollection 
- GetViewHtml 
- UpdateView 
- UpdateViewHtml 
- UpdateViewHtml2 

Doctype is html <!DOCTYPE html>
and i use the meta: <meta http-equiv="X-UA-Compatible" content="IE=edge">  
because of uikit, for the design... but its the same header informations as it is on a working site.

I tried with jquery 2.2.4 and 3.0.0

i think now the "incorrect syntax" is the error 404 message itself because it is not in XML format :-)
the question is - why the hack its not finding the list?

**Comment by Aymkdn** [comment]
Then, I don't know... I tried on my IE 11 (11.0.9600.18450) with jQuery 1.12.3 and it works as expected.

As I cannot reproduce your issue, it's not possible for me to help you more than that.

If you figure out what's wrong, please let me know!

**Comment by marcorensch** [comment]
sure :-) thanks for the try

**Comment by Aymkdn** [comment]
Have you been able to figure out the problem?

**Comment by marcorensch** [comment]
Hi Aymkdn
i was not really able to understand the issue so i created a new "Workspace" (a new primary host in our sharepoint) now the path is "https://xy.ch/communities/ast/charts"
there it works without any errors.

could it be that our IE does something wrong with the Path if there are dashes in it? 
i created my new workspace as a community workspace and not as a project but in fact there is no technical difference between those two virtual hosts - its just for the default page template / activated features. (keep in mind - in Firefox and Chrome it had worked!) - so i don't think it has something to do with the host itself.

so in fact, in our company IE will also be replaced by EDGE in a few months, so at least it works for me for now even if we don't really understand why that issue happened :-)

thanks for your fast response and really nice product :-)

**Comment by Aymkdn** [comment]
Thanks for the update :-)
