### ISSUE TITLE
CORS issue in chrome

### ISSUE THREAD

**Issue by martin0852** [Aymkdn/SharepointPlus#40]
Hi - Not sure if this is an "issue" but I wanted to ask how CORS is handled in Chrome as when i attempt to get list data I get the following:

`
XMLHttpRequest cannot load http://collaboration.<company>.com/projects/<site-name>/_vti_bin/Lists.asmx. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'null' is therefore not allowed access. The response had HTTP status code 401.  `

Clearly this library is supported on Chrome so I must be doing something wrong (no issue on IE11)

How do I do this request on chrome?

Thanks (sorry for opening issue I didn't know how to ask otherwise)

**Comment by Aymkdn** [comment]
Hi. This is not related to SharepointPlus...

Does your server return "Access-Control-Allow-Origin" ? If I believe the error returns by Chrome, it's not the case. Without it you cannot do cross domain requests. I'm surprised it works on IE11....

If you need more help on this issue you probably want to post on StackOverflow that is a more appropriate place for it as it's not related to my framework ;-)

**Comment by micuentadecasa** [comment]
Hi Aymkdn, I'm getting something similar in IE 11, I got "/_vti_bin/lists.asmx required CORS PREFLIGHT", I have tested on different browsers and only happens with one browser (IE11) so should be no your fault but any idea will help us.

**Comment by Aymkdn** [comment]
@micuentadecasa is your IE11 loaded as IE11 ? Open the web console (F12) and check you have 11 for the document type under "Emulation" tab.

If you need more help on this issue you probably want to post on StackOverflow that is a more appropriate place for it as it's not related to my framework, and make sure to provide correct code and explanations about server configuration.

**Comment by micuentadecasa** [comment]
IE11 that doesn't works - emulation 10 default
IE11 that works - EMULATION 5 default

what does it means?
