### ISSUE TITLE
Addnig fields to createFile not working

### ISSUE THREAD

**Issue by haitechdev** [Aymkdn/SharepointPlus#42]
Hi,

I am trying to create a file in SharePoint 2007. I can create the file however data in the fields option are not being adding to the file.

My code is:

$SP().list("DocumentLibraryName", "SiteURL").createFile({
        content: content,
        encoded: true,
        filename: name,
        destination: destination,
        fields: {
                "Document_x0020_Type": docTypeVariable,
                "IA_ID_Code": iaIDVariable
        },
        after;function() {
        }
});

I am using version SharepointPlus v3.0.4

Do you have any other solutions for me to achieve this?

Thanks,
Matt

**Comment by Aymkdn** [comment]
Hi.

The document is for SharepointPlus 3.13. The `createFile` arguments/options were different for the previous versions of SharepointPlus, so make sure you use the last version.
Also I don't use Sharepoint 2007 anymore so I cannot guarantee it will work.

Other alternative: you can first create the file, and then use `$SP().list().update()` to update the fields for the uploaded file.

**Comment by Aymkdn** [comment]
If you need to keep an old version of Sharepoint (like 3.0.4) you can still find the documentation by checking the .js file

For example, for the `createFile` document for v3.0.4 : https://github.com/Aymkdn/SharepointPlus/blob/master/old_versions/sharepointplus-3.0.4.js#L915
