### ISSUE TITLE
Using this in Node environment

### ISSUE THREAD

**Issue by buddythumbs** [Aymkdn/SharepointPlus#43]
Hi,

Is it possible to use this library in a node project?

I am importing the library using require() like the following but get an error when the app loads:
`let $SP = require('../../../public/js/sharepointplus-3.13.min.js')`
```
$SP().list(_LIST,_DATAURL)
      .get({
        fields:"P_NC,P_Ser,P_SO",
        orderby:"P_SO"
      },function(data) {
      let _LISTGROUP = data.map((item) => {
        return {
          'serv': item.getAttribute("P_NC"),
          'ser':item.getAttribute("P_Ser"),
          'so':item.getAttribute("P_SO"),
        }
      })
      this.setState({
        'material':  _LISTGROUP
      })
    });
```

This compiles OK but when the code runs I get:
```
Uncaught TypeError: $SP is not a function
    at Content.componentWillMount (Content.js:21)
    at ReactCompositeComponent.js:348
    at measureLifeCyclePerf (ReactCompositeComponent.js:75)
    at ReactCompositeComponentWrapper.performInitialMount (ReactCompositeComponent.js:347)
    at ReactCompositeComponentWrapper.mountComponent (ReactCompositeComponent.js:258)
    at Object.mountComponent (ReactReconciler.js:46)
    at ReactDOMComponent.mountChildren (ReactMultiChild.js:238)
    at ReactDOMComponent._createInitialChildren (ReactDOMComponent.js:697)
    at ReactDOMComponent.mountComponent (ReactDOMComponent.js:516)
    at Object.mountComponent (ReactReconciler.js:46)
```

I realize this library is client side (which I need) but is there anyone who has successfully integrated the library with ES6 modules?

Thanks in advance

**Comment by Aymkdn** [comment]
As you said, it's a client side library.... so it's not made to work with Node.

In the coming weeks/months I'll experiment Node with Sharepoint, so it's possible that I'll evolve SharepointPlus to work on Node.

**Comment by buddythumbs** [comment]
Hey - I've got this up and running in a kind of hacky fashon:
(I forgot to mention it's a React app I am building so node is just for dev)

I downloaded the nanoajax and sharepointplus libs and stored them in the my project somewhere (public folder)

Then where I needed to import the data I used the following:
```
import '../../../public/js/nanoajax.min'
let $SP = require('../../../public/js/sharepointplus-3.13.min').$SP

loadData() {
    return new Promise((resolve, reject) => {
      $SP().list(_LIST,_DATAURL)
      .get({
        fields:"1, 2, 3, 4, 5",
        where:'1 <> "something"',
        orderby:"1"
      },function(data,error) {
        if(error) {
          reject(error)
        }
        let _LISTGROUP = data.map((item) => {
            return {
              '1': item.getAttribute("1"),
              '2':item.getAttribute("2"),
              '3':item.getAttribute("3"),
              '4':parseInt(item.getAttribute("4"),10),
              '5': item.getAttribute("5")
            }
          })
          resolve(_LISTGROUP)
      })
    })
  }
```

This is working fine in the browser (IE11 only, I get CORS issues in chrome) from a create-react-app setup

**Comment by Aymkdn** [comment]
The v4.0 will be compatible with NodeJS from a server side perspective.
