### ISSUE TITLE
Working with Document Library (Not Lists)

### ISSUE THREAD

**Issue by maldinix** [Aymkdn/SharepointPlus#45]
I need to perform CRUD operations on a Document Library, with sub folders. I'm trying to use the code below to iterate over the Document Library (just as a starting point). Do I need to add or change  anything other than the library name? Does it matter that the site is a subsite? The API works fine for regular Lists. Thank you!

```javascript
$SP().list("DDR").get({fields: "BaseName,FileRef,FSObjType",
folderOptions: {show: "FilesAndFolders_Recursive"}});
```

**Comment by Aymkdn** [comment]
The code is correct. You just need to add the callback:
```javascript
$SP().list("DDR").get({
  fields: "BaseName,FileRef,FSObjType",
  folderOptions:{
    show: "FilesAndFolders_Recursive"
  }
}, function(data) {
  for (var i=0; i<data.length; i++) console.log(data[i].getAttribute("BaseName"))
});
```
You can try this code into the browser console directly to print the result. Also, in the browser web console, you can check what the server returns.


> Does it matter that the site is a subsite?

Yes it matters. If you call `DDR` but it's not in the current website, then it won't be able to find it. So if it's a subsite you need to add the URL of this website:
```javascript
$SP().list("DDR", "http://website.com/site/subsite/").get({
  fields: "BaseName,FileRef,FSObjType",
  folderOptions:{
    show: "FilesAndFolders_Recursive"
  }
}, function(data) {
  for (var i=0; i<data.length; i++) console.log(data[i].getAttribute("BaseName"))
});
```

**Comment by maldinix** [comment]
Thank you!! It's all working now. Now hopefully I can build on this to get my other operations working.
