### ISSUE TITLE
username documentation

### ISSUE THREAD

**Issue by emaV** [Aymkdn/SharepointPlus#46]
It took me one day to realize that the `accountName` parameter for the `$SP().usergroups` function should be formatted as `"i:0#.w|domain\\login"` for Sharepoint 2013 instances and not simply `domain\\login`.

I noticed from checking the [isMember](https://aymkdn.github.io/SharepointPlus/symbols/%24SP%28%29.html#.isMember) function so I guess would be better to update the documentation for all the function that require an username (where not already done as per `isMember` and `getUserInfo`:

* [distributionLists](https://aymkdn.github.io/SharepointPlus/symbols/%24SP%28%29.html#.distributionLists)

* [people](https://aymkdn.github.io/SharepointPlus/symbols/%24SP%28%29.html#.people)

* [usergroups](https://aymkdn.github.io/SharepointPlus/symbols/%24SP%28%29.html#.usergroups)

**Comment by Aymkdn** [comment]
Thanks!

The documentation will be updated for the v4.0 of SharepointPlus that should soon arrive :-)
