### ISSUE TITLE
The value of the property '$SP' is null or undefined, not a Function object

### ISSUE THREAD

**Issue by afripat** [Aymkdn/SharepointPlus#47]
Hi Aymkdn,

I'm very sorry if the following is a newbie question but I can't get sharepointplus working :(
Not even simple function calls are working as I always get the above mentioned error.
I read the documentation, checked your examples as well as the already closed issues.
Do I make any essential error?
I'd be very happy if you could help me!

Code example:
```
<script type="text/javascript" src="https://webapplication/sitecollection/SiteAssets/Scripts/jquery-1.11.1.min.js"></script>
<script type="text/javascript" src="https://webapplication/sitecollection/SiteAssets/Scripts/sharepointplus-3.14.min.js"></script>
<script>
function testSPPlus(){
	try{
		$SP().list("Announcements","https://webapplication/sitecollection/subsite/").get({
			fields:"Title"},function getData(data){
				for (var i=0; i<data.length; i++){
					console.log(data[i].getAttribute("Title"));
				}
			});
	}
	catch(ex){
		alert(ex.message);
	}
}
testSPPlus();
</script>
```

Thanks in advance and best regards,
afripat

**Comment by Aymkdn** [comment]
Can you verify that the content of your `https://webapplication/sitecollection/SiteAssets/Scripts/sharepointplus-3.14.min.js` is correct?

The error you have means the library hasn't been loaded. You can try to replace `https://webapplication/sitecollection/SiteAssets/Scripts/sharepointplus-3.14.min.js` with `https://cdn.jsdelivr.net/sharepointplus/3.14/sharepointplus.min.js` to see if it works better...

**Comment by afripat** [comment]
Thanks for the very fast reply!
I feel pretty stupid because you are actually right and with your provided CDN the function works fine.
Sorry for causing effort and thanks for your help.
