### ISSUE TITLE
dual license / license change

### ISSUE THREAD

**Issue by shahabafshar** [Aymkdn/SharepointPlus#48]
Hi, same guy from twitter @Shahab_Afshar

According to what I've learned about opensource licensing, there are two major movements: 
(1) The permissive movement: BSD / MIT / etc.
(2) The CopyLeft (the restrictive type): **GPL 1/2/3**

(1.5) the LGPL / Apache License / etc. (something in-between)

while the copyleft licensing (GPL) won't allow using your software with non-opensource. Since using your library (GPL) with other software (even at run-time) requires the **whole stack** to be opensource (which is not possible with lots of projects).
Therefore I recommend to change the license to something like **LGPL** which is designed for opensource libraries and allows using them with closed source software, or even better, a dual license such as **MIT/BSD** would be tremendously helpful in using and expanding the lovely $SP (which is the definite means of what __api should have been...)

So this will let people like me use your library in their projects and in SharePoint without worrying about the licensing issues, and still keep it opensource.

So, please please PLEASE give us access to the library with a more permissive license type.

**Comment by Aymkdn** [comment]
Hey,

I spent one hour reading many many websites speaking about the crazy world of licenses.... **LGPL sounds OK**, so if LGPL works for you, I'll change the license to it.

I'm not sure how to deal with this change.... [SharepointPlus v4.0](https://github.com/Aymkdn/SharepointPlus/blob/development-v4.0/changelog.md) should be released in a 2-3 weeks so I think it will give me the opportunity to change the license in the files and into the repository with the v4.0.

Thoughts?

**Comment by shahabafshar** [comment]
I'm so very happy to hear your decision. THANKS A TON! also you don't need to wait for any specific change or release, LGPL is GPL compatible so it does not interfere with your previous releases, you can make it a dual license GPL/LGPL or you can simply change it to LGPL anytime you like.
Once again, thank you for $SP and thank you for "LGPL"ing it!

**Comment by Aymkdn** [comment]
OK, good → https://github.com/Aymkdn/SharepointPlus/blob/master/LICENSE.md

**Comment by shahabafshar** [comment]
WOW PERFECT! I might as well bring some interesting news during the next few month. Your library ROCKS! Please keep up the good work! And THANKS AGAIN!

**Comment by shahabafshar** [comment]
Also you might want to change the licensing info at the bottom of this page too:
https://aymkdn.github.io/SharepointPlus/
it is noted as GPL 2.0 here.
<img width="523" alt="gpl2" src="https://cloud.githubusercontent.com/assets/5617071/25077260/6837e194-233d-11e7-8959-a0feaa386dd5.png">

**Comment by Aymkdn** [comment]
Yes I'll change it with the new release.

**Comment by Aymkdn** [comment]
v4.0 published: https://github.com/Aymkdn/SharepointPlus/releases/tag/v4.0
