### ISSUE TITLE
CheckIn file issue

### ISSUE THREAD

**Issue by hofline** [Aymkdn/SharepointPlus#49]
There is an issue checkin file, refer to line 1751

`var soapEnv = _this._buildBodyForSOAP("CheckInFile", '<pageUrl>'+setup.destination+'</pageUrl><comment>'+setup.comments+'</comment><CheckinType>1</CheckinType></CheckInFile>');`

double tag **CheckInFile**

`<soap:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
	<soap:Body>
		<CheckInFile xmlns="http://schemas.microsoft.com/sharepoint/soap/">
			<pageUrl>https://jpempresas.sharepoint.com/sites/GCT/centroDocumental/Documents/20160509__EvidenciaCttosCargados.xlsx</pageUrl>
			<comment>Nuevo documento</comment>
			<CheckinType>1</CheckinType>
		</CheckInFile>
	</CheckInFile>
</soap:Body>
</soap:Envelope>`

**Comment by Aymkdn** [comment]
Good catch ! I'll fix it in v4.0 that should arrive soon :-)

Thanks

**Comment by Aymkdn** [comment]
v4.0 published: https://github.com/Aymkdn/SharepointPlus/releases/tag/v4.0
