### ISSUE TITLE
async operations

### ISSUE THREAD

**Issue by micuentadecasa** [Aymkdn/SharepointPlus#52]
Hi, I'm trying to make a function that updates some items on a list and I want that the function returns only when all the items have been updated, because $SP().list("xxx").update is async I don't know how to know when all the operations end.

Note: I've seen that I can group the updates and execute an after function but I have other functions where I have add and update operations and I want to know when all the operations end.

Note 2: another problem is if I call my function from another function and I want to wait until all the operations end. I can group the update functions and execute the after function but before the after function is executed the function ends...

` $scope.saveConfigurations= function () {
 for (var i in $scope.configurations) {
if (x) 
 $SP().list("xxx").update({...
else
 $SP().list("xxxx").add({
}
}

 $scope.saveActivities = function () {
$scope.saveConfigurations();
// I want to expect that all operations from saveConfigurations are done
// do the rest of statements...

}

`

any clue?

**Comment by Aymkdn** [comment]
I'm on vacation in another country. I cannot really help for now.

**Comment by buddythumbs** [comment]
I encountered this challenge as well and while I haven't looked at the latest rev of this library, I think my solution may work for you.

```
var UPDATES = $scope.configurations.map(function(x){
  return new Promise(function(ok, reject) {
    if(updateCheck){
      $SP().list("List Name").update({
        ID:43, Title:"Ok"
      }, {
        success:function(items) {
          ok(items)
        }
      });
    }else{
      $SP().list("List Name").add({
        Title:"Ok"
      }, {
        success:function(items) { 
          ok(items); 
        }
      })
    }
  })
})
Promise.all(UPDATES).then(function(data) {
  console.log('ALL UPDATES OK')
})
```
Had to use this for a bunch of calls to and API nested within another call - I needed a babel polyfill for Promises as I was using IE11.

I haven't tested this exact code so might not work but the idea is to map and return a bunch of Promises and use `Promise .all` then to tell when it is all done

**Comment by Aymkdn** [comment]
The last version supports Promise. Also check this link : https://blog.kodono.info/wordpress/2017/04/13/resolve-promise-one-after-another-in-sequence/

**Comment by micuentadecasa** [comment]
Thanks to all. I'm gonna try your solutions and will tell you..

**Comment by micuentadecasa** [comment]
@buddythumbs  excuse me, if there is an error in the update for example, what happens?
if we add the optional error function what will happen?

**Comment by buddythumbs** [comment]
Hey @micuentadecasa, 

Sorry, forgot to put that in there. I would maybe do something like the following:

```
var UPDATES = $scope.configurations.map(function(x){
  return new Promise(function(ok, reject) {
    if(updateCheck){
      $SP().list("List Name").update({
        ID:43, Title:"Ok"
      }, {
        success:function(items) {
          ok(items)
        }, error:function(items){
          reject(items)
        }
      });
    }else{
      $SP().list("List Name").add({
        Title:"Ok"
      }, {
        success:function(items) { 
          ok(items); 
        }, error:function(items){
          reject(items)
        }
      })
    }
  })
})
Promise.all(UPDATES).then(function(data) {
  console.log('ALL UPDATES OK')
}).catch(function(items){
  console.error(items)
})
```

(Verify the syntax on the SP Plus docs for adding both success and error)

**Comment by micuentadecasa** [comment]
Thanks @buddythumbs

**Comment by micuentadecasa** [comment]
Dear all, I have tried with generators also but no luck (it doesn't stop the execution), I think will be a good idea when @Aymkdn  has time to create an article about:
1. present the idea from @buddythumbs 
2. explain when using sharepointplus functions with an array in $SP().list("List Name").update(array - if it is done in the order of the array of it is done async with any item of the array
3. propose a solution to do updates or insert in an order (we can have needs of making inserts in an order).
4. propose a solution to do different operations and not returning until all  is done (and stop the execution of the rest of code until we return from this function).

Note: 
I know this is out of the library, is more a javascript question but I think it is interesting to people using this library.
In addition know that in ES7 javascript there is an **await** that can be used for this but it seems it doesn't work in the actual browsers...

**Comment by Aymkdn** [comment]
> explain when using sharepointplus functions with an array in $SP().list("List Name").update(array) - if it is done in the order of the array of it is done async with any item of the array

It's done in the order you provide the items into the array.

Example of what you can do:
```javascript
var add=[], upd=[];
for (var i=0; i<total; i++) {
  if (MyCriteria === true) add.push({MyField:"something"});
  else upd.push({MyField:"something"})
}
// Once you have finished all your checks,
// you can proceed with the add/update operations into the list
// → Example with SharepointPlus v4.0 and Promises
// → in that case the both operations will be done at the same time
// DISCLAIMER: I didn't test it and the Promises stuff in SharepointPlus is new so it might not work as excepted
Promise.all([
  $SP().list("YourList").add(add),
  $SP().list("YourList").update(upd)
]).then(function() {
  // all add and update operations have been completed
})
// or without Promise and if you want to start with ADD and then with UPDATE you can do:
$SP().list("YourList").add(add, {
  after:function() {
    alert("ADD operations completed");
    $SP().list("YourList").update(upd, {
      after:function() { alert("UPDATE operations completed") }
    })
  }
})
```

Also, if it doesn't answer your question, you need to provide your code and then I should be able to provide a better answer.

**Comment by micuentadecasa** [comment]
It's ok thanks @Aymkdn
