### ISSUE TITLE
Support for Sharepoint 2016

### ISSUE THREAD

**Issue by kims89** [Aymkdn/SharepointPlus#53]
Is it any plans for support on Sharepoint 2016? Or is it supported now?

Thank you.

**Comment by Aymkdn** [comment]
I didn't have access to Sharepoint 2016 so I cannot test it. If the Web services are still available (and I think it's the case), then yes it should work.

**Comment by kims89** [comment]
Awesome fast answar! Thanks :D

9. mai 2017 8.48 p.m. skrev "Aymeric" <notifications@github.com>:

**Comment by danbete** [comment]
I use it often in 2016 Enterprise without any issues..
