### ISSUE TITLE
getAttribute

### ISSUE THREAD

**Issue by RezaErfani67** [Aymkdn/SharepointPlus#54]
hi
i worked with  version 3.0.10...
but recently i make decision to use version 4 
but there is error:
 getAttribute("....")  is undefined...
after change the version to 3.0.10 every thing worked correctly.

**Comment by Aymkdn** [comment]
Can you give more details about your code ??

**Comment by RezaErfani67** [comment]
the problem was here
after receiving data from callback
...
for(var i in data)
{
console.log(data[i].getAttribute("Title"));
}
i should use below syntax to work good.
for(var i=data.length;i--;)
{
console.log(data[i].getAttribute("Title"));
}
i dont know why?!

**Comment by Aymkdn** [comment]
Using `for..in` to iterate over an array is a bad bahevior. It should be avoid.

Here `data` doesn't return just an array. It's an "extended array" and not all the members have a `getAttribute` property.
