### ISSUE TITLE
Checkin issue

### ISSUE THREAD

**Issue by ra6hi9** [Aymkdn/SharepointPlus#55]
Hi,
I am using SharePointPlus v3.14, and I am facing a strange error with the checkin function
I ged allways "Error 'checkin': not able to find the URL!", even if I add url property to setup parameter.
$SP().checkin({url:"http://mySharepointIntranet",
                  destination: "/MyLibrary/Folder/file.ext",
                  comments:"Automatic check in",
                  after:function() {}
                })

Thanks

**Comment by Aymkdn** [comment]
That is probably related to this issue: https://github.com/Aymkdn/SharepointPlus/issues/49

**Comment by ra6hi9** [comment]
OK, thank you.
Can I switch to v4.0 without risk for my code upon v3.14?

**Comment by Aymkdn** [comment]
Yes, you shouldn't have any issues by using v4.0!

**Comment by ra6hi9** [comment]
thanks
