### ISSUE TITLE
No AJAX library has been found

### ISSUE THREAD

**Issue by martin0852** [Aymkdn/SharepointPlus#56]
Hey,

I am trying to implement this in node.

Using ES6 imports I am getting the following error:

![image](https://cloud.githubusercontent.com/assets/12892509/26515996/5dc1d65c-4278-11e7-985f-af96c93968c0.png)

```
import $ from 'jquery';
import nanoajax from 'nanoajax'
import {$SP} from 'sharepointplus'
```

As you can see in the image I have both nanaoajax and jquery loaded.

Can you provide an example of how you use jquery/nanoajax in the ES6 syntax?

Thanks!

**Comment by Aymkdn** [comment]
When using Node on the server side, you don't need jQuery or nanoajax.

Here you use it in the browser, so you have to expose `jQuery` as a function, or `nanoajax` as a function.  See https://github.com/Aymkdn/SharepointPlus/blob/master/sharepointplus-4.0.js#L259

I'm not familiar enough with ES6 imports to know the correct syntax, so feel free to share here what you found.

Thanks

**Comment by martin0852** [comment]
Hey- fix was to add the jQuery and $ to the window:
```
import * as jQuery from 'jquery';
window.jQuery = jQuery
window.$ = jQuery
```

Now it all works!
