### ISSUE TITLE
calendar - only got current month

### ISSUE THREAD

**Issue by micuentadecasa** [Aymkdn/SharepointPlus#58]
Hi, I'm trying to get the events from a calendar list using next code:
` $SP().list("Calendar").get({
                                                        fields:"Description",
                                                        calendar:true,
                                                    }, function(data) {`

and I only got events on current month or five days difference from current month, any clue?

**Comment by micuentadecasa** [comment]
I've found the option "range" but still not getting the old or former values

**Comment by Aymkdn** [comment]
You have to provide the `referenceDate`. See the documentation.

**Comment by micuentadecasa** [comment]
Thanks @Aymkdn 

I've found the solution using the "range" option

 $scope.panel5_getCalendarDataFromSharepoint = function ( ) {
                                                    $SP().list("Calendar").get({
                                                        fields:"Description",
                                                        calendar:true,
                                                        calendarOptions: {
                                                            range:"Year"
                                                        }
                                                    }, function(data) {

**Comment by Aymkdn** [comment]
I don't think it's a good idea to use `Year`. If you refer to the [link provided](https://www.nothingbutsharepoint.com/sites/eusp/Pages/Use-SPServices-to-Get-Recurring-Events-as-Distinct-Items.aspx) in the documentation, it says:

> &lt;Year />
> This is supposed to get all events within:
> (a) Today’s year (if no CalendarDate is passed), or
> (b) the date passed in QueryOptions as CalendarDate.
>          
> Actually, it returns all dates from [Today] into the future. It ignores:
> (a) the CalendarDate, and
> (b) the end of the current year

If you just try to get a list of items you don't need the calendar option and you could try:
```javascript
$SP().list("Calendar").get({
  fields:"Description",
  where:"EventDate > '2017-01-01' AND EndDate < '2018-01-01'"
}, function(data) {})
```

**Comment by micuentadecasa** [comment]
thanks @Aymkdn , in other site I have to use fiscal years (from July to July) so is very helpful your code.
