### ISSUE TITLE
how to deal with dates?

### ISSUE THREAD

**Issue by micuentadecasa** [Aymkdn/SharepointPlus#60]
Hi, I'm dealing with dates in SharepointPlus, if I got a valid date from Sharepoint I can use your functions but if I have an empty date I can not use your functions because:

- $SP().toDate(null) return "", that's ok
but - $SP().toSPDate("") gives error so I can not use it for null values in an add function. for example:

```javascript
$SP().list("ASE_Tasks").update({
            ID: obj.ID,
            Title: obj.Title,
             Start: $SP().toSPDate(obj.Start) ,
             End: $SP().toSPDate(obj.End),
```

**Comment by Aymkdn** [comment]
You can test it on your side:
```javascript
$SP().list("ASE_Tasks").update({
  ID: obj.ID,
  Title: obj.Title,
  Start: (obj.Start?$SP().toSPDate(obj.Start):""),
  End: (obj.End?$SP().toSPDate(obj.End):obj.End),

**Comment by micuentadecasa** [comment]
nice and clean, it works like a charm, thanks @Aymkdn
