### ISSUE TITLE
Q: Is this using the SOAP services or the JSON REST API?

### ISSUE THREAD

**Issue by AndersGerner** [Aymkdn/SharepointPlus#61]
Hi @Aymkdn, I would like to know if this is using the old SOAP services, and then converts it to an array, or is it using the REST API and getting JSON data?

Thanks in advance for response.

**Comment by Aymkdn** [comment]
It uses SOAP to make it compatible with older versions of Sharepoint and because SOAP is still the solution that provides the more functionalities.
