### ISSUE TITLE
SP().formfields().each() is not returning all fields.

### ISSUE THREAD

**Issue by mikeecuffe** [Aymkdn/SharepointPlus#63]
I created a CustomEditForm.aspx in SP Designer and set it as the default for my list then I added a CEWP webpart to the page that points to the below html that loads the required scripts. 
On ready() is called when I edit a list item - I see the page fully load and the alert box informs me I'm using version 4.0 of your library.

The problem is when it gets to the loop. The only field returned (the array length is 0) is attachment but there are three others fields being omitted - two fields unique to the list and the site column 'Title'; Title and another field have existing values.

Not sure what I am doing wrong but its not returning any values.

- Sharepoint 2010.
- Sharepointplus version: 4.0, 3.14
- Chrome Version 58.0.3029.81 (64-bit)
HTML SCRIPT LOADER IN CEWP.
```
<script type="text/javascript" src="https://cdn.jsdelivr.net/g/sharepointplus@4.0(sharepointplus.min.js+nanoajax.min.js)"></script>
<script type="text/javascript" src="*OMITTED*/SiteAssets/voucherEditForm.js"></script>
```
JAVASCRIPT BEING CALLED
```
$(document).ready(function() {
	alert("SP version : " + $SP().getVersion() );
	 $SP().formfields().each(function() {
	  console.log(this.name()); // -> return the name of the field
	  console.log(this.isMandatory()); // -> returns TRUE if it's a mandatory field
	})
});
```

**Comment by Aymkdn** [comment]
`$SP().formfields()` is used for the default forms of Sharepoint. If you create your own form, then probably that the HTML code is not the same as the default forms, so the library is not able to retrieve the fields into the page.
Example of the default HTML code produced by Sharepoint:
```html
<table class="ms-formtable" style="margin-top: 8px;" width="100%" cellspacing="0" cellpadding="0" border="0">
  <tbody>
    <tr>
      <td class="ms-formlabel" width="190px" valign="top" nowrap="true">
        <h3 class="ms-standardheader">
          <nobr>Action<span class="ms-formvalidation" title="This is a required field."> *</span></nobr>
        </h3>
      </td>
      <td class="ms-formbody" valign="top">
      <!-- FieldName="Action"
         FieldInternalName="Action"
         FieldType="SPFieldLookup"
        -->
        <span dir="none">
          <select name="ctl00$m$g_209dfb79_2e48_4e2b_b875_cf6cc7c8a5b0$ctl00$ctl05$ctl00$ctl00$ctl00$ctl04$ctl00$Lookup" id="ctl00_m_g_209dfb79_2e48_4e2b_b875_cf6cc7c8a5b0_ctl00_ctl05_ctl00_ctl00_ctl00_ctl04_ctl00_Lookup" title="Action Required Field">
            <option value="10">Business Support</option>
            <option value="5">Content</option>
            <option value="1">Delivering</option>
            <option value="3">Learning</option>
          </select>
          <br>
        </span>
        Description of the field
      </td>
    </tr>
  </tbody>
</table>
```

**Comment by mikeecuffe** [comment]
resolved!
Do you think its possible to make this more resilient, or is it a sharepoint pain? I haven't looked at the problem/code but I used to develop for the jpoint (sharejpoint) team with will lawrence years ago and might be able to help.

**Comment by Aymkdn** [comment]
The `formfields()` part of SharepointPlus is going to become a plugin (see [v5.0 announcement](https://github.com/Aymkdn/SharepointPlus/wiki/SharepointPlus-5.0-Announcement)). Its purpose is only to deal with the regular Sharepoint forms.

If you create your own form, it might be impossible to predict your HTML code. So, no, I don't think it will be possible to make it more resilient.
