### ISSUE TITLE
List get ignoring time in second WHERE clause

### ISSUE THREAD

**Issue by dutchstiphout** [Aymkdn/SharepointPlus#64]
Using SharePoint 2007

I have a list of appointments, and I'm using $SP().lists('appointments').get to select appointments for display over a date range. My WHERE clause looks like this:

`"Date >= '" + $SP().toSPDate(dateTimeRange[0], true) + "' AND " +`
`"Date <  '" + $SP().toSPDate(dateTimeRange[1], true) + "'",   //SP ignores time in this clause...`

The problem is that I'm only getting results up to 23:59.999 on the day prior to dateTimeRange[1]. If I replace the second call to toSPDate to `$SP().toSPDate(dateTimeRange[1])` (i.e., remove the `, true`), then I get exactly the same behavior.

**Comment by Aymkdn** [comment]
How looks like the XML created by SharepointPlus and sent to the server? You can see it into the web console of your browser. Please psste it here. 

Also, is your list a Calendar list? If yes, try to use the calendar options of `.get()` because the way Sharepoint deals with dates fields might be unexcepted.

**Comment by dutchstiphout** [comment]
`<soap:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
	<soap:Body>
		<GetListItems xmlns="http://schemas.microsoft.com/sharepoint/soap/">
			<listName>appointments</listName>
			<viewName></viewName>
			<query>
				<Query>
					<Where>
						<And>
							<Geq><FieldRef Name="Date" /><Value Type="DateTime" IncludeTimeValue="TRUE">2017-07-30 13:00:00</Value></Geq>
							<Lt><FieldRef Name="Date" /><Value Type="DateTime" IncludeTimeValue="TRUE">2017-08-01 04:00:00</Value></Lt>
						</And>
					</Where>
					<OrderBy>
						<FieldRef Name="Date" Ascending="true" />
						<FieldRef Name="Chair" Ascending="true" />
					</OrderBy>
				</Query>
			</query>
			<viewFields>
				<ViewFields Properties='True'>
					<FieldRef Name="ID" /><FieldRef Name="Barber" />
					<FieldRef Name="Customer" />
					<FieldRef Name="Date" />
					<FieldRef Name="Chair" />
				</ViewFields>
			</viewFields>
			<rowLimit>0</rowLimit>
			<queryOptions>
				<QueryOptions>
					<DateInUtc>False</DateInUtc>
					<Paging ListItemCollectionPositionNext=""></Paging>
					<IncludeAttachmentUrls>True</IncludeAttachmentUrls>
					<IncludeMandatoryColumns>False</IncludeMandatoryColumns>
					<ExpandUserField>False</ExpandUserField>
					<ViewAttributes Scope="Recursive"></ViewAttributes>
				</QueryOptions>
			</queryOptions>
		</GetListItems>
	</soap:Body>
</soap:Envelope>`

**Comment by dutchstiphout** [comment]
I just did some additional testing, and I made a bad assumption -- looks like it's ignoring the time on **both** Date clauses.

**Comment by dutchstiphout** [comment]
I'm seeing the same problem in `$SP().list("appointmenteditlog").remove` where it's ignoring the time.

**Comment by dutchstiphout** [comment]
Found the problem. Change the return statement in your toSPDate function from this:

`return year+"-"+month+"-"+day+(includeTime?" "+hours+":"+minutes+":"+seconds : "");`

to this:

`return year+"-"+month+"-"+day+(includeTime?"T"+hours+":"+minutes+":"+seconds : "");`

**Comment by Aymkdn** [comment]
OK, good to know. I'll do some tests on Monday. Thanks for reporting back!

**Comment by Aymkdn** [comment]
You're right! It will be fixed in v5.0.

Thanks again 👍

**Comment by Aymkdn** [comment]
Fixed in v5.0 → https://github.com/Aymkdn/SharepointPlus/releases/tag/v5.0
