### ISSUE TITLE
SP().list().update() - updating a choice field over web service.

### ISSUE THREAD

**Issue by mikeecuffe** [Aymkdn/SharepointPlus#65]
I'm attempting to update a choice field ("Certification_x0020_Status")  in a list ("List") using web services but the result is not as expected. 

If this is possible, what is the correct way to format the request so that SharePoint recognizes the value in the choice field?

**Code:**
```javascript
$SP().list("List").update({
  [_args.childFieldA] : $SP().formfields(_args.parentFieldA).val(), 
  ["Certification_x0020_Status"] : ["2. Requesting Exam Voucher"] },
  {where: _args.internalNameFieldFK +" = '"+ candidate +"'"}).then(function(res) { //blah});
```

**Result:**
AllItems.aspx :  ;#2. Requesting Exam Voucher;#
ViewItem.aspx : 2. Requesting Exam Voucher
EditItem.aspx : invalid - returns to default Choice.

**Comment by Aymkdn** [comment]
Why do you put `[]` around the field ID ?

For the type, if it's not a multi-selection Choice field, then just put the value as a string.

It should be:
```javascript
$SP().list("List").update({
  "Certification_x0020_Status": "2. Requesting Exam Voucher"
},
  {
   where: _args.internalNameFieldFK +" = '"+ candidate +"'"
  }
).then(function(res) { //blah});
```

With `"2. Requesting Exam Voucher"` that must exactly match the value from the dropdown selection.

**Comment by mikeecuffe** [comment]
Resolved! and again I find myself greatly appreciating the fast and accurate response.
I was initially using variables on the key & value - this is why there are [] around the key - to evaluate it before parsing.
I don't know why it didn't work for me - I'm putting it down to this head cold but either way super appreciate your assistance.
