### ISSUE TITLE
Paging with listItemCollectionPositionNext

### ISSUE THREAD

**Issue by ramonck** [Aymkdn/SharepointPlus#67]
Hi,

I'm trying to do the pagination feature in your library but what I want to for example to bring only the next 10 rows, it's bringing 20 instead of just the next 10.

`$SP().list('Pages', '/home/news/').get({fields:"Title,Content", rowlimit:10, paging:true, page:2, listitemcollectionpositionnext: 10},function(data) {
  for (var i=data.length; i--;) {
console.log(data[i].getAttribute("Title"));
}
});`

**Comment by Aymkdn** [comment]
Look at the example into the documentation : 
```javascript 
// use `listItemCollectionPositionNext` to start from this index
$SP().list("My List").get({fields:"ID",orderby:"ID DESC",rowlimit:10,paging:true,page:1}, function(data) {
  // get the next block
  this.get{fields:"ID",orderby:"ID DESC",rowlimit:10,paging:true,page:1,listItemCollectionPositionNext:data.NextPage}, function(data) {
    // here we have the 2nd block of data into `data`
  })
})
```

So `page` must be 1.
And you'll need : `listItemCollectionPositionNext:data.NextPage`

**Comment by ramonck** [comment]
Thanks, works great.

Thank you for the great work on this library.
