### ISSUE TITLE
delete list item attachments

### ISSUE THREAD

**Issue by RezaErfani67** [Aymkdn/SharepointPlus#68]
hi
thanks a lot for this...
is there any function for remove list item attachments?

**Comment by Aymkdn** [comment]
There is no direct function to do it. However you could use [`$SP().webService()`](https://aymkdn.github.io/SharepointPlus/core.html#webService)

Using the info from this [stakeoverflow post](https://sharepoint.stackexchange.com/questions/137752/how-to-delete-list-attachments-using-javascript) and using the [`DeleteAttachment`](https://msdn.microsoft.com/en-us/library/websvclists.lists.deleteattachment.aspx) you could try something like:
```javascript
$SP().webService({
  service:"Lists",
  operation:"DeleteAttachment",
  properties:{
    listName:"Test",
    listItemID:"Item_ID",
    url:"http://Server_Name/Site_Name/Lists/List_Name/Attachments/Item_ID/FileName"
  }
})
```

**Comment by RezaErfani67** [comment]
on sharepoint 2010 with shrepointplus-4.0.min.js,with above code, page remain on hang (1- continue script  2-Stop Script)...

but below code that exist in stackexchange work correctly...
$().SPServices({
    operation: "DeleteAttachment",
    listName: "List Name",
    listItemID: itemId, //list item id
    url: filePath, //url of attachment that needs to be deleted
    completefunc: function (xData, Status) {
        console.log('Deleted');
    }
});

**Comment by Aymkdn** [comment]
You copied the code for SPServices... not for SharepointPlus...

**Comment by RezaErfani67** [comment]
thanks :)
