### ISSUE TITLE
Where clause with People Field

### ISSUE THREAD

**Issue by ramonck** [Aymkdn/SharepointPlus#69]
Hi,

I wanted to do a query with People field but unfortunatly I don't know how to do it, it doesn't work. Please help :).

```javascript 
$SP().whoami({url:"http://thesite/"}, function(people) {
  $SP().getUserInfo(people["AccountName"],{url:"http://thesite/"}, function(info) {
    if (typeof info === "string") {
      alert("Error:"+info); // there was a problem so we show it
    } else {
      $SP().list('banco_dados_nn').get({fields:"Title", where:"PeopleField='"+info.ID+"'", rowlimit:10},function(data) {
      console.log(data.length);
      for (var i=data.length; i--;) {
    console.log(data[i].getAttribute("Title"));
    }
    });
    }
  });
});
```

**Comment by Aymkdn** [comment]
If you query using the user ID you must use a special character as described here : https://aymkdn.github.io/SharepointPlus/lists.html#parse

So your Where clause must be : `where:"PeopleField ~= "+info.ID` (and don't user quotes around the ID).

**Comment by ramonck** [comment]
Can I use domain\lanid ?

**Comment by Aymkdn** [comment]
> Can I use domain\lanid ?

It depends... If your list may have more than 5,000 items then no, you'll have to use the ID with `~=` (and to index the column).

If it's not the case, then it accepts the current format used to show the field:
![capture](https://user-images.githubusercontent.com/946315/29714178-40cf7916-89a2-11e7-9126-d5e9f2a94db8.png)

For example, if you select `User name` for this field, then you could do `where:'PeopleField = "lanid"'`

A workaround could be to create a "hidden" field that will be set by a workflow in the background to the username of the user.
For example you have field `PeopleField` that shows `Name`, and you create a `PeopleFieldShadowCopy` field as a Text that is the username of the `PeopleField` and that is set by a workflow.
Then you could do `where:'PeopleFieldShadow = "domain\lanid"'`.
