### ISSUE TITLE
Problem with document set

### ISSUE THREAD

**Issue by micuentadecasa** [Aymkdn/SharepointPlus#70]
When trying to use .update function with an item in a document set It gives me a 500 error

**Comment by Aymkdn** [comment]
Can you share some code? As well as the response body related to the error 500.

**Comment by Aymkdn** [comment]
No updates after 5 days.

**Comment by micuentadecasa** [comment]
Sorry I was travelling. At last was a problem with my code. Thanks @Aymkdn
