### ISSUE TITLE
Outer join with a column type number

### ISSUE THREAD

**Issue by juanglogic** [Aymkdn/SharepointPlus#71]
Hi, I'm trying to do a outerjoin between two lists, the second list have a column(EgNumber) like a number but when that returns, the column appears with decimals, for that reason (or I belive) the join can't show the B list eg: list A (ID) - list B(EgNumber)
ID = 34
EgNumber = 34.0000000
````Javascript
outerjoin: {
  list:'B',
  on: "'A'.ID = 'B'.EgNumber"
}
````
Exists any solution for that, without change the list configuration?

**Comment by Aymkdn** [comment]
The only solution is to change your column to be a "Single line of text", and then it will work.

If you cannot/don't want to chante your "EgNumber" field, you could create a new (hidden) field with the type "Single line of text" that a Workflow will fill in each time you update an item, copying the value of "EgNumber" into this hidden field. Then the `outerjoin` will be done on this field.
