### ISSUE TITLE
XML Parse error

### ISSUE THREAD

**Issue by Masanix** [Aymkdn/SharepointPlus#72]
Hello,

I am using sharepointplus regularly and I found it **really great**.

Trying to read a list I receive this 

> XML Parse error

**_Sharepoint 2013_** and **_Sharepointplus 4.0_**

Please could you check it?

Thanks in advance for your collaboration

Err received:
-------------------------------------
Error: Invalid XML: <?xml version="1.0" encoding="utf-8"?><soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema"><soap:Body><GetListItemsResponse xmlns="http://schemas.microsoft.com/sharepoint/soap/"><GetListItemsResult><listitems xmlns:s='uuid:BDC6E3F0-6DA3-11d1-A2A3-00AA00C14882'
     xmlns:dt='uuid:C2F41010-65B3-11d1-A29F-00AA00C14882'
     xmlns:rs='urn:schemas-microsoft-com:rowset'
     xmlns:z='#RowsetSchema'>
<rs:data ItemCount="177">
   <z:row ows_Title='APPEAR E2E Data Management' ows_UP3P_x0020_Reference='NA' ows_Project_x0020_Type='Project' ows_Lifecycle='Agile-Scrum' ows_Project_x0020_Status='Closed' ows_Project_x0020_Manager='Herzog, Lars'  .......

**Comment by Aymkdn** [comment]
Check the full answer from the server (the one you have pasted is incomplete). There is probably a text field where someone entered a weird/incorrect character that is not supported by XML. It's usually quite easy to find by just looking at what the server returned.

Once you found it, you can edit the item and remove the odd character.

**Comment by Masanix** [comment]
Hello,

Thanks for your help.
I'm looking for the incorrect character but restraining the input fields the problem has been corrected.

Merci beaucoup ;)
