### ISSUE TITLE
Error in code examples

### ISSUE THREAD

**Issue by ScotBoy** [Aymkdn/SharepointPlus#74]
In the 'Methods' section of the documentation, within the 'get' method, there are some examples that contain an extra bracket.  See below.

```javascript
// the WHERE clause must be SQL-like
// the field names must be the internal names used by Sharepoint
// ATTENTION - note that here we open the WHERE string with simple quotes (') and that should be your default behavior each time you use WHERE
var name = "O'Sullivan, James";
$SP().list("My List").get({
  fields:"Title",
  where:'Fiscal_x0020_Week > 30 AND Fiscal_x0020_Week < 50 AND Name = "'+name+'"'
```}),function getData(row) {```
  for (var i=row.length;i--;) console.log(row[i].getAttribute("Title"));
});

// Same example but this time we write the name directly inside the query...
// So make sure to use a single backslash (\) if you have a simple quote ' inside your WHERE with a double quotes (") to open/close the string
$SP().list("My List").get({
  fields:"Title",
  where:'Fiscal_x0020_Week > 30 AND Fiscal_x0020_Week < 50 AND Name = "O\'Sullivan, James"'
```}),function getData(row) {```
  for (var i=row.length;i--;) console.log(row[i].getAttribute("Title"));
});
// Or to use a double backslash (\\) if you have a simple quote ' inside your WHERE with a simple quote (') to open/close the string
$SP().list("My List").get({
  fields:"Title",
  where:"Fiscal_x0020_Week > 30 AND Fiscal_x0020_Week < 50 AND Name = 'O\\'Sullivan, James'"
```}),function getData(row) {```
  for (var i=row.length;i--;) console.log(row[i].getAttribute("Title"));
});
```

**Comment by Aymkdn** [comment]
Thanks!

Actually all these examples will change with [the v5 that is coming very soon](https://github.com/Aymkdn/SharepointPlus/wiki/SharepointPlus-5.0-Announcement) :-)

**Comment by ScotBoy** [comment]
I am just about to use your library to programatically interact with Sharepoint discussion lists (including threaded discussions).  They are not your standard lists and I have not been able to get SPServices to work with them, hence looking at your library.  Are you looking to better support discussion list interaction in V5 and is it easy/possible to read and post threaded discussion in the current version?  I can't find any examples of discussion list implementations of your library.

**Comment by Aymkdn** [comment]
I've never worked with discussions thread, however I wanted to look at it during the coming days! So, the v5 may include the support for discussions. I can let you know more in a couple of days.

I need to dig into it ([this looks like a good start](https://social.msdn.microsoft.com/Forums/en-US/da1c48aa-b54e-41af-9f2f-08cc35c8ee05/sharepoint-site-discussion-board-using-soaprest-webservice?forum=sharepointdevelopmentprevious))

**Comment by Aymkdn** [comment]
@ScotBoy so yes, I can now confirm v5 will support Discussion Board. I've already created the document to use with the v5: https://github.com/Aymkdn/SharepointPlus/wiki/Sharepoint-Discussion-Board
