### ISSUE TITLE
Nodejs For Sharepoint 2010

### ISSUE THREAD

**Issue by RezaErfani67** [Aymkdn/SharepointPlus#76]
when i send request to sharepoint 2010 from nodejs, the code return empty array...
```javascript
const credentials = {
    username:'test',
    password:'test',
    domain:'local.com'
};
// you can also define a proxy
const proxyweb = "http://" + credentials.domain + "%5C" + credentials.username + ":" + credentials.password + "@proxy:80";

const $SP = require('sharepointplus');

const sp = $SP().proxy(proxyweb).auth(credentials);

sp.list("ProductRequest","http://spserver/").get({fields:"ID",where:"ID<3000"},function(data){
    console.log(data);//------
});
```

**Comment by Aymkdn** [comment]
Try a couple of things:

1) try:
```javascript
sp.list("ProductRequest","http://spserver/").info(function(fields) {
  for (var i=0; i<fields.length; i++) console.log(fields[i]["DisplayName"]+ ": "+fields[i]["Description"]);
});
```

To verify SharepointPlus is able to connect and get data from your Sharepoint list.

2) If it works, try your `get()` into the browser to see the data returned by Sharepoint and see if your where clause and other stuff are OK.

Also, I'm about to push version 5.0 of SharepointPlus in a couple of minutes :-)

**Comment by RezaErfani67** [comment]
tanks alot  for version 5 of sharepointplus.
i install it and try agian with your code but not return anything...
`
const $SP = require('sharepointplus');
var user1 = {username:'test', password:'test', domain:'local.com'};
var sp = $SP().auth(user1);
sp.list("ProductRequest","http://spserver/").info(function(fields) {
    for (var i=0; i<fields.length; i++) 
console.log(fields[i]["DisplayName"]+ ": "+fields[i]["Description"]);
});
`

**Comment by RezaErfani67** [comment]
i found response...
you can use this code

```javascript
const $SP = require('sharepointplus');
var user1 = {
    username: "test",
    password: "test",
    domain: "local.com"
};
var sp = $SP().auth(user1);
sp.list("ProductRequest","http://spserver/")
.get({fields:"ID",page:1,paging:true,rowlimit:1})
.then((data) => {
    console.log(data[0].getAttribute("ID"));
}).catch((err) => {
    console.log('errored');
});
```
