### ISSUE TITLE
Provide separate versions for sever side and client side.

### ISSUE THREAD

**Issue by Dragnucs** [Aymkdn/SharepointPlus#79]
Having the same package to run for both server side and browser can be problematic in some cases. For example, when trying to require $SP when using webpack causes the build fails because it cannot load some NodeJS modules.

Probably maintaining two separate package can be a burden. I ask you then if it possible to surpass such issue while still having only one package.

**Comment by Aymkdn** [comment]
I don't use Node for client side, only for server side (for example to automate some scripts). I don't even know how to use it on client site like that.... For browsers I just call it into my HTML page served by Sharepoint. 

So no I don't have the skills to help you here.... But I'm open to suggestions.

**Comment by Dragnucs** [comment]
One does not use Node for client site. However, node does power [webpack](https://webpack.js.org/) which is a tool to bundle scripts. Those script are then used as regular ones served by SharePoint.

The thing is, when webpack finds the `require('sp-request')`, a pure Node module, it tries to load the following dependencies:

* child_process
* dns
* fs
* net
* readline
* tls

These cannot be part of a browser module and even installing them would not solve the problem. As a work around, I just remove the chunk of code requiring sp-request and everything works.

**Comment by Dragnucs** [comment]
The proper solution was to use Webpack [IgnorePlugin](https://webpack.js.org/plugins/ignore-plugin/). No changes to $SP were required. However, module `sp-request` could be set as an optional dependency.
