### ISSUE TITLE
security  documentation

### ISSUE THREAD

**Issue by micuentadecasa** [Aymkdn/SharepointPlus#80]
Hi, I would like to know if there is documentation about security, do you use Oauth? how do you authenticate the user?, I suppose that if a user doesn't have permissions on a list, can call an insert function but it will be denied; but I want to know the method used to accomplish it.

**Comment by Aymkdn** [comment]
If you use SharepointPlus into the browser, then everything is handled by the browser itself, just like if you navigate to a Sharepoint page. Nothing is done in the SharepointPlus code.

If you use SharepointPlus on a server side with NodeJS, then you need to authenticate (based on https://github.com/s-KaiNet/node-sp-auth).

**Comment by micuentadecasa** [comment]
Thanks @Aymkdn .
