### ISSUE TITLE
How to contributing

### ISSUE THREAD

**Issue by Dragnucs** [Aymkdn/SharepointPlus#81]
Hello,

I am willing to contribute a few things, like improved support for webpack and probably node too. However, I find it a bit difficult to edit the file especially since it has +5000 lines of code. I assume you are using a particular setup to compile/bundle the file.

Can you please clarify the setup, or the lack of it, to get me started?

**Comment by Aymkdn** [comment]
Actually no, I don't use a setup to compile/bundle the file. I started SharepointPlus many (many) years ago, and at that time it wasn't really a thing to use bundles.

Also it has always been created for using it into a browser. My move to Node is quite recent and mainly to automate some scripts (like exporting data from Sharepoint)....

The code is (I think) well documented and I have no current plan to split it in pieces.

In my job I work alone, and I've developed SharepointPlus alone too.

If you can propose a setup that makes sense, and easy to use, then why not. I just want to make sure we'll keep the size as small as possible (webpacks/bundles are good to develop and read the code, but often the end file is much bigger than expected).
I'm still learning :-)

(Je viens de regarder ton profile et j'ai l'impression que tu es/parles français aussi ?)

**Comment by Dragnucs** [comment]
Oui, je parle français aussi.

Regarding webpack, the raw files and development files maybe bigger indeed, but the final production file is extremely light. Minification is done using the regular libraries with optimized settings.

The advantage of using webpack or similar is that you can just require nanoajax and other dependecies in your main file and voila you dont need to bloat it. Just like other languages: using for C# and import for Python.

However, I am going to provide small changes little by little.

I am still learning too.

**Comment by Aymkdn** [comment]
> you can just require nanoajax
This is not a dependency anymore. I've integrated and changed its code to fit with my needs. So I cannot relay on the current nanoajax version anymore.

There is no more dependencies (except for promise polyfill for IE11).

But OK, sounds good. Feel free to try something and share with me!

Thank you :-)
