### ISSUE TITLE
list.history() parameters

### ISSUE THREAD

**Issue by 5eleven7** [Aymkdn/SharepointPlus#83]
Using SharePointPlus v5, SP2013

I am able to get back the history of a single column for one item no problem. Is it possible to pass an array of columns, or return all columns changed on the last version?

Thanks

**Comment by Aymkdn** [comment]
Nope, as described by the documentation, it's one field by one field. The Sharepoint webservice only supports one field!

The other possibility is to parse the `versions.aspx` page as explained here : https://stackoverflow.com/questions/24423657/sharepoint-2013-get-splistitem-versions-via-rest
