### ISSUE TITLE
copy list item attachments and delete it

### ISSUE THREAD

**Issue by RezaErfani67** [Aymkdn/SharepointPlus#88]
i use bellow code  to remove attachments that use SPService library
``` javascript
    $().SPServices({
        operation: "DeleteAttachment",
        listName: "test",
        listItemID: 3717, 
        url: "r/Lists/test/Attachments/3717/ProductFlow.vsdx",  //url of attachment that needs to be deleted
        completefunc: function (xData, Status) {
            console.log('Deleted');
        }
    });

```
how can i  copy attachments on shared folder and delete it after that?(with SharepointPlus 5.0 not SPService)

**Comment by Aymkdn** [comment]
Are you asking for the equivalent code for `$().SPServices({operation: "DeleteAttachment", [...]})` with SharepointPlus, or are you asking for the code to `how can i copy attachments on shared folder and delete it after that?` ?

In the first case, you can use [webService](https://aymkdn.github.io/SharepointPlus/core.html#webService).

In the second case, I won't give you the whole code, but I can give you some tips : 

1. Use [.get](https://aymkdn.github.io/SharepointPlus/lists.html#get) to find items with an attachment into your list
2. What is your shared folder? A share drive on a computer, or a Sharepoint document library?
    * If it's a share drive, then you'll have to use [SharepointPlus with Node](https://aymkdn.github.io/SharepointPlus/node.html#auth) on the computer, and download the file using [.ajax()](https://aymkdn.github.io/SharepointPlus/utils.html#ajax) as an `ArrayBuffer` (see the second example), and finally use [fs](https://nodejs.org/api/fs.html) (or whatever you want) to pass this `ArrayBuffer` as a file to the share drive
    * In the second case, you can use [.ajax()](https://aymkdn.github.io/SharepointPlus/utils.html#ajax) to get the `ArrayBuffer` of the file, then use [.createFile()](https://aymkdn.github.io/SharepointPlus/files.html#createFile) with the `ArrayBuffer` to create the file into the destination Sharepoint doc library
3. You can delete the attachment using [webService](https://aymkdn.github.io/SharepointPlus/core.html#webService)

**Comment by RezaErfani67** [comment]
Perfect...
