### ISSUE TITLE
update list item not work correctly

### ISSUE THREAD

**Issue by RezaErfani67** [Aymkdn/SharepointPlus#91]
with version 4 work correctly but with version 5 in node js return failed..
![image](https://user-images.githubusercontent.com/24381986/34912935-c9f3e53a-f903-11e7-9e8f-d4126cbd1021.png)

**Comment by Aymkdn** [comment]
I've just tried here, and it passed all my tests.

Try to do your request with a `.get()` and see which IDs are returned.

The `update()` with WHERE is just a `.get()` followed by an update using the IDs found from the `get()`

**Comment by RezaErfani67** [comment]
.get() work fine because it finds 2 item as you can see ... but final update has been canceled...
after some hours testing i noticed it work fine by replacing 
javascript
```
_SP
```
by 
javascript
```
var _sp = $SP().auth(user1);
$SP().auth(user1)
```


why?

**Comment by Aymkdn** [comment]
Both expressions are supposed to do the same...

I believe something is not correct somewhere into your code.

**Comment by RezaErfani67** [comment]
this problem is related to `.update()` ...
`.get()`  is OK every where...

**Comment by Aymkdn** [comment]
As I said, for me, my code is not the problem here. All my tests show that it does work....

```javascript
const credentials = require('../credentials');
const $SP = require('sharepointplus');
const sp = $SP().auth(credentials);

sp.list("SharepointPlus","https://my.website.com/site/")
.update({Title:"Update 2"}, {where:'Title = "Update OK"'})
.then(res => {
  console.log(res);
/* Results:
   [ { Title: 'Update 2', ID: '59', raw: [Object] },
     { Title: 'Update 2', ID: '58', raw: [Object] },
     { Title: 'Update 2', ID: '39', raw: [Object] } ],
  failed: [] } 
*/
})
```

So I cannot do anything more here... Except if you're able to isolate the exact issue.
