### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by Ileouleyuki** [Aymkdn/SharepointPlus#92]
Hye,
I try to use your library on Firefox 52.3.0 (32 bits) and i have an error : 
<code>TypeError: data.getElementsByTagName is not a function   sharepointplus-5.0.js:498:30 </code>in the debug console when i try to test this code for listing all items of a lists 

Here is my code 

<code>
$SP().list("Contacts","http://shp.itn.ftgroup/entite/lists/test/").get().then(function(data) {
    console.log(data);
});
</code>

I have access at the list 

Thanks for ypur help

Jules

**Comment by Ileouleyuki** [comment]
Oh,
I don't use NodeJS, i just want to use it from the client side and my application use jQuery

**Comment by Aymkdn** [comment]
Can you check the debugger console to see the response that is sent back from the server?

**Comment by Ileouleyuki** [comment]
<code>http://shp.itn.ftgroup/entite/_vti_bin/Lists.asmx</code>401 UNAUTORIZED
but i'have got the access when i try to connect to http://shp.itn.ftgroup/entite/ int url toolbar

**Comment by Aymkdn** [comment]
1. Try to open `http://shp.itn.ftgroup/entite/_vti_bin/Lists.asmx` in your browser and check if you can access the page
2. `$SP().list("Contacts","http://shp.itn.ftgroup/entite/lists/test/")`: Instead of `"http://shp.itn.ftgroup/entite/lists/test/"`, it should be `"http://shp.itn.ftgroup/entite/"`. BTW, if your webpage is already under `"http://shp.itn.ftgroup/entite/"`, then no need to provide the URL. The URL must be only provided if you try to get data from another website.
3. If you use it within a browser, then it uses the credentials of the current user, so it should work...
4. Is it Sharepoint Online or On-Promise ?

**Comment by Ileouleyuki** [comment]
I do an erase of all the config :

EXPLANATION :

So i have a Sharepoint. I can access it with <code>http://shp.itn.ftgroup/sites/test/default.aspx</code>

In this sharepoint i have 3 sites with differents access but i'm the administrator of the root SharePoint.

Entite 1 >> <code>http://shp.itn.ftgroup/sites/test/Entite1/default.aspx</code>
Entite 2 >> <code>http://shp.itn.ftgroup/sites/test/Entite2/default.aspx</code>
Entite 3 >> <code>http://shp.itn.ftgroup/sites/test/Entite3/default.aspx</code>

In each site of Entite, i have :

-  One lists of contacts and i want to list items in a web application
-  One Library and i want to create folder and put some doc from the same web app

Contacts : <code>http://shp.itn.ftgroup/sites/test/EntiteX/Lists/Contacts/AllItems.aspx</code>
Library : <code>http://shp.itn.ftgroup/sites/test/EntiteX/File/Forms/AllItems.aspx</code>

So, i do the test of **Entite1**

_Try to open http://shp.itn.ftgroup/entite/_vti_bin/Lists.asmx in your browser and check if you can access the page_

I can access to a list of all SOAP operations when i try <code>http://shp.itn.ftgroup/sites/test/Entite1/_vti_bin/Lists.asmx</code> : 

![image](https://user-images.githubusercontent.com/26007537/35183894-50313e16-fded-11e7-9eaa-fa91f5ec795e.png)


 i think it's Ok for the credentials of the browser.

_$SP().list("Contacts","http://shp.itn.ftgroup/entite/lists/test/"): Instead of "http://shp.itn.ftgroup/entite/lists/test/", it should be "http://shp.itn.ftgroup/entite/". BTW, if your webpage is already under "http://shp.itn.ftgroup/entite/", then no need to provide the URL. The URL must be only provided if you try to get data from another website._

**First attempt :**

<code>
$SP().list("Contacts","http://shp.itn.ftgroup/sites/test/Entity1/").get().then(function(data) {
console.log(data);
}
</code>

RESULT : An http request type OPTION to <code>http://shp.itn.ftgroup/sites/test/Entity1/_vti_bin/Lists.asmx</code> with State 401 Unauthorized :(
But it's ok to access <code>http://shp.itn.ftgroup/sites/test/Entity1/_vti_bin/Lists.asmx</code> in the urltoolbar 

**Second attempt :**

<code>
$SP().list("http://shp.itn.ftgroup/sites/test/Entite1/Lists/Contacts").get().then(function(data) {
console.log(data);
}
</code>

RESULT : An http request type POST to <code>http://localhost/_vti_bin/Webs.asmx</code> my localhost ??? > 
I thinck i'm doing wrong but i can't find doc on the function 'list()' to know the options

**Third attempt :**

<code>
$SP().list("Contacts","http://shp.itn.ftgroup/sites/test/Entite1/").get().then(function(data) {
    console.log("toto");
    console.log(data);
});
</code>
}   
I have the same error than the first attempt (Same Request, Same state unauthorized)

_If you use it within a browser, then it uses the credentials of the current user, so it should work..._

I can acces to the list because i'm the administrator and i can do CRUD operation on the list of Cnntacts

_Is it Sharepoint Online or On-Promise ?_

The SharePoint is on a different server than my webapp

But the web app and the sharepoint is on the same AD Environnement like the futur users of my web app. For the moment the webapp is on localhost and i don't use NodeJS.

Thanks for your help

**Comment by Aymkdn** [comment]
Ah, it's on a different server! It's why you get this cross-domain request error. You have to test it on the same hostname. So your code must be executed on a webpage under `http://shp.itn.ftgroup`, otherwise you'll get this JavaScript error due to the browser's security.

Or you have to enable CORS on your Sharepoint/IIS settings to accept requests from another server.

**Comment by Aymkdn** [comment]
Is it OK now ?

**Comment by Aymkdn** [comment]
No news, so I'm closing it. Feel free to comment back if you have more questions.

**Comment by Ileouleyuki** [comment]
Sorry for the the late response. 
Now it's not OK because has you say it's croos-domain and it's not possible to activate it on the sharepoint server for security reason.
so i abandon this idea :(
Thanks for your help
