### ISSUE TITLE
Getting list of item with folderOptions pull out empty array.

### ISSUE THREAD

**Issue by biacho** [Aymkdn/SharepointPlus#93]
I want to see list of files in Library. Array is empty and in console log shows:

sharepointplus-5.0.min.js:8 XHR finished loading: POST "https://domain/_vti_bin/Webs.asmx".
e.ajax @ sharepointplus-5.0.min.js:8
(anonymous) @ sharepointplus-5.0.min.js:8
_promise @ sharepointplus-5.0.min.js:8
ajax @ sharepointplus-5.0.min.js:8
(anonymous) @ sharepointplus-5.0.min.js:8
_promise @ sharepointplus-5.0.min.js:8
_getURL @ sharepointplus-5.0.min.js:8
list @ sharepointplus-5.0.min.js:8
(anonymous) @ left_right_menus.js:1
sharepointplus-5.0.min.js:8 XHR finished loading: POST "https://domain/_vti_bin/Webs.asmx".
e.ajax @ sharepointplus-5.0.min.js:8
(anonymous) @ sharepointplus-5.0.min.js:8
_promise @ sharepointplus-5.0.min.js:8
ajax @ sharepointplus-5.0.min.js:8
(anonymous) @ sharepointplus-5.0.min.js:8
_promise @ sharepointplus-5.0.min.js:8
_getURL @ sharepointplus-5.0.min.js:8
list @ sharepointplus-5.0.min.js:8
(anonymous) @ left_right_menus.js:27
left_right_menus.js:86 **data.length: 0**

Code I using: 
```javascript
$SP().list("Images_Banner", "https://domain/sites/emea/").get({folderOptions: {
path: "/sites/emea/Images_Banner", 
show: "FilesAndFolders_InFolder"}
}).then(function(data) {
	console.log("data.length: " + data.length);
	if (data.length > 0) {
		console.log("Name: " + data[0].getAttribute("Name"));
	}
});
```

**Comment by Aymkdn** [comment]
1) You don't need to provide the URL if you're working in the same website (so if your page is already under "/sites/emea/" no need to write `list("Images_Banner", "https://domain/sites/emea/")`.... `list("Images_Banner")` is enough
2) The path is a relative path for a folder. So let's say you have a folder **icons** in your Images_Banner library, then path will be : `path:"icons"`. Here it looks like you want the files at the root of your Images_Banner library, so no need to provide path. Also the default value for `show` is already **FilesAndFolders_InFolder**, so no need to provide it too.

At the end:
```javascript
$SP().list("Images_Banner").get()
.then(function(data) {
  console.log("data.length: " + data.length);
  data.forEach(function(d) {
    console.log("Name: " + d.getAttribute("FileRef"));
  })
});
```

**Comment by biacho** [comment]
Well, simple as that :) I tried using just name of Library as you in your example but I was refered to "Name" (like name of column) not "FileRef" as you did. There existing dictionary with naming convention of fields? Obviously i can't using names of columns like in List case.

Thank You, for your help.

**Comment by Aymkdn** [comment]
For document libraries, as described in the documentation, there are 4 generic internal names that can be useful:
> **"BaseName"** is the name of the file/folder;
> **"FileRef"** is the full path of the file/folder;
> **"FSObjType"** is 0 for a file and 1 for a folder;
> **"File_x0020_Size"** the filesize in bytes.

If you have customized your list, then you can go to the List Settings and click on the column you want and check the URL to find the internal name. Example:
> mysharepoint.com/sites/mine/_layouts/15/FldEdit.aspx?List=%7B13916B96%2D3447%2D4B5B%2DAC5C%2D976F223B2FD4%7D&Field=**Internal_x0020_Name_x0020_x0020_Here**

**Comment by biacho** [comment]
No more questions or doubts. Thank you one more time for clarification.

**Comment by Aymkdn** [comment]
OK cool ! So I'm closing the issue :)
