### ISSUE TITLE
read content of file

### ISSUE THREAD

**Issue by RezaErfani67** [Aymkdn/SharepointPlus#95]
how can i read content of file such as .txt file or .js file from Document Library with nodejs?
can you please give me an example?

**Comment by Aymkdn** [comment]
With [`.ajax()`](https://aymkdn.github.io/SharepointPlus/utils.html#ajax) : 
```javascript
$SP().ajax({url:'https://url.com/file.txt', getXHR:function(xhr){ xhr.responseType = 'arraybuffer' }})
.then(function(data) {
  // data = ArrayBuffer of the file
})
```

**Comment by RezaErfani67** [comment]
nodejs not accept this syntax.
it return:
TypeError: "string" must be a stri
ng, Buffer, or ArrayBuffer
    at Function.byteLength (buffer
.js:475:11)

**Comment by Aymkdn** [comment]
For Node, it should be: 
```javascript
$SP().ajax({method:'get', url:'https://url.com/file.txt'})
.then(function(data) {
  console.log(data)
})
```

**Comment by RezaErfani67** [comment]
thanks alot ...
