### ISSUE TITLE
ASCII character generats error.

### ISSUE THREAD

**Issue by biacho** [Aymkdn/SharepointPlus#97]
Hi, 
I don't knot how can i manage with "&" character when i have this in folder name. I got this error: 

`{statusCode: 400, responseText: undefined, request: XMLHttpRequest}`

even when i using: `{whereEscapeChar: true}` in my code.

My whole code: 
```
$SP().list(root).get({whereEscapeChar: true, folderOptions: {
			path: parent + subfolder + subsubfolder,
			show: "FilesAndFolders_InFolder"
		}
	}).then(function(data) {
	createTable(data);
});
```

**Comment by Aymkdn** [comment]
How did you create a folder with a & ? When I try I receive this message from Sharepoint:
```
The file or folder name "L & D" contains invalid characters.
Please use a different name. Valid file or folder names cannot begin or end
with a dot, cannot contain consecutive dots and cannot contain any of the
following characters: ~ " # % & * : < > ? / \ { | }.
```

**Comment by Aymkdn** [comment]
Regarding `whereEscapeChar: true` it's used for the `where` clause, but you don't have any where clause, so it's useless.

I guess your `&` is in parent, or subfolder, or subsubfolder ? Then you can try to escape it by yourself in the path, something like : 
```javascript
(parent + subfolder + subsubfolder).replace(/&/,"&amp;")
```

If it doesn't work try : 
```javascript
(parent + subfolder + subsubfolder).replace(/&/,"%26")
```

Because I cannot create a folder with this invalid character, then I cannot test it...

**Comment by biacho** [comment]
Thanks for replay. 
Yes, folder was created with & in name. I don't know how :), I working with already created folders. 

I tried with `where` clause for first time, but didn't work so i removed it.  I will try and let know.

**Comment by biacho** [comment]
Yes, parent, subfolder and sun subfolder, all three can contain `&`. But unfortunately your proposition doesn't work either.

So I think i unfortunately have to change name convention on ShP.

Never less thank you for your help. You rock! 👍 :) 

I think you can close this issue.
