### ISSUE TITLE
Previous Page

### ISSUE THREAD

**Issue by RezaErfani67** [Aymkdn/SharepointPlus#99]
how can i get previous page?
data.NextPage is Present, but data.PreviousPage is not exist in the properties.

**Comment by Aymkdn** [comment]
`NextPage` is just the `listItemCollectionPositionNext` returned by Sharepoint, and they don't provide a "previous page".

If you have the `NextPage` it means you loaded the previous page at some point... So you can cache the `NextPage` for all your pages, and if the user wants to go to the previous page you just reuse the `NextPage` in cache for the requested the page.

**Comment by RezaErfani67** [comment]
your idea require programming on every page or function that use $SP().get()...
 it's better to write it in SharepointPlus 5.1  for using every where...
for large data it is important to have comfort  syntax... thanks alot

**Comment by Aymkdn** [comment]
As I said, it's not something that Sharepoint provides, so I cannot integrate it in v5.1

It's the responsability of each developer to setup his/her own system.

**Comment by RezaErfani67** [comment]
by the way thanks Aymkdn

**Comment by Aymkdn** [comment]
I gave a second thought, and maybe I could just save `NextPage` in `PreviousPage` (for example) each time a new call is done. I'm not sure if it would work. If I find some time I'll do some tests.

**Comment by RezaErfani67** [comment]
for first call it works correctly...
but for second call, the value of PreviousPage  is going to lost

**Comment by Aymkdn** [comment]
I'm not sure to understand what you mean.

**Comment by RezaErfani67** [comment]
in the first time that i click on {PeriviousPage}, it works correctly..
if i click again on {PriviousPage},it return Current Page because it's value is equal to NextPage.
after test,you can understand what i mean

**Comment by Aymkdn** [comment]
Ah OK I understand now... So it might be too complicated to do it in SharepointPlus.

So, yes you'll have to integrate it into your code and save the different NextPage into an array for example. You keep an index and each time you go back/forward you move your index

**Comment by koltyakov** [comment]
Hey @Aymkdn,

Are you using skip token for pagination?

**Comment by koltyakov** [comment]
Skip token has two modes:

- Paged=TRUE&p_ID=${skip}
- Paged=TRUE&PagedPrev=TRUE&p_ID=${skip}

But looks like it works well only with default ordering.

**Comment by Aymkdn** [comment]
@koltyakov I believe that `skip` is for REST API calls. SharepointPlus is based on Web Services. So I only use `listItemCollectionPositionNext`

**Comment by koltyakov** [comment]
Oh. Gotcha. I've never looked inside the lib, thought it was using REST.

**Comment by Aymkdn** [comment]
Ah. Actually `NextPage` is just a copy of `listItemCollectionPositionNext` (that looks like `Paged=TRUE&p_ID=ID`), nothing else. So maybe it's possible to change this string provided by Sharepoint in some ways, but you know how bad is the MS documentation...

**Comment by RezaErfani67** [comment]
@Aymkdn 
but i know you can ;)

**Comment by Aymkdn** [comment]
The `PagedPrev=TRUE` may work if I believe [this blog post](https://social.technet.microsoft.com/wiki/contents/articles/18606.sharepoint-2013-paging-with-sharepoint-client-object-model.aspx). I'll have to do some test to see how/if it works.

**Comment by Aymkdn** [comment]
It works. Thanks @koltyakov :-)

So, @RezaErfani67 you can use `listItemCollectionPositionNext:"Paged=TRUE&PagedPrev=True&p_ID="+ID`, with `ID` the first ID of the current set.

**Comment by koltyakov** [comment]
Cool! :)

**Comment by RezaErfani67** [comment]
yes it works...thanks all @Aymkdn @koltyakov
